### ISSUE TITLE
Show basic metadata on Show Page

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#101]
- Date created - do we want to have them display the same as in the search results? (e.g., XXXX --> "unknown")?
- Need wireframe for page

## Acceptance Criteria
- [x] Field labels do not display if field is not populated
- [x] Metadata groups do not display if no contained fields are populated
- [x] Use human readable dates from curate

**Comment by nikdragovic** [comment]
@maxkadel New details on date treatments in acceptance criteria, to address your question.

**Comment by nikdragovic** [comment]
@maxkadel I added a wireframe and other details to this ticket. Please let me know if I need to move some of this info to the epic or to a new ticket.

**Comment by maxkadel** [comment]
I have carved out a ticket for Persistent URL
https://github.com/emory-libraries/dlp-lux/issues/139
