### ISSUE TITLE
Use a replication-delayed index of the curate (prod) solr cloud

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#119]
The replication will run once day
The name needs to make sense and configured on the Hyrax side (.env.production file) lives in shared directory

**Comment by mprefer** [comment]
Replication delayed Solr index update established.
lux_collection created in Zookeeper and Solr and populated.
Crontab entry created to update once a day at 6:00AM (1:00AM UTC).
Runs on solr-cor-1.library.emory.edu

Will confirm cron job execution success/failure tomorrow.

**Comment by mprefer** [comment]
Modified the SOLR_URL in /opt/dlp-lux/shared/.env.production and restarted Apache.
Search results are displayed.
