### ISSUE TITLE
Implement spike for searching indexed metadata fields (Column J)

### ISSUE THREAD

**Issue by srodge5** [emory-libraries/dlp-lux#121]
The following 11 fields will be the initial set:
:title
:creators
:contributors
:abstract
:table_of_contents
:keywords
:subject_topics
:subject_names
:subject_geo
:parent_title
:uniform_title
:publisher

**Comment by maxkadel** [comment]
There's a good test for this now, not sure the best way to illustrate it otherwise.

**Comment by mark-dce** [comment]
@nikdragovic & @tmiles2 - when we write a ticket like this that references "Column J" or "the spreadsheet", can we make sure to link to the spreadsheet in question in the ticket - i.e. I don't know which column J this ticket refers to unless I already have that spreadsheet open (I actually have lots of spreadsheets 😉 )

**Comment by tmiles2** [comment]
[Metadata spreadsheet  ](https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=0)
