### ISSUE TITLE
Build a initial search test suite

### ISSUE THREAD

**Issue by srodge5** [emory-libraries/dlp-lux#122]
- [x]  Test for search against at least one field in prod like environment
- [x]  Test suite does not run during continuous integration  
- [x]  Specify which prod like environment to run against

**Comment by maxkadel** [comment]
* Right now I have this as a rake task which can be called from the command line, and which starts a browser and drives it. I've hard-coded digital-arch as the environment for now.
* Does "Specify which prod like environment to run against" mean the user should be able to enter that as a variable? Or have it as an environment variable? Or just let people know what prod-like environment it runs against?

**Comment by maxkadel** [comment]
Relevancy tests can be run from the command line using rake task `PROD_LIKE_ENV=qa|test|arch|prod rake lux:relevancy`
