### ISSUE TITLE
Implement results of Targeted Field Search spike

### ISSUE THREAD

**Issue by srodge5** [emory-libraries/dlp-lux#125]
## Requirements
- [x] Common Fields is the default/first option, and it includes: all Title, Creator, and Subject fields below as well as 
:system_of_record_ID
:primary_repository_ID
:emory_ark
:local_call_number
:other_identifiers

- [x] Title is the second option and it includes: 
:title 
:uniform_title 
:series_title 
:parent_title

- [x] Creator is the third option and it includes: :creators
:contributors

- [x] Subject is the fourth option and it includes: 
:keywords, 
:subject_topics
:subject_names
:subject_geo
:subject_time_periods
:keywords

- [x] All Fields is the fifth option and it includes:
:institution
:primary_language
:publisher
:local_call_number
:other_identifiers
:holding_repository
:system_of_record_ID
:primary_repository_ID
:related_material_notes
:place_of_production
:keywords
:administrative_unit
:subject_topics
:subject_names
:subject_geo
:subject_time_periods
:conference_name
:title
:uniform_title
:series_title
:parent_title
:sublocation
:creators
:contributors
:sponsor
:data_producers
:grant_agencies
:content_genres
:grant_information_notes
:author_notes
:notes
:data_source_notes
:geographic_unit
:technical_note
:issn
:isbn
:abstract
:related_publications
:related_datasets
:emory_ark
:table_of_contents

## Acceptance Criteria
- [ ]

**Comment by nikdragovic** [comment]
@bess The fields for the dropdowns are finalized; I am just waiting for objects to test the work against.

**Comment by wulman16** [comment]
![Screen Shot 2020-01-13 at 4.40.15 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/e9423ce1-ac59-4db3-a64c-66d696474f55)![Screen Shot 2020-01-13 at 4.40.23 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/07993db3-2cd4-44a7-aa1e-bb476fd01ef9)
