### ISSUE TITLE
Define human readable date field in curate

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#126]
Index date fields in curate such that they can be displayed like this:

- [x] "XXXX" for date fields in Curate display as "unknown" in Lux.
- [x] "193?" for date fields in Curate display as "1930s" in Lux.
- [x] "1934?" for date fields in Curate display as "1934 approx." in Lux.

- [x] "194X/195X" for date fields in Curate display as "within the 1940s or 1950s" in Lux.
- [x] "1942?/1944?" for date fields in Curate display as "between 1942 and 1944" in Lux.

MAYBE (if @nikdragovic can find an example):
- [x] "XXXX-09-07" for date fields in Curate display as "Month 07 Day 09, year unknown" in Lux. (possible to script this to show calendar day?)

**Comment by nikdragovic** [comment]
@eporter23 DCE is seeking an example from our collections that demonstrates the last ETDF example noted here.  A tangible use case sounds necessary here and I apologize that I don't have a comprehensive enough grasp of the collections to source this.

**Comment by eporter23** [comment]
@nikdragovic examples in Langmuir include MSS1218_B014_I042, MSS1218_B016_I199, and 
MSS1218_B018_I003 (in batch 1). I can try to load these up in curate-test or curate-arch so we can see them, but I imagine they are photos with a month and date indicated and not a year. I also want to note that XXXX-09-07 should indicate 09 as the month and not 07 as noted above.

**Comment by eporter23** [comment]
Have you all looked at this gem from Duke, btw? https://github.com/duke-libraries/edtf-humanize

**Comment by rotated8** [comment]
I think I had heard of that before, but I'd forgotten about it. Thanks! @wulman16- you should check that out.
