### ISSUE TITLE
Implement metadata grouping

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#127]
## User Story
As an end-user, I want to view metadata for an object that is grouped for easy skimming, so that I can easily locate the information I am looking for or better understand what segments of information are available.

## Acceptance Criteria
- [ ] Metadata groups do not display if no contained fields are populated

## References
[Metadata spreadsheet](https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=696928716)
"Field grouping" tab is the main information source for this ticket.

## Wireframe
[Link](https://app.zenhub.com/files/172767026/9c9eca0d-b001-40be-96d8-bb4836b4d9e2/download)
Blue coloring means default element in Blacklight. Green means customization anticipated. For the purposes of this ticket, only the metadata groups referred to in the spreadsheet at relevant.

**Comment by maxkadel** [comment]
replaced by smaller tickets
