### ISSUE TITLE
Decide how to set up Shibboleth

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#133]
Create an ADR for how to setup Shibboleth. Use the curate setup? Request new setup?

**Comment by SolomonHD** [comment]
There's been some developments.

It appears that Gerry who manages Shibboleth already has metadata for lux.

So I think we'll skip the middle step of adding this to curate and have digital standalone

**Comment by SolomonHD** [comment]
ADR was merged, shibboleth had a few issues that had to be resolved:
1) Emory IDP was rejecting Lux shibb callbacks b/c lux didn't have ssl enabled throughout.
2) Switching target group of Lux to https instead of http that it was on resolved that issue. Shibb worked after that point.
