### ISSUE TITLE
SPIKE: Persistent URL?

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#139]
## Acceptance Criteria
- [ ] We have a clear answer about what the persistent URL is
- [ ] That URL resolves somewhere
- [ ] Appropriate tickets have been made to describe any work required by the above 

Note: There has been a suggestion to use PURL (e.g. digital.library.emory.edu/purl/7375tb2rcs-cor) if that is the decision that is reached, we will need development time to implement urls in that pattern.

**Comment by tmiles2** [comment]
@maxkadel After speaking with Emily and Collin, the decision was made for Emory to-do this work post beta. We recommend de-scoping this work from the sprint. 

Possible impact would be to one field (Persistent URL) that displays on the Show Object page
