### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#143]
* Implementation reference link: https://getbootstrap.com/docs/4.0/getting-started/theming/
* Bootstrap Mapping: https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit#gid=0

**Comment by tmiles2** [comment]
https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit#gid=0
