### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#150]

**Comment by nikdragovic** [comment]
We originally wanted to display a tagline or some explanatory text as shown on the [Ursus](https://ursus.library.ucla.edu/) homepage. In the interest of preserving vertical space, it may make sense to see if something like this can work as an overlay on the hero: 

Emory Digital Collections delivers long-term digital access to unique cultural heritage and scholarship collections from Emory University.

**Comment by tmiles2** [comment]
Can we close this epic @nikdragovic? If so can we remove it from the sprint goals?
