### ISSUE TITLE
Populate metadata for "This item contains:" partial for show page

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#154]
## References
[Metadata spreadsheet](https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=696928716)
"Field grouping" tab is the main information source for this ticket.

## Wireframe
[Link](https://app.zenhub.com/files/172767026/9c9eca0d-b001-40be-96d8-bb4836b4d9e2/download)
Blue coloring means default element in Blacklight. Green means customization anticipated. For the purposes of this ticket, only the metadata groups referred to in the spreadsheet at relevant.

**Comment by maxkadel** [comment]
What fields in Curate / Solr should be used to populate this

**Comment by tmiles2** [comment]
@eporter23 would you happen to know the answer to Max's question above?

**Comment by eporter23** [comment]
I suspect that's an extraneous copy and paste in the wireframe. The "This Item Contains" section would show links to child works on a parent object, so this should not apply for a simple/flat object.

**Comment by tmiles2** [comment]
@wulman16 @maxkadel Emily responded above.

**Comment by wulman16** [comment]
**Before:**

![Screen Shot 2019-12-17 at 2.27.32 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/09a9da11-8f11-44ea-97d9-22c22ae9cacb)



**After:**

![Screen Shot 2019-12-17 at 2.28.09 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/ae10575b-1198-4032-8249-0b882662406a)
