### ISSUE TITLE
Implement Redirects for Persistent URLs

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#156]
According to decisions: https://docs.google.com/document/d/1kLGqqiGBImiuWdIH5lZY2efip0bBZ76QnUBFxFZ023k/edit

See [Curate ticket 983](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/983). The Persistent URL (for Lux) displays in the More Information pane of the Universal Viewer, but a redirect is needed to make the address functional.

Redirect notes: 
the base url https://digital.library.emory.edu/purl should redirect to 
https://digital.library.emory.edu/catalog in Lux.

e.g. https://digital.library.emory.edu/purl/123xjdjd99kid-cor
should resolve to https://digital.library.emory.edu/catalog/123xjdjd99kid-cor

**Comment by eporter23** [comment]
@nikdragovic please note that we've been building this out in [Curate ticket 983](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/983). The placeholder URL is showing in Curate now. We should coordinate on how to display this in Lux.
