### ISSUE TITLE
Change "Misc Details" heading on show page to "Additional Details"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#158]

**Comment by maxkadel** [comment]
This work also included changing file names / spec names for maintainability.

![image](https://user-images.githubusercontent.com/45948126/71025540-3d7dd100-20d5-11ea-9ce6-b9fdb6cef0f9.png)

**Comment by maxkadel** [comment]
@tmiles2 - not sure why this is back to "In progress"? Is there additional work that needs to be done?

![image](https://user-images.githubusercontent.com/45948126/71129045-95433780-21bc-11ea-8aa7-b889bf4605ed.png)

**Comment by maxkadel** [comment]
Nevermind, Bess filled me in, it should be good to close.
