### ISSUE TITLE
Configure a live Blacklight application

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#16]
## Story
As a Product Owner, I want to access a public version of the application in a production-like environment, so that I can perform functional/QA testing in an environment that closely approximates the experience of an end-user.

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
According to Colin, the dlp-lux repo currently contains Blacklight 6.2, which matches Hyrax.

#### Checklist
- [ ] Application resembles public demo version at projectblacklight.org (barring any version disparities)

**Comment by rotated8** [comment]
Curate is on [6.20.0](https://github.com/emory-libraries/dlp-curate/blob/master/Gemfile.lock#L876), and Lux has ["~> 6.20"](https://github.com/emory-libraries/dlp-lux/blob/master/Gemfile#L9)
