### ISSUE TITLE
Display username of logged in user in navbar

### ISSUE THREAD

**Issue by little9** [emory-libraries/dlp-lux#174]
Right now there is a just a `Logout` link when you are signed in. The username should also be displayed.

- [x] When you log in with Shibboleth, you should see your username in the upper right corner of the page

**Comment by wulman16** [comment]
![image.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d075f947-37d8-41eb-96b7-a9f5b67b8ae4)
