### ISSUE TITLE
Cover additional human-readable date formats in Curate

### ISSUE THREAD

**Issue by wulman16** [emory-libraries/dlp-lux#177]
In addition to the cases listed in #126, there are other date formats in Curate that need to be indexed in a human-readable format:
- [x] "1936-12-03" displays as "December 3, 1936"
- [x] "1962-02" displays as "February 1962"
- [x] "1940-02~" displays as "February 1940 approx."

**Comment by eporter23** [comment]
@wulman16 I am fixing any instances of YYYY-YYYY because those are invalid, they should be YYYY/YYYY. So, no need to work around those.

**Comment by maxkadel** [comment]
I can't seem to enter the last example into my local instance of Curate? Would it have to be entered in some other way? 

![image](https://user-images.githubusercontent.com/45948126/71289067-27247f00-233a-11ea-8a1a-1b6147812c64.png)

**Comment by eporter23** [comment]
@maxkadel if you were entering a date range between 1943 and 1944 you would enter it as 1943/1944 in the form.

**Comment by wulman16** [comment]
Part of a sample Solr document that converts "2020-01~" (at top) to "January 2020 approx." (at bottom):
![Screen Shot 2020-01-07 at 11.38.17 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/f8c8fe26-68fa-4721-976f-34f4ffb8af52)
