### ISSUE TITLE
Link Rights Statement - Controlled field values to associated information at rightsstatement.org

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#183]
URIs for statements here: https://rightsstatements.org/page/1.0/?language=en

Example using Creative Commons: https://repository.duke.edu/dc/earlymss/emsgk01023

**Comment by nikdragovic** [comment]
@maxkadel Should I be able to test this by filtering arch by Rights Status and then checking the show pages for the resulting objects?

**Comment by maxkadel** [comment]
@nikdragovic - Yes, that would work. I believe it's also a required field, so it should be present on any CurateGenericWork (aka, anything that is not a Collection).
