### ISSUE TITLE
Customize metadata display labels

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#185]
## Story
As a Repository Administrator, I want to customize end-user metadata display fields, so that users will find the metadata more intuitive.

## Acceptance Criteria
- [x] Labels appear as noted in [this document](https://docs.google.com/document/d/1vyZKU7diWfm2AiXspVxL6txP1Sk7WjxFKv1l_jyQ-SY/edit?usp=sharing).

**Comment by wulman16** [comment]
Before and After for Date Issued -> Date Published/Issued:

![Screen Shot 2020-01-07 at 10.45.45 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/a7e18ee2-e2af-477f-9098-ba737e02482f)

![Screen Shot 2020-01-07 at 10.45.19 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/9432e4aa-0ea1-443b-9a8d-9d3e59df705d)
