### ISSUE TITLE
Display desired facets

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#187]
### Wireframe
![Facets](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/524c70b3-e9d8-40ff-b0d9-51a2319e5650)

### Acceptance Criteria
- [ ] Facet values display number of items contained
- [ ] Date facet allows user to type in a query for a date span
- [ ] "Date" facet combines "Date created" and "Date issued" fields

**Comment by maxkadel** [comment]
It looks to me like this is already the case (the right side of this image).
![image](https://user-images.githubusercontent.com/45948126/71854169-5ca3c900-30ab-11ea-85a6-4864c1992372.png)

**Comment by maxkadel** [comment]
Oh, so, you'd like it to be like "Library (27) [down-carat]", is that right?

**Comment by nikdragovic** [comment]
This ticket has now been replaced with #188 and will be closed.
