### ISSUE TITLE
Add collection to facet list and order facet list

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#188]
### Wireframe
![Facets](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/524c70b3-e9d8-40ff-b0d9-51a2319e5650)

### Acceptance Criteria
- [x] Facets are labeled as depicted in wireframe above
- [x] Facets are in order displayed above
- [x] "Date" facet combines "Date created" and "Date issued" fields

**Comment by maxkadel** [comment]
Do you mean ordering the results, or ordering the facets themselves?
* The results are currently ordered by number of results, highest to lowest
* The facets are ordered based on how they appear on this spreadsheet - https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=0 . How would you like them to be ordered?

**Comment by nikdragovic** [comment]
@maxkadel This refers to the order of the facets themselves. The desired order is what is depicted in the wireframe on this ticket.

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/72016168-43c52000-3231-11ea-9818-f0b72c1995c1.png)
![image](https://user-images.githubusercontent.com/45948126/72016183-4fb0e200-3231-11ea-9876-dfe4cc752a32.png)
