### ISSUE TITLE
SPIKE: Google Analytics configuration

### ISSUE THREAD

**Issue by wulman16** [emory-libraries/dlp-lux#190]

**Comment by kristianserrano** [comment]
I've generated the property and tracking code to be included in the header.
```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-61756900-33"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-61756900-33');
</script>
```
I've set up `q` as the search parameter and `search_field` as a "category" parameter. If you don't think `search_field` should be identified as a search category, or if you think something else could be, let me know and I'll make the change.

I've also set up GA to strip the above parameters and `utf8` from the URLs it logs. This will help keep data clean in the reports.

I've configured the same for curate as well with its own tracking code:
```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-61756900-34"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-61756900-34');
</script>
```

@nikdragovic and @eporter23 have access to these properties as does the LTDS Google account.

Please let me know if you have any questions.

**Comment by nikdragovic** [comment]
@bess @maxkadel Just wanted to call your attention to Kristian's comments above; working with Rachel to schedule our meeting.

**Comment by kristianserrano** [comment]
## Development Tracking Code
```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-61756900-35"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-61756900-35');
</script>
```

**Comment by kristianserrano** [comment]
@bess Below is screenshot of how I've configured the view for Lux with filters for query string parameters. I figured this might be a good starting point for the discussion.

I’m still looking into what query parameters to include or strip. For example, @eporter23 and I were considering testing facet parameters as search categories and seeing how that data might look.
## Screenshot of Lux GA View Settings
<img width="384" alt="Screen Shot 2020-01-07 at 3 50 26 PM" src="https://user-images.githubusercontent.com/1796189/72007444-ab726f80-321f-11ea-9a5f-23a8a5c463c6.png">
