### ISSUE TITLE
Shibboleth returns user to previous page after authenticating

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#191]
Given that I am not logged into Lux,
When I try to access a Log In Required item via a direct link,
Then I am presented with a Shibboleth login page that sends me to the item show page after successfully authenticating.

Given that I am not logged into Lux,
When I try click on a Log In Required search result,
Then I am presented with a Shibboleth login page that sends me to the item show page after successfully authenticating.

- Time boxed at 5 points

**Comment by devanshu-m** [comment]
https://github.com/emory-libraries/dlp-curate/blob/main/app/controllers/omniauth_callbacks_controller.rb#L9

**Comment by bwatson78** [comment]
No screenshots to provide. PR made: https://github.com/emory-libraries/dlp-lux/pull/669/files

**Comment by bwatson78** [comment]
Hopefully the last PR I have to make for this task. 
https://github.com/emory-libraries/dlp-lux/pull/678

**Comment by eporter23** [comment]
Looks great! Should be good for prod.

**Comment by eporter23** [comment]
Works as hoped in prod!
