### ISSUE TITLE
In Curate, save a year_for_lux field to Solr that combines year_created and year_issued, and that de-duplicates and puts them in order

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#193]

**Comment by eporter23** [comment]
@nikdragovic @wulman16 @tmiles2 will this impact Langmuir items that have already been ingested?

**Comment by nikdragovic** [comment]
@wulman16 @maxkadel I am not seeing the date facet in digital-arch. Is that related to this ticket, or one of the prior tickets we closed out?

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/72283867-b35e5500-360d-11ea-856f-d43334629eeb.png)
