### ISSUE TITLE
Install Google Analytics tracking codes on environments

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#195]
These should be set in an environment variable called `GA_TRACKING_CODE` in `.env.production`

Production environment code: UA-61756900-33
Other environments (qa and arch): UA-61756900-35

More detail in comment thread for spike ticket #190

### Acceptance Criteria
- [x] Properties are visible in Emory's Google Analytics account

**Comment by SolomonHD** [comment]
The tracking codes have been manually placed on the digital servers and also committed to the cor-cm repo's vault file.

**Comment by nikdragovic** [comment]
![Screen Shot 2020-01-10 at 3.47.46 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/9424b7b9-4d51-4b8d-b61c-a89ce3ed425e)

Analytics is working in arch; just wanted to provide a screenshot. @maxkadel @kristianserrano @SolomonHD

**Comment by nikdragovic** [comment]
Pending further testing for acceptance.

**Comment by nikdragovic** [comment]
![Screen Shot 2020-01-10 at 4.02.01 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/3c773894-366c-4bf3-980f-cbd62dd7a75a)
Collection events; I triggered these.
