### ISSUE TITLE
Implement DCE collection-level analytics code

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#196]
Using information documented here: https://docs.google.com/document/d/17h6zvTVEjasVX8JH1hHMLFHVGZzHFdzUQBcej93zYP4/edit?usp=sharing

### Acceptance Criteria 
- [x] Google Analytics can display metrics by collection and holding repository / library

**Comment by maxkadel** [comment]
Working for DCE environment 
![image](https://user-images.githubusercontent.com/45948126/72097854-4b48ff80-32eb-11ea-98ab-a6775f7f9208.png)

**Comment by nikdragovic** [comment]
Including screenshots of various events working on the dev property, but not yet production. I have triggered some events and will close this as soon as I can verify the traffic there.

![Screen Shot 2020-01-15 at 3.34.28 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/fc8c40d2-1547-404b-bfbb-a5384010374c)![Screen Shot 2020-01-15 at 3.35.18 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b833e4ee-6555-4883-bc30-b2373492b653)![Screen Shot 2020-01-15 at 3.35.27 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/665dcb74-54c6-4bbe-abc9-503c0a061e7c)![Screen Shot 2020-01-15 at 3.35.38 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/abd40f07-367e-4e42-a066-5e884f5d72ac)
