### ISSUE TITLE
Metadata grouping placement on show page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#199]
Instead of static placement, metadata groupings should adjoin each other vertically, without negative space.

**Comment by maxkadel** [comment]
* No Blacklight sidebar
* Below are 3 examples with small, medium, and large sets of metadata

## Small 
![image](https://user-images.githubusercontent.com/45948126/72109263-8f47fe80-3303-11ea-9bbc-c4264208a3eb.png)

## Medium
![image](https://user-images.githubusercontent.com/45948126/72109290-9bcc5700-3303-11ea-84c2-9b7588954f4d.png)

## Large
![image](https://user-images.githubusercontent.com/45948126/72109187-5ad44280-3303-11ea-9e43-e8ad7756b643.png)
