### ISSUE TITLE
(SPIKE) Install Blacklight advanced search plugin

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#202]
Verify whether plugin works with Blacklight 7, and decide how to proceed based on those results.

**Comment by wulman16** [comment]
The advanced search page from #214:

![Screen Shot 2020-01-09 at 4.43.58 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/885f4180-3c44-4921-8b23-3bb88cd684e4)
