### ISSUE TITLE
Identify a multi-volume book in Lux to serve as a durable test object

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#203]
## Objects
https://curate-arch.library.emory.edu/concern/curate_generic_works/030prr4xkj-cor?locale=en	

https://digital-arch.library.emory.edu/catalog/030prr4xkj-cor

https://curate-arch.library.emory.edu/concern/curate_generic_works/665h9w0vx3-cor?locale=en	

https://digital-arch.library.emory.edu/catalog/665h9w0vx3-cor

**Comment by tmiles2** [comment]
Tiffany will check with Emily about when we load a multi-volume book

**Comment by tmiles2** [comment]
Emily has loaded two multi-part books into arch, we are still pending open questions discussion which is scheduled for 1/16. That meeting will include Nik, Emily, Cari and Tiffany
