### ISSUE TITLE
Make three or more sample objects to compare layout

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#204]
- [x] Make a small, medium and XXL object in terms of their metadata 
- [x] Take a screen shot of each for use in analysis of show page layout

See:

https://github.com/emory-libraries/dlp-lux/pull/209

and 

https://github.com/emory-libraries/dlp-lux/pull/210

**Comment by bess** [comment]
@nikdragovic It looks like @maxkadel did this already, so I'm just keeping the board up to date and indicating that this has been done.

**Comment by nikdragovic** [comment]
@maxkadel Thanks for generating these! We do not want to reinstate Blacklight sidebar and we'll exclude headers for metadata sections when those sections are empty. The spacing looks great!

**Comment by nikdragovic** [comment]
@bess @maxkadel Thanks for generating these! We do not want to reinstate Blacklight sidebar and we'll exclude headers for metadata sections when those sections are empty. The spacing looks great!
