### ISSUE TITLE
SPIKE: metadata grouping layout

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#205]
- [x] Using the three or more screenshots of variously populated metadata fields, generate three possible layout choices
- [x] Give these to @nikdragovic and Emily and make a choice
- [x] The chosen wireframe will be implemented in #199

Two choices so far: 

https://github.com/emory-libraries/dlp-lux/pull/209

and 

https://github.com/emory-libraries/dlp-lux/pull/210

**Comment by nikdragovic** [comment]
@maxkadel Thanks for generating these! We do not want to reinstate Blacklight sidebar and we'll exclude headers for metadata sections when those sections are empty. The spacing looks great!
