### ISSUE TITLE
Advanced search initial configuration 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#218]
Get advanced search working as well as fielded search

**Comment by wulman16** [comment]
As it stands now in v0.4.3, fielded search is working. If by "advanced search" we mean targeting multiple fields with different search terms (.e.g, https://digital-arch.library.emory.edu/catalog?utf8=%E2%9C%93&op=AND&common_fields=&title=anna&creator=trollope&subject=&all_fields=&search_field=advanced&commit=Search), that is also working. But there are a few existing issues around the edges of advanced search that will need to be addressed, depending on the requirements that end up being fleshed out:

1. The simple search bar at the top does not work when the user is on the advanced search page. This problem will be addressed in #219.
2. Facets on the advanced search page have unexpected behavior. When the user clicks on one, an advanced search is immediately conducted with the terms the user has already typed in. The user can't narrow down with facets until they are brought to the search results page itself. This problem could be resolved in a separate ticket, though an easy solution could be to remove facets from the advanced search page entirely.
3. Out of the box, the blacklight-advanced-search plugin introduced Boolean search in the simple search bar but not in advanced search. However, the "Search tips" sidebar on the advanced search page leads the user to believe that Boolean search would work on that page. An easy solution would be simply to remove the bullet point about Boolean search from that page.
4. When the user conducts an advanced search, a Start Over button appears at the top of the search results page. It seems to me that this button should take the user back to the advanced search page, but it currently takes the user back to the home page.
5. At the bottom of the advanced search page, there is an unpopulated dropdown for sorting the results. This could either be removed for now or left to be addressed when search results sorting is targeted during a later sprint.

Once the requirements for advanced search are hammered out later this week, we can move forward with the rest of these issues.
