### ISSUE TITLE
Advanced search page should not have regular search bar on it

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#219]
Advanced search page should not have regular search bar on it

**Comment by wulman16** [comment]
**Before:**

![Screen Shot 2020-01-15 at 11.47.15 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/8a005c2b-b40e-4b44-b3f3-2db6d5cf7620)

**After:**

![Screen Shot 2020-01-15 at 11.47.30 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/789f11dc-9071-4f5e-a5c4-d902e9a63c1d)
