### ISSUE TITLE
For collection member objects, "This item is part of" "Collection Title" links to parent collection page

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#223]
![Lux Beta Wireframes - Working Document - View Simple Object - Update.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/bcab0b61-d215-4aa4-8f5d-ede87476520c)

When on an item show page, the "This item is part of" section should contain the collection name with an embedded link that takes the user to the collection show page.

**Comment by nikdragovic** [comment]
This issue duplicates #230

**Comment by nikdragovic** [comment]
This ticket does not, in fact, duplicate #230 and was closed on accident. Apologies.

**Comment by maxkadel** [comment]
A CurateGenericWork links to its parent collection's page.

![image](https://user-images.githubusercontent.com/45948126/73688174-81369500-4699-11ea-99a4-aee0ce182d62.png)
