### ISSUE TITLE
Date facet should use a date slider

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#228]
- [x] Instead of displaying years as facet strings, use a date slider. 

Example:

![date_slider.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/35752dd1-b37e-46f3-8f9b-35ab06cb9734)

## User Story
As an end user, I would like to refine dates using a date slider, so that I can easily select ranges of dates that are relevant to my search.

## Acceptance Criteria
- [x] Dates can be added as text or using slider.
- [x] Date range allows users to select years between 1000 and current year.
- [x] Unknown dates do not appear when slider is used.

**Comment by wulman16** [comment]
![Screen Shot 2020-01-16 at 1.05.06 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/37e5882b-8449-4fb1-b304-a906602e8386)
