### ISSUE TITLE
Add link to member objects from collection view page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#230]
## User Story
As an end user, I would like to follow a link from a general collection page to a list of its objects, so that I can easily view and explore a the items comprising that collection.

## Wireframe
![Collection View](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/5d261a3c-f648-4a67-9e5f-f9b479bf8f47)

**Comment by maxkadel** [comment]
@nikdragovic  - this is great info, and really gives me specifics I can sink my teeth into - thank you! 

What should the Finding Aid link be? (e.g. is there a field in Curate that has this information? if not, we'll need to create and populate that field in Curate, and save it to the Solr index, before it will appear in any of the Digital environments).

**Comment by nikdragovic** [comment]
@maxkadel This collection object shows an example of that information being populated: https://curate-arch.library.emory.edu/collections/815p8cz8wv-cor?locale=en

**Comment by maxkadel** [comment]
- Adds partial and link for "View items in this digital collection" on Collection pages
- Creates a separate partial for "About This Collection". This partial currently **only** contains:
  - Description / Abstract
  - Creator
  - Library
- Compare to "About This Item" (for Curate Generic Works, not Collections) which contains:
  - uniform_title_tesim: 'Uniform Title'
  - series_title_tesim: 'Series Title'
  - parent_title_tesim: 'Title of Parent Work'
  - creator_tesim: 'Creator'
  - contributors_tesim: 'Contributor'
  - human_readable_date_created_tesim: 'Date Created'
  - human_readable_date_issued_tesim: 'Date Published / Issued'
  - data_collection_dates_tesim: 'Data Collection Dates'
  - human_readable_content_type_tesim: 'Format'
  - content_genres_tesim: 'Genre'
  - extent_tesim: 'Extent / Dimensions'
  - primary_language_tesim: 'Primary Language'
  - notes_tesim: 'Note'
  - abstract_tesim: 'Description / Abstract'
  - table_of_contents_tesim: 'Table of Contents'
- Work that still needs to be done is adding the number of search results this would link to

![image](https://user-images.githubusercontent.com/45948126/72552253-7a6bed80-3864-11ea-9708-53c9ccea31de.png)

**Comment by maxkadel** [comment]
- [ ] Create partial for "View items in this digital collection"
- [ ] Add that partial to the Collection show page
- [ ] Link to facet search for all items in the collection
- [ ] Show the number of items that will be returned based on the facet search on the Collection page
