### ISSUE TITLE
Edit help text for advanced search page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#234]
Revised text should appear as following (based on initial findings documented in #218):

Search tips
- Select "match all" to require all fields.
- Select "match any" to find at least one field.
- Use quotation marks to search as a phrase.
- Use "+" before a term to make it required. Otherwise, results matching only some of your terms may be included.
- Use "-" before a word or phrase to exclude.
- Truncation and wildcards (*) are not supported - word-stemming is done automatically.

**Comment by wulman16** [comment]
![Screen Shot 2020-01-27 at 10.33.33 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/9c0b762b-7946-456c-acbf-065a4c171a76)
