### ISSUE TITLE
Customize hierarchical object view on Blacklight show page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#241]
## Wireframe
![Possible wireframe, approved at Emory](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/a1d874ce-c9a0-454e-bed4-7329f4b128d0)

## Object Links
One title for multiple years
https://curate-arch.library.emory.edu/concern/curate_generic_works/030prr4xkj-cor?locale=en	

https://digital-arch.library.emory.edu/catalog/030prr4xkj-cor

**Comment by maxkadel** [comment]
Thanks Figgy!

Logged in user sees download, share, and fullscreen buttons
![image](https://user-images.githubusercontent.com/45948126/73594292-fc058180-44da-11ea-8274-995a54f3df4c.png)

Logged out user does not
![image](https://user-images.githubusercontent.com/45948126/73594303-0d4e8e00-44db-11ea-9dac-9f40f798a5b1.png)

**Comment by nikdragovic** [comment]
Updated wireframe to demonstrate suppression of viewer for these object types. I re-ordered the middle sections as well based on this change.[Uploading... Lux Beta Wireframes - Working Document - Emocad without Header.jpeg ]

**Comment by wulman16** [comment]
![Screen Shot 2020-02-12 at 1.56.03 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/53b48ba1-c6a7-41e5-86ce-e1a4d084b69d)
