### ISSUE TITLE
Update collection show page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#242]
## Wireframe
![Lux Beta Wireframes - Working Document - Yearbooks (1).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4010ca1d-7bfe-42b6-a67d-8c08cde54939)

## Details
"Find" grouping contains these fields:
:primary_repository_ID (N/A for now)
:system_of_record_ID
:emory_ark
:other_identifiers
:institution
:holding_repository
:administrative_unit
:local_call_number
:contact_information

"About" grouping contains these fields:
:abstract
:finding_aid_link
:creator
:contributors
:primary_language
:notes

"Subjects / Keywords" grouping contains these fields:
:subject_topics
:subject_names
:subject_geo
:subject_time_periods
:keywords

## Acceptance Criteria
- [x] Field labels are not shown if field is not populated
- [x] Where applicable, labels match adjustments made for labels on object show page

**Comment by wulman16** [comment]
![Screen Shot 2020-01-24 at 4.15.15 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/156baf98-4074-47fa-b51d-33a017ff6f15)
