### ISSUE TITLE
Implement sort options for search results

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#245]
Blacklight defaults for sort:
relevance
year
author
title

**Comment by wulman16** [comment]
![image.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/eb5c85ac-549d-415c-9194-548caeadd13e)

**Comment by nikdragovic** [comment]
@wulman16 Thanks for switching "author" to "creator." Can we change "year" to "date"?

**Comment by wulman16** [comment]
![image.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/c77e91e8-93c3-48a6-91d6-e7c4cd7711c6)

**Comment by wulman16** [comment]
All sort fields are ready to test in the digital-test environment

**Comment by nikdragovic** [comment]
Awesome, thanks @wulman16. This appears to be behaving as expected for the defaults and I will retest when the customizations in #277 are deployed.
