### ISSUE TITLE
Confirm "Public" objects display as intended

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#246]
## User Story
As a collection manager, I want the public (not logged in to Lux) to be able to view/play, download, share full quality files for selected digital objects, so that I can fulfill my organization’s public service mission while respecting rights and agreements.

## Acceptance Criteria
Given
I am an Emory Collection Manager
When
I deposit material without rights restrictions and select the Public visibility option in Curate
Then
I can deliver a high quality content file through Lux to any user who wants to view, download, or share it with others; and I can see and manage the preservation files in Curate

Given
I am a content consumer not logged into the Lux product
When
I discover an object through the Lux product 
Then
I am able to see a high quality file in the Lux viewer and I can download and share it with others

Given
I am a content consumer not logged into the Lux product
When
I discover a Cor repository object because someone has shared a link to it
Then
I am able to see a high quality file in Lux or load it into another IIIF viewer and I am also able to download and share it with others

## File Specs
File resolution/quality: the highest quality version available for the preferred file delivered in the Viewer. For some collections, the Viewer delivers an Intermediate file instead of the Preservation Master File. For more information, see Curate ticket #411.

## Sample objects
https://curate.library.emory.edu/concern/curate_generic_works/3720cfxpr8-cor?locale=en
https://curate.library.emory.edu/concern/curate_generic_works/84302v6x0k-cor?locale=en

https://curate-arch.library.emory.edu/concern/curate_generic_works/030prr4xkj-cor?locale=en
https://curate-arch.library.emory.edu/concern/curate_generic_works/624jm63xv7-cor?locale=en

## Additional Information
[DCE’s Access Controls table
](https://docs.google.com/spreadsheets/d/1JGND3IjTK0kvqkKKX0Wi0dHxtcYRZD1QQM-BqJjfrBg/edit#gid=1226450121)
[Emory Ticket Notes
](https://docs.google.com/document/d/1Z68oz1PFWHBOPNRNJpyYKUi5MK8R87DYtP2oJzJYJTg/edit?usp=sharing)

**Comment by maxkadel** [comment]
I believe this is the current behavior, and I think this information is important to have, because we want to be sure to maintain this behavior as we go forward.

**Comment by maxkadel** [comment]
Note for implementation:

- When an object has visibility_ssi “open”, 
  - An unauthenticated user can 
    - View full quality files (i.e. IIIF requests are not rewritten)
    - Download - it has a download button that allows users to download full quality files 
    - Share - it has a share button
  - An authenticated user can also do the above

**Comment by maxkadel** [comment]
Test edit.
