### ISSUE TITLE
Restore sort options for advanced search

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#247]
Blacklight defaults for sort:
relevance
year
author
title

**Comment by wulman16** [comment]
![Screen Shot 2020-01-31 at 10.06.41 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/ef02d998-1b7f-409e-a897-7eb232e62e1e)

**Comment by nikdragovic** [comment]
@wulman16 Thanks for switching "author" to "creator." Can we change "year" to "date"?

**Comment by wulman16** [comment]
![Screen Shot 2020-01-31 at 10.52.07 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/5d8308fc-9c27-4991-b869-d16164ab07e4)

**Comment by wulman16** [comment]
All sort fields are ready to test in the digital-test environment
