### ISSUE TITLE
Build EC2 for digital and digital-test 

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/dlp-lux#26]
Build EC2s and deploy a ruby on rails server (like the curate box)
~it should use the solr instance from the env-equivalent from curate (solr-test to lux-test, solr-arch to lux-arch, etc)~, 
and can reach cantaloupe, and use shib auth
for digital-test.library.emory.edu

Added after the Solr meeting:
this environment should use a stand-alone, non-cloud solr index, using the solr config from curate.

**Comment by SolomonHD** [comment]
I've begun adjusting the variables for digital and digital test in cor-cm, should have those up by tonight.

**Comment by SolomonHD** [comment]
I've created EC2s for Digital, Digital-test and Digital-arch
Prod and Test have their own blacklight 7 schema and are working they're at:
https://digital.library.emory.edu/ and https://digital-test.library.emory.edu/

The plan with arch was to point it at curate-arch's solr schema, that's not working, see below:

Some interesting notes:
- Blacklight will only work if it's pointed at a collection or core named 'blacklight-core'
- For test and prod this was fine, I just created a new core with the correct name, for arch I had to create an alias named blacklight-core
- Even after creating this alias blacklight is rejecting the schema of curate-arch, the error message is below:

[LINK] (http://solr-cor-arch.library.emory.edu/solr/blacklight-core/select?wt=json&facet.field=format&facet.field=%7B%21ex%3Dpub_date_ssim_single%7Dpub_date_ssim&facet.field=subject_ssim&facet.field=language_ssim&facet.field=lc_1letter_ssim&facet.field=subject_geo_ssim&facet.field=subject_era_ssim&facet.query=pub_date_ssim%3A%5B2014+TO+*%5D&facet.query=pub_date_ssim%3A%5B2009+TO+*%5D&facet.query=pub_date_ssim%3A%5B1994+TO+*%5D&facet.pivot=format%2Clanguage_ssim&&&rows=10&facet=true&f.subject_ssim.facet.limit=21&f.language_ssim.facet.limit=11&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc)
