### ISSUE TITLE
Proxy requests to Cantaloupe

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#260]
In order to implement the requirement of access controls, we need to proxy requests for images to Cantaloupe, depending on whether or not a user is authenticated.

 - [x] Curate exposes a IIIF endpoint that proxies traffic to the Emory Cantaloupe server (i.e. no one goes directly to Cantaloupe; all IIIF traffic goes through a system that checks permissions).
 - [x] Initial implementation should not change existing behavior

**Comment by bess** [comment]
Action shots of iiif proxy working on curate-test:

![iiif_proxy_working.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/7bca4054-0af5-40ff-bc8c-816fde6aea23)

![proxy_logs.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/060475f4-b9f3-4cb9-9120-f955b99756bd)
