### ISSUE TITLE
Streamline values for "Access Group" facet

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#272]
The current form of this ticket assumes that all users (authenticated and not) will be able to search and discover records that are access-restricted, except Private objects.

- [x] "Access Group" should be renamed "Access."

- [x] "Public" category should include: 
  - [x] Public
  - [x] Public Low View 

- [ ] "Log In Required" should include:
  - [x] Emory High Download 
  - [x] Emory Low Download 
  - [ ] Rose High View 
  - [ ] Embargo (de-scoped)
  - [ ] Lease  (de-scoped)

- [x] The following should not appear:
  - [x] Private

**Comment by maxkadel** [comment]
Would it make sense to have a third grouping for something like "Reading Room Access"? Initially that could be for only "Rose High View" objects, then could be expanded for other reading rooms?

My understanding for Rose High View was that both logged in and not-logged-in users should be able to see those objects, if they were coming from the correct IP address?

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/74604789-3cdec800-508f-11ea-931b-dac783713ff7.png)

**Comment by maxkadel** [comment]
Per feedback, only showing parent access groups, not sub-groups 
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/3eaba428-2136-4845-be74-849842a37d77)
