### ISSUE TITLE
Allow two-page layout view option in Universal Viewer

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#276]

**Comment by tmiles2** [comment]
Testing...

**Comment by nikdragovic** [comment]
Closing this due to a persistent edit error that Tiffany and I could not figure out.![Screen Shot 2020-02-05 at 8.58.25 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/3d1eb624-765c-4fa6-95eb-2e0d7e9dfca9)
