### ISSUE TITLE
Customize search result sort options

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#277]
Sort by:
 - [x] Relevance
 - [x] Date (oldest)
 - [x] Date (newest)
 - [x] Creator (A-Z)
 - [x] Creator (Z-A)
 - [x] Title (A-Z)
 - [x] Title (Z-A)

 - [ ] Records with an unknown date should not appear at the beginning of a sort.

**Comment by wulman16** [comment]
@nikdragovic Our :year_for_lux field contains multiple values. For sorting by date, should we go by the latest year or the earliest year? Should that value be the same for both Date (oldest) and Date (newest) sorting?

**Comment by nikdragovic** [comment]
@wulman16 Good point. I think earliest for both Date (oldest) and Date (newest will give us the best result.

**Comment by nikdragovic** [comment]
@wulman16 Can we apply these changes to the advanced search sort as well?

**Comment by wulman16** [comment]
@nikdragovic Yes, after I configured the default sort options, it looks like advanced search sort automatically pulls from the settings for simple search sort.

**Comment by nikdragovic** [comment]
@wulman16 Sorting by Creator and Title look great! I'm a little confused by the ordering of sorts by Date when testing in digital-test.

**Comment by wulman16** [comment]
@nikdragovic @maxkadel I think we are just waiting on a deploy and re-index in Curate for date sorting to work as intended

**Comment by nikdragovic** [comment]
@wulman16 Right, thanks!

**Comment by nikdragovic** [comment]
![Screen Shot 2020-02-14 at 5.22.36 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/58ebda25-30cb-4a71-8456-71465fadaa04)

Note for me to test these objects after reindex to see if that might resolve the sort issues in the demo today.

**Comment by nikdragovic** [comment]
It looks like the collection objects above are still not sorting properly. Sort by date seems to behave mostly as expected; although I found the attached that, for some reason, does not. Might it make sense for me to close this issue and write a bug ticket instead? ![Screen Shot 2020-02-18 at 7.11.55 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4ea19302-84f5-4fe8-9173-c26b5c84961e)

**Comment by maxkadel** [comment]
I think making a bug ticket for the collection behavior would be helpful. It looks like it's not sorting the CurateGenericWork titles alongside the Collection titles, which sounds like the desired behavior?

When you notice something odd, like the screenshot above, would you share as much context as you can, so we can try to recreate the situation? What, exactly, you did to get to that state. 

So, for me:
Environment - digital-test.library.emory.edu
Actions - home page -> click search -> Sort by Creator (A-Z) -> Click page numbers linked at the bottom of the search results page to find "M" section, where I'd expect to find "Braddock's Spring", created by "Marken & Bielfeld" -> screenshot below
Final url - https://digital-test.library.emory.edu/?page=9&q=&search_field=common_fields&sort=creator_ssort+asc

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/f71fdc21-7080-4e49-91ec-b9b2b8158886)
