### ISSUE TITLE
Customize result views in search result list

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#280]
## Wireframe![Lux Beta Wireframes - Working Document - Update-Search-Browse-Results.jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/88abd5b4-46f6-410d-8de5-fbe4f71720e3)

Add "This item is part of: " link for to parent object for search result view of its children.

From #279:
Items display a parent relationship (possibly a static one). Emocad can serve as a use case - likely contains too many children for explicit/detailed display in search results. Possibly create a static, generic indicator that children exist. This could also apply to Collection object results.

## Notes
Do we need separate tickets for collection, parent, child, and non-hierarchical views?

**Comment by nikdragovic** [comment]
![Screen Shot 2020-02-05 at 10.11.33 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f4d938b9-2ce3-4971-ba68-94d79b290f3c)

Example from Science History Institute

**Comment by nikdragovic** [comment]
![image.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/d6bd00e0-381e-4c92-9a50-39204a0b3624)

Example from Science History Institute

**Comment by wulman16** [comment]
@nikdragovic Just to clarify, do you want to keep the **Library:** label for Collections as in the screenshot below, or do you want to display only the value as in the wireframe above?
![Screen Shot 2020-02-17 at 11.58.02 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/1e7914aa-62b3-4aa7-8e6e-370c6535ceb6)

**Comment by wulman16** [comment]
![Screen Shot 2020-02-18 at 9.54.10 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/b2c7cb70-92e3-46f6-b6de-57d6bef33ef9)![Screen Shot 2020-02-18 at 9.53.33 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/9efb0977-3adc-4506-a418-dd6227eecb85)![Screen Shot 2020-02-18 at 9.51.58 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/054e8cc1-37b0-4c24-b096-c19afbaf396d)![Screen Shot 2020-02-18 at 9.52.50 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d16c3e91-9fe9-4dc6-a8a2-a2ab74e160b0)
