### ISSUE TITLE
Download and Share Buttons Display

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#284]
For a logged in user, Download and Share buttons 
  - Do display for works with visibility:
    - [x] Public
    - [x] Emory High Download
    - [x] Emory Low Download
 - Do not display for works with visibility:
    - [x] Public low view
  - N/A (cannot open "show" page, dealt with on different ticket)
    - Rose High View
    - Private

For a non-logged in user, Download and Share buttons
  - Do display for works with visibility:
    - [x] Public
  - Do not display for works with visibility: 
    - [x] Public low view
  - N/A (cannot open "show" page, dealt with on different ticket)
    - Rose High View
    - Private
    - Emory High Download
    - Emory Low Download

**Comment by maxkadel** [comment]
Public - not logged in
![image](https://user-images.githubusercontent.com/45948126/74177647-2c020280-4c08-11ea-8e1c-8ebac95b6d98.png)

Public - logged in 
![image](https://user-images.githubusercontent.com/45948126/74177695-43d98680-4c08-11ea-885f-ea924d3b3e06.png)

Public Low View - not logged in
![image](https://user-images.githubusercontent.com/45948126/74178316-5a341200-4c09-11ea-95a4-28de74079149.png)

Public Low View - logged in
![image](https://user-images.githubusercontent.com/45948126/74178263-3e307080-4c09-11ea-9ea3-b19660d6d2b0.png)

Emory Low View - logged in
Can't find an example work that has working IIIF and

**Comment by nikdragovic** [comment]
We talked yesterday about how we might need to reconcile this ticket with tickets 300-307. I'll add that to the mid-sprint agenda.

**Comment by nikdragovic** [comment]
Accepted based on screenshots and quick testing; will need to perform additional testing with requisite content.
