### ISSUE TITLE
Suppress User Collections from appearing in Lux Collections facet

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#285]
Collection Type "User Collections" is currently displaying in digital-arch. Only type Library Collections should display (currently the five targeted launch collections). This behavior is implemented in Curate and should also be reflected in Lux.

![Screen Shot 2020-02-04 at 12.09.05 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/77a6763b-396f-479b-af7d-97c244d47cc1)

**Comment by maxkadel** [comment]
@eporter23  - which of these collections should the Lux user not see in the facets? My guess would be the "Parking Lot" and "QA Collection" collections, but they are of two different collection types, and the "Parking Lot" appears to be the same collection type as "Langmuir," etc.

Implementation note: Do the Library and User Collection Types have identifiers that persist across environments? Is there a way to know which is which from outside a given Curate instance?

**Comment by eporter23** [comment]
@maxkadel ideally, collections of the type "User Collection" (e.g. QA Collection in arch) would never be discoverable in Lux. Additionally collections of the type "Library Collection", if they are set to Private (e.g. Parking Lot in arch), should not be discoverable in Lux. I'm not sure if I can answer the implementation note question but I will poke around to see what may identify a particular Type for a collection.

**Comment by eporter23** [comment]
@maxkadel it looks like the solr docs for each collection across the 3 environments have gid://dlp-curate/hyrax-collectiontype/1 for Library Collection and gid://dlp-curate/hyrax-collectiontype/2 for User Collection

**Comment by nikdragovic** [comment]
Based on backlog grooming 4/13, we can't do email because AWS @ Emory has not approved the requisite email service. SMS is not a high-value feature.

**Comment by nikdragovic** [comment]
@eporter23 In digital-arch, I no longer see the collections from the ticket description, although there are various "test" collections now. Are those Library Collections tied to recent Curate experiments rather than User Collections?

I don't see any undesired collections in test or prod, so I think this is good to close?

**Comment by eporter23** [comment]
@nikdragovic the QA Collection in arch is a User Collection, which we don't want to expose in Lux. So, that work still needs to be done. We can work around this in the meantime, however, so it may not be a priority for beta.

**Comment by nikdragovic** [comment]
This is what I see in digital-arch currently.[Uploading... Screen Shot 2020-04-14 at 9.54.57 AM.png ]

**Comment by nikdragovic** [comment]
@eporter23 This is what I see in digital-arch currently.

![Screen Shot 2020-04-14 at 9.54.57 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e00aab23-ee4d-47e6-a301-d4f13e6dcf68)

**Comment by eporter23** [comment]
@nikdragovic your screenshot shows the Library facet; here is what I see for Collections in digital-arch: 
<img width="1031" alt="Screen Shot 2020-04-14 at 11 54 58 AM" src="https://user-images.githubusercontent.com/13855987/79245997-e7345b00-7e46-11ea-9c74-e880e7df7a9d.png">

**Comment by eporter23** [comment]
In the above, the QA Collection is a "User Collection" which we don't want to be discoverable in Lux.

**Comment by nikdragovic** [comment]
@eporter23 Wow, thanks! I was definitely not paying attention there.

**Comment by maxkadel** [comment]
https://docs.google.com/document/d/1xL7qKrhNkeItJji2XqNzSYxpB4DewNpDFdj8FN8PvyI/edit#

**Comment by eporter23** [comment]
As a followup to the discussion of the Decision Document posted above, I have disabled creation of User Collections by non-Admin users in arch, test, and prod, and we will train Admin users to make sure they do not create new User Collections.
