### ISSUE TITLE
Run Lighthouse 

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#288]
## Acceptance Criteria
- [x] Run Lighthouse on Home Page
- [x] Run Lighthouse on Advanced Search Page
- [x] Run Lighthouse on one static page (e.g., About)
- [x] Run Lighthouse on search results page 
- [x] Run Lighthouse on Collection Show Page 
- [x] Run Lighthouse on Simple Object Show Page
- [x] Determine next steps for accessibility remediation

**Comment by mark-dce** [comment]
Here's a document that describes the way DCE used lighthouse for UCLA - In particular see Appendix A - Step-by-step Test Procedure for how we ran lighthouse
https://drive.google.com/drive/folders/1LcxB_M5n7O_4bD-zP1fVVXrv6xQFJzKV

**Comment by maxkadel** [comment]
Documentation and data in Emory's box - https://app.box.com/folder/111177124322
