### ISSUE TITLE
Add Max to AWS@E

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#29]
Add as an admin,

**Comment by tmiles2** [comment]
@rotated8 I've requested Max's sponsor account, he received his credentials this morning but it may take 24 hrs for them to be updated in the system.

**Comment by tmiles2** [comment]
Collin has add @maxkadel to AWS@emory.  Mark P. has put in a request for VPN access. (REQ88355 - VPN: Additional Core Access)
