### ISSUE TITLE
Custom 404 page should display styles when path is invalid

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#292]
- Entering a bad URL (digital.library.emory.edu/123) leads to the custom 404 page, but without CSS and major UI elements.

## Acceptance Criteria
- [ ] Header, footer, and styling should appear when the custom 404 page is reached.

![Screen Shot 2020-04-13 at 8.40.01 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/64ebb0d0-f156-43f6-b248-62227362fc73)

**Comment by maxkadel** [comment]
So, I did a little poking on this, and it looks like this page displays correctly for a logged in user, but not a logged out user, is that what you found? And for a logged out user they should get the default 404 page, is that correct? If so, could we change the ticket to something like:

An unauthenticated user gets to a 404 page when going directly to "digital.library.emory.edu/bookmarks"

**Comment by nikdragovic** [comment]
Maybe this is better left for backlog grooming or some other discussion. However, on the Blacklight demo, unauthenticated users can bookmark records and view / share them in a session via the Bookmarks link. I think this is a nice feature. However, I wrote this ticket more because I wanted to make sure I understood cases in which an error page might be presented that is not the 404.

**Comment by nikdragovic** [comment]
Honeybadger is set up for Lux, but may need to be troubleshooted.

**Comment by nikdragovic** [comment]
Break into tickets for 404/403 versus 500 (server) errors.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-15 at 10.25.15 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d13a8407-ef19-4c5b-9729-6f1008ebbd30)

**Comment by bwatson78** [comment]
PR for the changes above: https://github.com/emory-libraries/dlp-lux/pull/498
