### ISSUE TITLE
Public Low View page load

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#295]
Acceptance Criteria 
- [x] An unauthenticated user can see the page when the Public Low View visibility badge is selected in Curate

**Comment by maxkadel** [comment]
Tested with https://curate-arch.library.emory.edu/concern/curate_generic_works/6214mw6mbk-cor?locale=en and https://digital-arch.library.emory.edu/catalog/6214mw6mbk-cor
