### ISSUE TITLE
Emory High Download page load

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#296]
Acceptance Criteria 
- [x] An unauthenticated user reaches the 404 page when the Emory High Download visibility badge is selected in Curate
- [x] An authenticated user reaches the show page when the Emory High Download visibility badge is selected in Curate

**Comment by maxkadel** [comment]
Tested with https://curate-arch.library.emory.edu/concern/curate_generic_works/740ksn02z0-cor?locale=en and https://digital-arch.library.emory.edu/catalog/740ksn02z0-cor
