### ISSUE TITLE
Emory Low Download page load

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#297]
Acceptance Criteria 
- [x] An unauthenticated user reaches the 404 page when the Emory Low Download visibility badge is selected in Curate
- [x] An authenticated user reaches the show page when the Emory Low Download visibility badge is selected in Curate

**Comment by maxkadel** [comment]
Tested using https://curate-arch.library.emory.edu/concern/curate_generic_works/392g79cnqp-cor?locale=en and https://digital-arch.library.emory.edu/catalog/392g79cnqp-cor
