### ISSUE TITLE
Rose High View page load

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#298]
Acceptance Criteria 
- [x] An unauthenticated user outside the specified IP range reaches the 404 page when the Rose High View visibility badge is selected in Curate
- [x] An authenticated user outside the specified IP range reaches the 404 page when the Rose High View visibility badge is selected in Curate
- [x] An authenticated or unauthenticated user with the specified IP reaches the show page when the Rose High View visibility badge is selected in Curate

**Comment by maxkadel** [comment]
Logged out, from the "right" IP
![image](https://user-images.githubusercontent.com/45948126/74293985-86838780-4d0a-11ea-96a3-4391d50da1ae.png)

Logged in, from the "right" IP
![image](https://user-images.githubusercontent.com/45948126/74294001-9733fd80-4d0a-11ea-88d1-b220bd14ced3.png)

Logged out, from the "wrong" IP
![image](https://user-images.githubusercontent.com/45948126/74293903-39071a80-4d0a-11ea-83dd-2c210b3294fb.png)

Logged in, from the "wrong" IP
![image](https://user-images.githubusercontent.com/45948126/74293936-56d47f80-4d0a-11ea-935c-b5c4af4ea029.png)

**Comment by maxkadel** [comment]
Solomon has asked that the the Environment variable for the IPs be a pointer to a file, rather than the IPs being stored in the environment variable itself.

**Comment by eporter23** [comment]
@maxkadel @nikdragovic using my static IP (which I'll double-check to see if it's been added), I'm unable to see the Work page and get directed to the 404, so this appears to be failing for me. We still need to do additional testing in the Rose Reading room on-site, but wanted to note this as an FYI.

**Comment by maxkadel** [comment]
New ticket - #360 - to add IPs to servers & Ansible scripts. I had misunderstood a conversation with Solomon to mean they were already on the servers, but just the sample file was.

**Comment by tmiles2** [comment]
The Emory load balancer changes the IP client address to the F5 address.

**Comment by tmiles2** [comment]
Final work: Implement the current solution on test on prod and arch.

**Comment by tmiles2** [comment]
@eporter23 Solomon has deploy the Rose High View page load solution on prod and arch can you test this?

**Comment by tmiles2** [comment]
@eporter23 please test

**Comment by eporter23** [comment]
I've tested this on my local machine using a permitted IP address and it works as desired. We have not yet been able to test the IPs in the actual reading room due to additional laptop re-configurations being required. I recommend we close this now, and Emory can do additional testing later on the actual machines.
