### ISSUE TITLE
Private page load

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#299]
Acceptance Criteria
- [x] All users reach a 404 page when attempting to go to a page when the Private visibility badge is selected in Curate

**Comment by maxkadel** [comment]
Tested using https://curate-arch.library.emory.edu/concern/curate_generic_works/361rfj6q71-cor?locale=en and https://digital-arch.library.emory.edu/catalog/361rfj6q71-cor
