### ISSUE TITLE
Support display of parent/child relationships via breadcrumbs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#3]
## Story
As a Collection Manager, I want to display parent/child relationships for nested objects via breadcrumbs or other links, so that end users can see the object structure and its collection relationship.

*Ticket updated to reflect generic text in breadcrumbs to replace most specific page names.*

~Possible Pattern: Home > Collection > Work > Volume > Page~

~Can we create shorthand for collections and truncate work names? Some of these are very long. ~

## Acceptance Criteria
- [ ] All elements of breadcrumbs are clickable
- [ ] All work pages and collection pages have breadcrumbs
- [ ] Static/misc pages (About, Help, Bookmarks) have breadcrumbs
- [ ] First three words of the last breadcrumb item display, followed by an ellipsis, with full text appearing on hover
- [ ] Generic phrasing for breadcrumb items that are not last in sequence:
   - [ ] Home   
   - [ ] Back to Collection
   - [ ] Back to Parent Object
- [ ] Use pattern [breadcrumbs](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=molecules-breadcrumbs) from pattern library

## Examples 
https://digital-test.library.emory.edu/catalog/689d51c5br-cor

~Home > Emory University Yearbooks > Memory > Memory [1946] > Page 23 (de-scoped) ~
Home > Back to Collection > Back to Parent Object > Memory [1946]

https://digital-test.library.emory.edu/catalog/2150gb5mkr-cor

Home > Emory University Yearbooks

https://digital-test.library.emory.edu/catalog/866vx0k6g6-cor

Home > Back to Collection > First African Baptist...

~Home > Robert Langmuir African American Photograph Collection > First African Baptist Church, Revival Chorus of the, Under the direction of Prof. E. Clifford Davis, Nationally known choir director and song writer of Chicago, Illinois, Madame Mary Johnson Davis, soloist, Rev. W.A. Harrod, DD, Pastor, 16th and Christian Streets, Philadelphia, Pennsylvania, March 19-April 2, 1939~

## Wireframe
![Lux Beta Wireframes - Working Document - Breadcrumbs (1).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/32491f91-ef73-4ca2-a8c1-dca1ecbd7e4b)

**Comment by tmiles2** [comment]
Note: Curate team suggests truncating display + hover text. Curate ticket: https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1055

**Comment by bwatson78** [comment]
PR created: https://github.com/emory-libraries/dlp-lux/pull/474

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-01 at 2.06.52 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c82b4aaa-f0d5-4d2f-b153-f38fedb11d69)

**Comment by bwatson78** [comment]
Resuming work on this ticket per request from @nikdragovic. Will be styling the breadcrumbs to the pattern library standards.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-03 at 9.10.42 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/81c5ce4c-9206-45be-970b-de19f6a52453)

**Comment by bwatson78** [comment]
Will be pushing the code shown above soon.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-07 at 9.58.03 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e81d0816-73df-424a-886f-c5f031dfc250)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-07 at 9.58.57 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/73dfc17d-7a79-40de-a55b-31cc5a456018)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-07 at 9.59.44 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/81f2cf13-c267-4ae8-a73e-74e9bf4501db)

**Comment by bwatson78** [comment]
PR ready for re-review: https://github.com/emory-libraries/dlp-lux/pull/477

**Comment by lovinscari** [comment]
Breadcrumbs working as expected.
