### ISSUE TITLE
Display representative media on collection show page in Blacklight app, not Universal Viewer

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#310]
Curate related ticket [1016](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1016)
![Lux Beta Wireframes - Working Document - Yearbooks (1).jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b7d8812c-455b-42f5-82d4-7daf733dc064)

**Comment by nikdragovic** [comment]
As discussed, "collection thumbnail" is just a placeholder for any suitable media. With only 4-5 collections to worry about for the time being, it is totally feasible to handle this in a manual way.

**Comment by maxkadel** [comment]
FYI, this work will encompass some fixes and testing for other hierarchical objects, so may need to be revised up. Working on a PR now which fixes the thumbnail image issue shown below

From digital-arch, broken
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6876edb9-0bb4-41d2-b6cd-b1c0e4306c7f)

Local environment, fixed
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9c4527b6-3b2d-4660-8baa-d7c817b00e50)

**Comment by maxkadel** [comment]
I've removed the UV from the collection page, but currently Curate is not successfully saving other representative media for Collections, moving to blocked. 
![image](https://user-images.githubusercontent.com/45948126/74948723-b39afe80-53ca-11ea-8c56-3ed2ad074e4b.png)


Error message when trying to add logo to Collection
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/a2755d2f-6c6c-48d5-8b0b-cafecf8dfb46)

**Comment by tmiles2** [comment]
@wulman16 @bwatson78 The Curate team has completed their work for this ticket. Feel free to reach out to Devanshu or Emily if you have questions about work on the Curate side.

**Comment by bwatson78** [comment]
Pull request made in `dlp-curate`to provide index each collection needs for this issue: https://github.com/emory-libraries/dlp-curate/pull/1109 .

**Comment by bwatson78** [comment]
Above has been merged. New PR created for the lux side: https://github.com/emory-libraries/dlp-lux/pull/445.

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-26 at 8.52.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3bbe0067-b951-4553-bb41-9aceb51194a0)
