### ISSUE TITLE
Public Low View IIIF configuration

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#313]
## Acceptance Criteria
 - [x] Files in viewer should be configured to display at reduced quality. See [Curate 985](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/985) for additional detail.
 
If I go to this image:
https://curate.library.emory.edu/iiif/2/d28c5b20cf9b9663181d02b5ce90fac59fa666d7/full/600,/0/default.jpg

It should give me the same response as if I go to this image:
https://curate.library.emory.edu/iiif/2/d28c5b20cf9b9663181d02b5ce90fac59fa666d7/full/,400/0/default.jpg

**Comment by tmiles2** [comment]
Waiting on #996 in Curate

**Comment by bess** [comment]
This is currently blocked because lux needs to get the IIIF manifest from curate, but curate is redirecting to shibboleth when the manifest is requested and this is throwing the display off. 

See below for a screen shot of UV failing to load an image because the manifest isn't being returned:

![manifest_still_not_loading.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/426b7f7c-c0ad-421f-8e77-d67efb1473e4)

**Comment by eporter23** [comment]
@bess @rotated8 I wanted to confirm if additional work was needed in the Curate-generated manifest to constrain the low-resolution dimensions, or if info about our image dimensions needs to be updated in the Lux board? We have a ticket in [Curate - 985](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/985) that specifies the maximum height of a low-res image should be constrained to 400px, based on reviewing different approaches with Bess recently.

**Comment by bess** [comment]
Update: Manifests are now loading, but the image resolution doesn't seem quite right yet.

**Comment by bess** [comment]
I haven't had much time to work on this. It is 90% working, but Emily's feedback was that the image is still too high resolution, so we're going to scale that down, and if that still doesn't work we'll have to go to watermarking.

**Comment by eporter23** [comment]
@bess just a followup, I think what we talked about last week was that the desired output for low res would sized to this: https://curate-test.library.emory.edu/iiif/2/586f96be080fbf73d08cabf2161bb3237a987316/full/,400/0/default.jpg but we saw that the "full" URL pattern was still much larger (and we want them to be the same): https://curate-test.library.emory.edu/iiif/2/586f96be080fbf73d08cabf2161bb3237a987316/full/full/0/default.jpg

**Comment by bess** [comment]
Before on left, after on right, subject's eye. After image is more pixelated / has less information

![pixelated_eye.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/779e6eb8-0fc4-47b3-ba6b-8813a1fc260e)

**Comment by tmiles2** [comment]
@eporter23 Please test

**Comment by nikdragovic** [comment]
@eporter23  are closing out the development portion of this, but will follow up with a ticket to finalize documentation about what comprises "low resolution" as implemented.
