### ISSUE TITLE
Emory Low Download IIIF configuration

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#315]
## Acceptance Criteria
 - [x] Files in viewer should be configured to display at reduced quality.
 - [x] Only visible to authenticated Emory users

**Comment by fnibbit** [comment]
Full size image requested
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/31135f7f-ae4f-41f6-b5f7-bcb961a71d75)

result limited to 400 pixels
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/7b1d9127-a69d-4a3e-901c-2f8bdc377542)

**Comment by fnibbit** [comment]
Not authenticated to lux: cannot load image.

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/b2afc37d-9323-400b-99f5-35169e110df4)

**Comment by nikdragovic** [comment]
One last question about this category. When zooming in on an [object](https://digital-test.library.emory.edu/catalog/177fqz612s-cor) in the Universal Viewer, the text on the color bar looks fairly clear. When downloading the image and reviewing the exposed curate image tab, it looks much more pixelated. Is this expected behavior? I reviewed the demo and documentation but not sure I'm 100% clear on this. I had to resize these screenshots in order to upload but hopefully they are illustrative or can help reproduce.

![Screen Shot 2020-03-23 at 12.38.17 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/dbe4096c-7c8d-4870-8f10-245bcd755bc7)
![Screen Shot 2020-03-23 at 12.39.08 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/98b22e4b-3ae7-42c4-bee5-2b2185ab2d1b)

**Comment by nikdragovic** [comment]
@bess @fnibbit @maxkadel Just wanted to check and see if anyone has had a chance to check into the comment above? I believe this relates to the Zoom behavior notes I highlighted on pages 1 and 2 of the [document](https://docs.google.com/document/d/1e9XKxjw7klpncvVVYrA9RQzfDVrNmBAaIrb462WXb3Y/edit?usp=sharing).

**Comment by bess** [comment]
@nikdragovic Would you please take another look now that that system has been re-indexed? Here is a screen shot of that same area this morning, which looks more like what we'd expect. If you still think the images are too high resolution for "low res" we can adjust the settings as mentioned in this document: https://docs.google.com/document/d/112JvZfHYIijmX7V_FPeIJudao1n5K2XfMnoJbsr2Q6Q/edit

![Screen Shot 2020-03-25 at 10.19.30 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/a0a7bc33-cc60-41cc-9e08-c209c52e4c23)
