### ISSUE TITLE
Rose High View IIIF configuration

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#317]
## Acceptance Criteria
 - [x] Files in viewer should be configured to display at full quality.
 - [x] Visible only to users coming from one of the Rose reading room's IP addresses
 - [x] Use X-Forwarded-For header to identify user IP address

**Comment by maxkadel** [comment]
We asked Solomon to add my VPN'd IP to the configuration file for testing purposes. Bess tested in her office across town at the same time, see next comment.

When in the "Rose Reading Room" (aka my office), I was able to see the image:
In Lux whether or not I was logged in - https://digital-test.library.emory.edu/catalog/4881jwsts9-cor
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/0c86b84f-8554-4fda-9731-590c76b6ce5e)

In Curate, only when logged in as an admin - https://curate-test.library.emory.edu/concern/curate_generic_works/4881jwsts9-cor?locale=en
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/455be62b-a59d-4114-b09b-16fde067c4da)

And in an incognito window as a IIIF url - https://curate-test.library.emory.edu/iiif/2/90b2e0779bdfd5f865c507d22ffaea82eaadca80/full/64,/0/default.jpg
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/0e7912ce-9f3f-4f4b-b890-b2c70e3cde80)

**Comment by bess** [comment]
From an IP NOT in the list of Rose reading room IPs:

1) I can still see the image as expected if I am logged into curate as an admin:

![Screen Shot 2020-03-24 at 9.32.39 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/475c4541-fd70-4ff3-a01c-ec879d927e65)

2) I can NOT see the image if I am unauthenticated and I go directly to an image url

![Screen Shot 2020-03-24 at 9.37.50 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/d7055a09-7a15-414e-937e-e655ab280ac5)

**Comment by nikdragovic** [comment]
@fnibbit @maxkadel One question about Reading Room use cases - do you happen to know if one login is permitted to access the application on multiple computers? 

The scenario here would be that a guest user (with no Emory login) comes to the Reading Room. The Rose staff has a generic Shib login that they would use to permit the guest access to Log In Required material. Wondering if this would pose a challenge with two visitors in the reading room at one time, attempting to use the same login. Would we need Rose to verify that they have enough logins to provide unique credentials to all simultaneous guests?

**Comment by maxkadel** [comment]
@nikdragovic  - If they are in the Rose Reading Room, they will have access to Rose High View visibility works whether or not they are logged in via Shibboleth.

If they are a guest in the Rose Reading Room and want to see Emory High Download and Emory Low Download materials, and staff give them a generic Shibboleth login to do so, I believe they could use the same login on multiple computers, but that is dependent on Emory's Shibboleth setup, not this particular application.

**Comment by nikdragovic** [comment]
@maxkadel Thanks for clarifying!
