### ISSUE TITLE
Display generic thumbnails for Emory Log In Required objects in search results

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#323]
## Story
As an end user, I want to view a thumbnail image that helps describe the access level for restricted items in my search results, so I can determine whether or not I can view the show page by logging in or going to a reading room.

## Acceptance
Display a temporary a thumbnail stating Log In Required. Show to all non-logged in users for the appropriate objects.

Refinement of work moved to #395.

**Comment by mark-dce** [comment]
The placeholder images are added in PR #412 

I saved a PSD with the original artwork on google drive: https://drive.google.com/file/d/1rqowdcOSSaZTGFtexZa092ODUscBWfU3/view?usp=sharing

**Comment by maxkadel** [comment]
Not logged in 
![image](https://user-images.githubusercontent.com/45948126/77648836-286bd600-6f3f-11ea-8d12-a4aa214d0482.png)

Logged in
![image](https://user-images.githubusercontent.com/45948126/77648870-37528880-6f3f-11ea-8d36-d49d97840d07.png)
