### ISSUE TITLE
Add links from show pages to faceted browse / search results for specified fields

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#330]
As an end user, I want to click a link from a show page field entry such as "Subjects - Topic," so that I have a simple way to browse items scoped to my interests. 

Page types to include are all show pages (for collections and works).

Fields to link:
- [x] Creator
- [x] Contributor
- [x] Format
- [x] Genre
- [x] Language
- [x] Subject - Topics
- [x] Subject - Names
- [x] Subject - Geographic Locations
- [ ] Subject - Time Periods
- [ ] Keywords
- [x] Library
- [ ] Administrative Unit
- [ ] Sublocation
- [ ] Related Material (would link to work show page)
- [ ] Related Publications (would link to work show page)
- [ ] Related Datasets (would link to work show page)

**Comment by maxkadel** [comment]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5d63001e-2b3a-4b1c-8cd4-19f6a296278a)

Need to be saved facetable in Curate:
 - Subject - Time Periods
 - Keywords
 - Administrative Unit
 - Sublocation

Requires more work to link to individual show pages
 - Related material
 - Related publications
 - Related datasets
