### ISSUE TITLE
Verify that expected download and embed options appear in Universal Viewer for appropriate objects

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#331]
Work occurring in Curate [984](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/984), [986](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/986),(completed) [987](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/987) (completed)

## Wireframe
![Lux Beta Wireframes - Working Document - Download (1).jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e2177ac2-2d6d-4e19-a5dc-c1483472ac46)

**Comment by nikdragovic** [comment]
Per a call with @devanshu-m, it sounds like the dimensions for the embed feature refer to the iframe and not the image/content within. He does not currently see a way to alter the predefined options. Given that it will not affect the content and a custom option is supplied, this may be a nonissue.

**Comment by nikdragovic** [comment]
Confirmed today that we are fine with default options or whatever option can be managed with a feasible amount of work, not necessarily in accordance with what was originally drafted in wireframes above.

**Comment by eporter23** [comment]
@nikdragovic @lovinscari @tmiles2 for the download sizes offered for Emory Low Download, the Curate team has proposed that we only show a single "Whole Image" option which is constrained to the low-resolution size (400px high). See [Curate ticket 1054.](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1054)

**Comment by eporter23** [comment]
@tmiles2 @lovinscari @nikdragovic just a clarification that Curate 986 work is complete, but we need to make sure that the manifest generation and caching process continues to provide the additional downloadable files as expected.

**Comment by tmiles2** [comment]
Devanshu and Zo are wrapping this up. Devanshu will need to submit a PR to the Lux team because some of the changes occur on the UV Configuration in Lux (not a Curate code change)
-  For Emory Low Download, we will provide a single size download only called "Whole Image" that only permits the 400 px high image
-  For other scenarios we are trying to fix the "Current View" functionality and make sure the medium size download does not distort the aspect ratio.

**Comment by nikdragovic** [comment]
Per standup today, I tested in arch. 

Note that the user will have to wait for the item to load for the download options to populate, otherwise the popup will instead say "No download options available."

@rotated8 @eporter23 I am still seeing distortion for the midsize image download option for this object: 

https://digital-arch.library.emory.edu/catalog/825x69p8gd-cor

This relates to the comment directly above this one, so just let me know if there's still work pending for me to test this, or if anything needs to move into a new ticket. 

I'm not seeing PDF options for yearbooks or yellowbacks.

**Comment by eporter23** [comment]
@nikdragovic my understanding is that the aspect ratio fix hasn't been deployed yet.

**Comment by nikdragovic** [comment]
@eporter23 Thanks for clarifying! I'll wait for an update on when this is ready to test, and try doing it in the test environment instead.
