### ISSUE TITLE
Style the header

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#341]
- [x] It looks like the attached screenshot, and It uses official Emory 
  - [x] Fonts
  - [x] Colors
  - [x] Logos
  - [x] CSS
- [x] At different sizes, the header continues to look attractive, especially the logo and utility navigation (break points)
- [x] At mobile size, utility navigation links on top left and right should gather into hamburger menu (similar but not identical to [website](https://libraries.emory.edu/))
- [x] At mobile size, searchbox should stack below logo and hamburger menu 
- [x] Maximum width for application still under discussion
   - [x] Model the header after the max width on the footer (currently 1235px)
- [x] The logo (shield + Emory University + Emory Libraries) should be configured to link to libraries.emory.edu
- [x] The branding header links are styled correctly on hover

See http://emilyporter.net/emory/blacklight-headerA-4.html
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=all

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/4b996004-9d6d-461c-98fc-b8dedc2c0756)

**Comment by nikdragovic** [comment]
Sorry, I forgot to add that the logo should link to libraries.emory.edu, will do that now.

**Comment by maxkadel** [comment]
As of Wednesday noon
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/58fa7de7-bb9c-4593-933d-f004c15eaa12)

**Comment by nikdragovic** [comment]
@maxkadel and I discussed making the utility links across the top consistent in style. Advanced Search, Bookmarks, etc. will use the same style as "Home."

**Comment by maxkadel** [comment]
As of March 2, 2020
Desktop view
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5e116b7c-4c9a-43a9-83c7-d38f58e84200)

Mobile view
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/4851f929-824b-439e-a4ec-15a3f8bcab7f)

**Comment by maxkadel** [comment]
I suspect there will be changes requested, but I'm ready for some feedback on things to change and priorities.

**Comment by nikdragovic** [comment]
Thanks, @maxkadel. I believe @eporter23 may also have feedback soon. This is moving along great. A few things:

1) We talked last week about creating consistent fonts across the top header. I should have been more specific; the desired treatment is shown for "Home" in the mockup:
http://emilyporter.net/emory/blacklight-headerA-4.html

The Libraries website header is another example. I'm attaching screenshots from the pattern library that shows it as all-caps, with the appropriate fonts and padding.![Screen Shot 2020-03-03 at 2.18.23 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/090f1fa7-2497-4ce3-a1f4-4989ce4ead2f)![Screen Shot 2020-03-03 at 2.18.46 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/74e98323-3a86-4816-a8e8-cce26f763e85)

2) Would it be possible to include the whole phrase "Common Fields" in the targeted field dropdown? Let me know if this poses a challenge for mobile view.

3) We have a dropdown style in Figma (shown below) that would be desirable for the targeted fields. I do not believe it has been translated to the pattern library. Is it possible to implement?
![Screen Shot 2020-03-03 at 2.23.05 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/8e62f439-7921-4132-ba65-7f702a7fcdc7)

These are in current order of priority; please let me know if you have any questions.

**Comment by maxkadel** [comment]
#1 - not deployed yet. 
 ![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/d245517b-a963-4a23-b3f0-79ec0cfa90e7)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/45152b32-0da3-408b-8eb1-81a3745766e3)

**Comment by maxkadel** [comment]
Here is some documentation about my concern about using all-caps for the site navigation and accessibility - https://w3c.github.io/low-vision-a11y-tf/requirements.html#capitalization

**Comment by eporter23** [comment]
@maxkadel @nikdragovic feedback for the header and footer (desktop breakpoint only). A lot of this is very detailed, related to sizing and positioning adjustments. I wrote this up in a pseudo css way so that it is not implementation specific. Let me know if I can clarify any of this. https://docs.google.com/document/d/1XLsPxzExwyKAx8moGanwttLbkni9GSk3jdYmOU8DF8U/edit#heading=h.fysr59ug0db

**Comment by nikdragovic** [comment]
@maxkadel Thanks for the additional info! Emily and I have discussed and she included some info in the doc about how this can be managed for screen readers (search her doc for "Text-transform/Case: UPPERCASE")

Regarding low-vision users and the documentation you linked to, I suspect it might be targeted at text of greater length. "3.3.4 Capitalization" references "blocks" of text, which is defined above in "3.3.3 Style." We can discuss further, I just want to make sure I can justify any deviations from the pattern library and existing design convention if we decide to keep sentence case.

**Comment by maxkadel** [comment]
As of 3/9/2020
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6fbde563-3bef-4aff-8c4f-fec5fa7910cb)

**Comment by wulman16** [comment]
![Screen Shot 2020-03-20 at 1.57.51 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/7c9d19d0-1e75-4f0c-bae6-6906ead27389)

**Comment by wulman16** [comment]
Header at large width:


![Screen Shot 2020-03-23 at 1.57.09 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/b59fc912-3ce8-4048-9efe-a50557599827)


Header at medium width:


![Screen Shot 2020-03-23 at 1.57.20 PM.png]
(https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/e5ab20c0-cd39-42cd-b5fb-9413b03d2a0b)

Header at small width:


![Screen Shot 2020-03-23 at 1.57.27 PM.png]
(https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d0893777-0c36-4825-87e8-85ca4301f208)

**Comment by wulman16** [comment]
![Screen Shot 2020-03-24 at 1.54.23 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/024d8e03-9b79-4347-aca8-e9dcc290aff2)

**Comment by wulman16** [comment]
@eporter23 @nikdragovic 

I think I was able to address everything in the linked document except the following:

1a. I set the max-width for the header at 1235px, but I'm now seeing the comment in the document saying we might want this at 1110px instead. If that's the case, it will be a simple fix.

6bi + 8ci. I was not able to get the distance between the utility nav bottom border and the top of the Emory University text to be 18px in a maintainable way. I assumed it was a higher priority to have the search form vertically aligned with the Emory University and Emory Libraries branding on the left (8ciii).

8cii. Given the max-width of the header overall, the minimum width needed to display the text in the fielded search dropdown, and the desired proportions between the three elements in the search form, it wasn't feasible to have a minimum 180px between the search form and the branding elements. Depending on the size of the window, the gap ranges between 52px and 153px currently.

**Comment by eporter23** [comment]
@wulman16 looks fabulous! I'm fine with how it is now, will confer with @nikdragovic about the max width.

**Comment by nikdragovic** [comment]
@wulman16 Thanks for your detailed comments! This looks great. 

I'd like to try the 1110px width if it's not too hard. Open to hearing whether you think this will shore up the alignment with the object title and metadata groupings on the typical desktop view. I think even just a screenshot of a local environment should suffice to tell?![Screen Shot 2020-03-26 at 10.25.20 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4e8e69b9-b527-4ef6-bcaf-e94decfd9bc8)

**Comment by wulman16** [comment]
**Updated header width:**

![77691736-d1d0bd00-6f7b-11ea-878e-3756a3ece7f5.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/0d0cdec8-8443-498c-9267-afe6f4b9a558)
