### ISSUE TITLE
Style Footer

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#342]
- [x] It looks like the attached screenshot, and uses official Emory pattern library
- [x] It also has the version footer information currently in Lux (above copyright line)
- [x] Full width vs. body width footer still under discussion 

* http://template.library.emory.edu/styleguide/patternlibrary/current/?p=all
* http://emilyporter.net/emory/blacklight-headerA-4.html

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/38ad3a64-9833-46a0-9e35-08ce078c742c)

**Comment by nikdragovic** [comment]
Footer links:

About Digital Collections | Copyright and Reuse | Contact | Donate

**Comment by wulman16** [comment]
![Screen Shot 2020-02-26 at 10.32.18 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/aaca2982-4ff6-4222-b69d-446ac5c1b826)

**Comment by wulman16** [comment]
![Screen Shot 2020-02-28 at 11.58.16 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/bc17d46b-d74e-48a5-8517-9552be13a7d1)

**Comment by nikdragovic** [comment]
@tmiles2 helpfully reported the following unexpected behavior on a set of rather large screens. I have been unable to replicate it on a 13" device:

![Unknown-1.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/36166e63-8d37-40a2-9fa0-8fd2d45f4fc6)
 
On my monitor: Dell UltrasSharp 34” curved
Digital-arch – footer looks fine on Chrome, Firefox
Digital -test – footer looks fine on Firefox
On Chrome – If you preview the site full screen there’s a white strip under the footer

On a 35” screen:
Both digital arch and digitial test the footer has a white strip below the footer on Safari, Chrome and Firefox.

**Comment by eporter23** [comment]
@wulman16 @nikdragovic - feedback for the footer element (see the end of the doc). This is mostly fine tuning some details. Written as pseudo CSS so it is not implementation specific. Let me know if I can clarify any of this:  https://docs.google.com/document/d/1XLsPxzExwyKAx8moGanwttLbkni9GSk3jdYmOU8DF8U/edit#heading=h.fysr59ug0db

**Comment by wulman16** [comment]
@eporter23 Thanks for the detailed feedback. I think 13 and 14 are related—the CSS for the dividers between links is there, but the dividers I'm noticing are often showing up on the left edge of the page for some reason. Will need some more fine-tuning.

**Comment by wulman16** [comment]
![Screen Shot 2020-03-16 at 1.41.44 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/bcc408f0-eda6-4d29-a063-220918fcf3ee)

![Screen Shot 2020-03-16 at 1.42.54 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/99322e4a-e28d-4657-88e4-9e5934ee4b63)

**Comment by lovinscari** [comment]
Both Emily and Cari have reviewed. The footer is accepted with the understanding a slight modification is still needed to the height of the footer. This will be addressed with a new issue once links to the static pages are known and the footer can be updated.
