### ISSUE TITLE
Style the hero image for the front page

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#343]
- [ ] Rotate through multiple images
- [ ] Add title with official Emory assets from pattern library
- [ ] It should display on the front page only, as indicated in the mockup 
- [ ] A caption for each image should state "View Featured Item" with hyperlink to the show page - [Example](https://ursus.library.ucla.edu/)

* http://template.library.emory.edu/styleguide/patternlibrary/current/?p=all
* http://emilyporter.net/emory/blacklight-headerA-4.html

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/8c73f175-e05e-4a92-86a4-2b39e9037a3d)

**Comment by tmiles2** [comment]
@maxkadel @nikdragovic here are some sample images to start with in case you need them sooner. https://emory.app.box.com/folder/104330269851

**Comment by wulman16** [comment]
![Screen Shot 2020-03-05 at 1.57.44 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d3fc801d-ddd2-43df-9aec-4e15a0588b25)

**Comment by eporter23** [comment]
@wulman16 for generating the link to the Work Show page, would it help if we named the hero images with the work id as the filename?

**Comment by wulman16** [comment]
@eporter23 Yes that would be helpful, thanks

**Comment by wulman16** [comment]
![Screen Shot 2020-03-06 at 1.58.00 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/13190cd2-0df9-412d-819b-3a9fe8a42b00)

**Comment by nikdragovic** [comment]
@wulman16 I made a small change to the fourth checkbox to hopefully simplify things - generic text for linking instead of the work title.

**Comment by wulman16** [comment]
@nikdragovic Perfect, thanks

**Comment by eporter23** [comment]
@wulman16 I added the production IDs to the filenames for the hero image samples, but I realize those won't work in test. So let me know if we should do something different in the short term. Also, I'm starting to get all the final images in from the collection managers, so let me know if/when we should touch base on that later.

**Comment by wulman16** [comment]
@eporter23 I can have the captions link to the homepage in the meantime. Once we have all the objects available, we can change the links. As for the images, it would be great if they were all roughly the same dimensions (the one sample image with slightly funky behavior right now is "Group of Atkinson College Students" because it is a bit short and wide). It would also be good if they had decent contrast with the white text throughout, though we could potentially put a filter on the images if necessary.

**Comment by eporter23** [comment]
@wulman16 agreed on the image sizes - I wasn't sure if the old vs. new CSS would be scaling or positioning these images. Based on the intro-hero pattern, I will size the images to a fixed height (440px?) and then we can figure out what the width should be.

**Comment by wulman16** [comment]
![Screen Shot 2020-03-12 at 12.25.59 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/58a8abbc-609c-439e-b80c-9905cdee85f0)

**Comment by lovinscari** [comment]
Accepted with a note to Emily to crop the hero images.

**Comment by eporter23** [comment]
@wulman16 @lovinscari @nikdragovic we may need a new ticket for this, but I have added/will continue adding cropped and resized hero images for the beta launch to this folder in box: https://emory.app.box.com/folder/106881613222
