### ISSUE TITLE
Implement "Explore Our Collections" section of home page

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#345]
- [x] It looks like the attached screenshot, and uses official Emory pattern library
- [x] "Explore Our Collections" text uses Emory Blue #082B73 and Open Sans font
- [x] It includes 3 collections, with appropriate styling:
  - [x] Langmuir
  - [x] Asian Artifacts
  - [x] Medical Artifacts
- [x] For Beta release, hard code, may in future be pulled from Curate.

* http://template.library.emory.edu/styleguide/patternlibrary/current/?p=all
* http://emilyporter.net/emory/blacklight-headerA-4.html
* [Design System Document](https://drive.google.com/open?id=1MpIKYe6YpeS8qpPNqNohKRklloFF2_2m)
* [Bootstrap Mapping](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)
* [Content](https://docs.google.com/document/d/1f2zhc87x_ViS_giII3c7M48ReaBjh499gnM5wK6vdKk/edit?usp=sharing)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5f37f6c5-cede-4985-8a76-fda25d3af8aa)

**Comment by nikdragovic** [comment]
@wulman16 Here's the updated content for this section; I also added the link in the ticket description: https://docs.google.com/document/d/1f2zhc87x_ViS_giII3c7M48ReaBjh499gnM5wK6vdKk/edit?usp=sharing

**Comment by wulman16** [comment]
![Screen Shot 2020-04-07 at 1.55.41 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/a3813e74-148c-468f-b342-e489469098d8)

**Comment by wulman16** [comment]
![Screen Shot 2020-04-08 at 1.52.00 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/4aa44d79-4220-44d8-a426-ae764f296109)

**Comment by wulman16** [comment]
![Screen Shot 2020-04-09 at 10.10.56 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/09c669e8-c8bb-4014-9a46-eeacf28925a0)

**Comment by wulman16** [comment]
![Screen Shot 2020-04-09 at 12.32.09 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d876d510-9438-4355-85e4-f959ca52b3f2)

**Comment by nikdragovic** [comment]
@wulman16 Here are the links to these collections:

Langmuir:
https://digital.library.emory.edu/catalog/914nk98sfv-cor

Oxford: 
https://digital.library.emory.edu/catalog/320sqv9s4v-cor

Health Sciences:
https://digital.library.emory.edu/catalog/5053ffbg7n-cor
