### ISSUE TITLE
Determine 2 more footer links

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#346]
Even numbers of columns look better in the footer, come up with 2 more links for footer.

**Comment by tmiles2** [comment]
@nikdragovic Can you confirm what the two links are and what they are pointing to?

**Comment by nikdragovic** [comment]
@tmiles2 @eporter23 I propose that the links are as follows, left to right:

About Digital Collections | Copyright and Reuse | Contact | Donate

We can lightly edit the wording as needed, but this seems to be in accord with what we have discussed to this point.

Yesterday, we settled on creating dead/placeholder links in the header for the pages that don't exist yet. I recommend we do the same for the footer until I settle on architecture of the static pages in the next few days (whether internal or external).
