### ISSUE TITLE
Change wording of "Reading Room Specific" access group to "Reading Room Only"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#350]

**Comment by nikdragovic** [comment]
Note that a reindex will be required for this work to be visible in the application.

**Comment by wulman16** [comment]
![Screen Shot 2020-02-20 at 2.27.59 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/5ce4f4a2-f7d6-4138-ae78-adea46685292)
