### ISSUE TITLE
Link Keyword field from show pages

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#351]
As an end user, I want to click a link from the "Keyword" field, so that I have a simple way to browse items scoped to my interests.

**Comment by wulman16** [comment]
![Screen Shot 2020-02-20 at 3.52.54 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/c12a976c-a8d1-4946-a918-f68dcd6e11a9)

**Comment by tmiles2** [comment]
@nikdragovic screenshot provided
