### ISSUE TITLE
Create "About Digital Collections" Page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#352]
## Acceptance Criteria
- [x] Uses universal application header and footer.
- [x] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [x] Path is digital.library.emory.edu/about
- [x] Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html
- [x] Legend for specific styles located at https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing

## Wireframe
[https://app.zenhub.com/files/172767026/4b082182-7ca9-463a-b250-0d55d626a895/download](https://app.zenhub.com/files/172767026/4b082182-7ca9-463a-b250-0d55d626a895/download)
- [ ] [Template](https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing) 
- [ ]  [Working content](https://docs.google.com/document/d/1ZQE6brthA0nq-Ya0ogL054TEMjhEJnuCBrpopFntNK8/edit?usp=sharing)

**Comment by bwatson78** [comment]
Created pull request for this issue: https://github.com/emory-libraries/dlp-lux/pull/413

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-18 at 1.14.54 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3f8376dd-757f-4f57-958e-ee9ba9e6472e)

**Comment by bwatson78** [comment]
To-do for another issue (styling):

- [ ] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [ ]  Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html
- [ ]  Legend for specific styles located at https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing

**Comment by nikdragovic** [comment]
Moving remaining work into update ticket.
