### ISSUE TITLE
Create "Contact" page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#353]
Acceptance Criteria
- [x] Uses universal application header and footer.
- [x] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [x] Path is digital.library.emory.edu/contact
- [x] Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html
- [x] Legend for specific styles located at https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing

## Wireframe
[https://app.zenhub.com/files/172767026/02bf08a9-355f-4863-ac02-60e9c209b965/download](https://app.zenhub.com/files/172767026/02bf08a9-355f-4863-ac02-60e9c209b965/download)
- [ ] [Template](https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing) 
- [ ]  [Working content](https://docs.google.com/document/d/1LvGlw1qC9me9ZMp_RZtuBa1_BL7Y4Pp2wGdOgO-caoA/edit?usp=sharing)

**Comment by bwatson78** [comment]
Pull request has been created: https://github.com/emory-libraries/dlp-lux/pull/413

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-18 at 1.10.06 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/67107a7a-80ee-4637-a101-3052fef39a18)

**Comment by bwatson78** [comment]
To-do for another issue (styling):

- [ ] Uses body text and heading styles from pattern library / library website.
- [ ]  Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html
- [ ]  Legend for specific styles located at https://docs.google.com/document/d/1d8MGgO8Mv92KF3fIUXuUaRFxfvMm1EtDoigahrMJK6U/edit?usp=sharing

**Comment by nikdragovic** [comment]
Moving remaining work into update ticket.
