### ISSUE TITLE
Access facet does not appear in digital-arch

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#354]
Reindex of arch on 2/18 does not appear to have resolved this. 
Based on curate-arch, it appears that works in digital-arch have this field assigned.

**Comment by wulman16** [comment]
The Access facet now uses the `visibility_group_ssi` field instead of `visibility_ssi`. There is a re-index still running in curate-arch that should introduce that field to those Solr documents.

**Comment by nikdragovic** [comment]
@wulman16 Thanks; I didn't realize it was still running, or that it would have to complete before showing this result. I'll wait for that to happen and then close this out.
