### ISSUE TITLE
Change value of iiif_url on digital servers

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#356]
There is an environment variable called `IIIF_MANIFEST_URL` in the `.env.production` files on all of the digital-*.library.emory.edu servers and it needs to change.

The new value is `SERVER_NAME/iiif/`

@SolomonHD Please let me know if this is enough info. 

Once this is done, this UV should start working: https://digital-test.library.emory.edu/catalog/508hdr7srq-cor

**Comment by SolomonHD** [comment]
Change has been completed.
