### ISSUE TITLE
Confirm that the settings for the Emory F5 load-balancer provides the "X-Forwarded for" header

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#362]

**Comment by tmiles2** [comment]
@SolomonHD or @mprefer Here's the ticket we discussed during standup. Please make edits to outline the work you will do if this is incorrect.

**Comment by maxkadel** [comment]
The x-type headers right now, going to digital-test.library.emory.edu through F5
```
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 6.0.4
X-Request-Id: 74e01489-6d98-4e39-bc38-1921ad14e283
X-Runtime: 0.067835
X-XSS-Protection: 1; mode=block
```

**Comment by SolomonHD** [comment]
After testing out the reading room IPs, the team has come to realize that we will not have access to user client IP. This is due to being behind multiple load balancers. We need to enable the X-Forward-For option in the F5 to get the client IP address.

**Comment by SolomonHD** [comment]
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/53679851-8603-48a1-ac28-227b5a1813ab)

I altered an existing profile in called HTTP_Xfwd_for_100MB to insert the header. Also I switched to that header in our dlp VIP.

**Comment by SolomonHD** [comment]
Confirmed that the setting is working and that Client IP is being forwarded. Note that if you're on F5 VPN Client, you're given a temporary "tunnel IP" that will be shown instead of your true IP when accessing emory websites.
