### ISSUE TITLE
ADR for how we get a client's IP address

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#364]
Create an Architecture Decision Record that
- [x] explains the issue with the current configuration
- [x] outlines the proposed solution, with details about how wide of an effect the change will have
- [x] briefly describes alternatives considered, even if they wouldn't work.
- [x] follows the [ADR template](https://github.com/emory-libraries/dlp-lux/blob/master/architecture-decisions/0000-TEMPLATE.md)

**Comment by SolomonHD** [comment]
There's a PR for this @rotated8
