### ISSUE TITLE
Style the search results page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#368]
## Acceptance Criteria
- [x] Uses universal application header and footer.
- [ ] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
  - QUESTION: What should the hover behavior for the link be? Currently underline.
- [ ] When the user selects facets the results are displayed next to header "Search Term" with results of facet. 
- [ ] When the user selects search criteria, the number of results from search are displayed next to header "number of results"
- [x] The user is able to select the number of results to be displayed in increments of 10, 20, 30, 50 using the default display if previously configured.
- [ ] The user is able to sort the results of the search according to previous configurations for sort results.
- [ ] The results of the sort appear directly beneath the pagination and next to the facets
- [ ] Themes using Emory branding (text, headers, colors, spacing) should be used where possible
- [x] Text above the facets should read "Limit your search" (default text) as opposed to customized homepage text (Browse all items).

* [Bootstrap Mapping](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)

## Wireframe
Use this design for beta.
![Lux Beta Wireframes - Working Document - Search-Page.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b447d155-50c8-4627-9e17-971531a87506)

**Comment by tmiles2** [comment]
Note: In the wireframe we have descoped list view and gallery view.

**Comment by maxkadel** [comment]
Started on https://github.com/emory-libraries/dlp-lux/tree/theme_search_page , feel free to pick up or start from master, whichever is easier.

**Comment by bwatson78** [comment]
PR ready for review: https://github.com/emory-libraries/dlp-lux/pull/485

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-10 at 2.55.08 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/594b1e71-b8d9-4e3f-98fc-bd9f3d872804)

**Comment by nikdragovic** [comment]
@bwatson78 This looks great. The only thing that looks a little odd is the alignment of the Bookmarks checkbox for each item. I remember us discussing the alignment on a call but forgot the details.

**Comment by nikdragovic** [comment]
@bwatson78 I think I see. When we reviewed the layouts, it was for collections and nested objects that have additional text on that line. For simple objects, without additional text on that line, the Bookmarks checkbox is getting pushed leftward. See correct alignment below.![Screen Shot 2020-04-14 at 4.44.55 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/ffe25c50-c5b9-4ae5-9806-1c04aee040cc)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-15 at 8.49.18 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5feaff9f-91aa-449a-99cf-c8a340d9f807)

This behavior (bookmark not floating to the right) is happening on test sites due to the fact that the left column is only populated when a parent, child, or associated works are present. I have inserted a blank element to correct the issue.
