### ISSUE TITLE
Style the collection page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#369]
## Acceptance Criteria
- [x] Uses universal application header and footer.
- [x] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [x] Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html
- [x] When a user selects a collection from facet or featured collections on home page, the user is taken to the corresponding collection page
- [x] layout is similar to that found at https://digital.library.ucla.edu/catalog/8zn49200zz-89112

* [Bootstrap Mapping](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)

## Wireframes
- Updated wireframe:
 ![Lux Beta Wireframes - Working Document - Yearbooks (3).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/8940014c-2a8e-4ca9-a395-e68fb6295406)
- Previous version, has been superseded:
[https://app.zenhub.com/files/172767026/3fb4c125-80fc-472c-bb33-13a1b633024c/download](https://app.zenhub.com/files/172767026/3fb4c125-80fc-472c-bb33-13a1b633024c/download)

**Comment by bwatson78** [comment]
[Uploading... Screen Shot 2020-04-07 at 2.40.33 PM.png ]

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-07 at 2.40.33 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/90b84190-37e2-4652-9161-139d595dc57d)

**Comment by bwatson78** [comment]
PR created: https://github.com/emory-libraries/dlp-lux/pull/479/
