### ISSUE TITLE
Style the work (single item) page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#370]
## Question
- Do we need separate issues for parent, child, and simple objects?

## Acceptance Criteria
- [x] Uses universal application header and footer.
- [ ] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [ ] Colors and styles similar to that found at https://libraries.emory.edu/contact/index.html

* [Bootstrap Mapping](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)

## Wireframes
![Lux Beta Wireframes - Working Document - View Parent Object - Update.jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/44e4bc82-97ae-4858-beb2-8c13c8869568)

**Comment by wulman16** [comment]
@nikdragovic I think having one issue for parent, child, and simple objects is fine. If there are changes that need to be made specifically to one of those pages that isn't covered in the spreadsheet, I would add them to this issue.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-03 at 8.28.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/cc6b17dd-a4ea-4cab-bfa5-47caaf0ce082)

**Comment by bwatson78** [comment]
@nikdragovic Three elements were identified as needing styling:

- The buttons below the nav bar: they now mirror the search button in the nav bar. I kept the "Back To Search" button the same color scheme, but later found that could be inherited from Blacklight's default. If you'd rather have that button look the same as "Search" and Start Over", please let me know and I'll adjust that.
- The `h1` ("Mondo Jaws" in this instance) now directly mirror all aspects of EUL's pattern library. Your request for font size has also been adjusted.
- The middle metadata columns now display titles and values side-by-side. They stop doing that once the screen size goes smaller than 768, the break point that all of the columns reduce to one column.

Please let me know if you see any other elements for me to work on.

**Comment by bwatson78** [comment]
Code has been refactored with requested changes made by @wulman16: https://github.com/emory-libraries/dlp-lux/pull/476

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-06 at 2.49.24 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/64fc563d-1f44-4a8f-8dc8-d048a6aa020f)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-06 at 2.47.45 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a620053d-b1db-40a5-9da8-e33a0644c29c)

**Comment by lovinscari** [comment]
I am accepting this issue after reviewing with Emily but there are a few cosmetic changes that will be needed post-beta that was referenced on the styling spreadsheet created by Emily.
