### ISSUE TITLE
Style the advanced search page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#371]
Layout does not need to change.

## Acceptance Criteria
- [ ] Colors and fonts should be consistent with History page.

**Comment by wulman16** [comment]
![Screen Shot 2020-04-13 at 1.43.10 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/bb56d933-0ff8-47b3-b8a2-82214d7d1d89)

**Comment by wulman16** [comment]
![Screen Shot 2020-04-13 at 1.44.41 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/894bc156-e3b2-4851-86d8-fdf4243f8917)

**Comment by wulman16** [comment]
![Screen Shot 2020-04-13 at 1.43.10 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/501e80c5-56e4-4c36-bd69-9d36e81ce6f6)

**Comment by wulman16** [comment]
**Top of advanced search page:**
![Screen Shot 2020-04-14 at 4.25.21 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/4970ddcc-570c-4fb2-82ca-fe2031919c17)


**Bottom of advanced search page:**
![Screen Shot 2020-04-14 at 4.25.35 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d97b4517-fe32-49e0-80cc-21ac7dfe0814)
