### ISSUE TITLE
Style the bookmarks page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#372]
## Acceptance
- [ ] For bookmark items, use the styling from general search result items

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/502

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-16 at 9.28.43 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a2715021-dc25-4d2d-a601-ebbf3258577f)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-16 at 9.29.20 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d509141b-8c7d-4a63-9735-a1ef3e205ea6)
