### ISSUE TITLE
Restore default alignment for facets 

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#375]
## Acceptance
- [ ] Facets and search results should be adjacent, as shown in wireframe and [Blacklight demo](http://demo.projectblacklight.org/?utf8=%E2%9C%93&search_field=all_fields&q=).
- [ ] Add back sidebar

## Wireframe
![Lux Beta Wireframes - Working Document - Search-Page.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/cc747770-fb17-42cc-9f24-076adb2bc992)

**Comment by wulman16** [comment]
**3/30 update**: The facets are in the right place on the page, but I'm still figuring out how to get the facets to show by default without having to click the toggler.
![Screen Shot 2020-03-30 at 1.53.59 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/f9b150c8-3734-4e74-859c-0c6d3a32d29e)

**Comment by wulman16** [comment]
**Large width:**![Screen Shot 2020-03-30 at 9.01.58 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/2f2c4046-eaa8-4d8e-aad4-f6db0f504358)

**Medium width:**![Screen Shot 2020-03-30 at 9.02.12 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/bb7da98a-69e4-4098-a458-5c44cc7635c4)

**Comment by nikdragovic** [comment]
@wulman16 Thanks, looks great. Later on, we may want to try lining up the hamburger buttons for the nav and facets in mobile view.
