### ISSUE TITLE
Index Short names for Collections to Solr in Curate

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#378]
For the breadcrumbs, we want a short version of Collection names in Lux. 

The short names should be:

- Emory University Yearbook Collection
  - [ ] [?]
- Victorian Yellowbacks and Paperbacks Collection
  - [ ] [?]
- Medical Artifact Collection
  - [ ] [?]
- Asian Artifacts Collection
  - [ ] [?]
- Langmuir African American Photograph Collection
  - [ ] [?]

**Comment by maxkadel** [comment]
@nikdragovic  - would you put the short names you'd like in this ticket?

**Comment by tmiles2** [comment]
Note: Curate team suggests truncating display + hover text. Is this an acceptable solution?

**Comment by nikdragovic** [comment]
We're going to use a different solution for this issue, as documented in #3.
