### ISSUE TITLE
Test apply "Table" style to metadata groupings on show page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#381]
Timeboxed ticket to examine level of effort and possible result of incorporating additional branding.

[Table style](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=atoms-table) (also available in [Figma](https://www.figma.com/file/B7WWVWaPZOsvffwAbDXMf1cb/Emory-System?node-id=0%3A213))

![Screen Shot 2020-02-27 at 9.41.07 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/166b1084-2027-4962-98b4-995243b958c6)
![Screen Shot 2020-02-27 at 9.40.39 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4634c4e9-55e3-4dea-9f2d-dc2e4c4b10f7)

- [x] Heading should use prescribed fonts and colors, possibly at a larger font size
- [x] Field labels should use "subheading" style
- [x] Metadata values should use "data" style
- [x] Linked text remains "accessible blue"

**Comment by maxkadel** [comment]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5226cd2e-2b23-4b24-a82a-bed93a7ca6d6)

**Comment by tmiles2** [comment]
We will address the front styling changes in another ticket
