### ISSUE TITLE
Add Rachel K to AWS at Emory 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#386]
NetID is: RKADEL2
- [x] Add RK as an admin 
- [x] Request VPN access

**Comment by SolomonHD** [comment]
I've added Rachel K to the aws@emory account as an auditor.

**Comment by fnibbit** [comment]
Maybe relevant? https://emory.service-now.com/sp?id=kb_article&sys_id=38c21d84a4749d4098b6e4ec3c25b36c NOTE: All new VPN users must have Basic VPN access before requesting elevated VPN Access. The user requiring this access must contact the University Service Desk at 404.727.7777 to be vetted/registered to use VPN. For sponsored accounts, the sponsor must call first on behalf of the person and get an EPIN number. The person with the sponsored account then calls the Service and supplies that EPIN number to verify their identity.

**Comment by fnibbit** [comment]
I have basic VPN access now; the knowlegebase says "NOTE: Only supervisors and/or local support personnel are permitted to request elevated access." so I think the ticket for aws@emory core access needs to be created by someone else than me.

**Comment by mprefer** [comment]
Request for aws@emory VPN access entered, request number: REQ94640

**Comment by mprefer** [comment]
Blocked waiting for fulfillment.

**Comment by mprefer** [comment]
Request completed.

Request Item: RITM00106186 - VPN: Additional Core Access
Opened: 2020-03-03 03:44 PM EST
Update:
2020-03-03 05:40 PM EST - Marvin Head (Public notes (emailed to the user))
Rachel Kadel has been added to AWSALLOW_Core

**Comment by fnibbit** [comment]
Works great!
