### ISSUE TITLE
Relevancy Customization Cross-Training

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/dlp-lux#389]
I lieu of specific development for relevancy customization and the challenges presented (limited collections migrated to test against, limited ability to test to get abnormal relevancy results, etc.) we would like to explore a plan for Emory Libraries Development Team to receive training from DCE developers on some of the work they have completed around relevancy customization for other customers. This ticket could be considered a SPIKE ticket for estimation purposes if we need to time-box the work to be done or we can simply detail what is involved with what is needed for training and knowledge transfer and then estimate the issue.

Once the plans for this work is determined we can decide if an Epic with multiple issues is needed or if this is simply one issue.

**Comment by nikdragovic** [comment]
Quick note - it would be good to address any variance in how search operators work in simple versus advanced search, and any additional considerations we want to make or testing we want to do when testing those changes.

I am seeing some differences in searches I currently think should be close to identical. "african" in common fields from the homepage returns a work first. Running a search for "african" in all fields from advanced search, and sorting by relevance returns the Langmuir collection object first.

**Comment by RachelDCE** [comment]
The teach-out is scheduled for April 8 at 3:15 and will be recorded.

**Comment by fnibbit** [comment]
Slide deck from the teach-out -- should be viewable by team members. https://docs.google.com/presentation/d/1NKR-o6Hvx1fraIAlxQVbSJE0xwBtCTh4BtJxdp0ipy8
