### ISSUE TITLE
Search does not work on Bookmarks, History, and Works pages

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#390]
When searching "Common Fields" on digital-arch and digital-test (both v0.6.19) for "emocad," the application does not appear to react. Similar searches work from the homepage on arch and test, as well as on all pages in prod (v0.6.15). This may have something to do with ongoing work for the header?

** Update March 5 **

With recently deployed header work in prod, this appears to be the case in all environments.

**Comment by bwatson78** [comment]
Pull request ready for review: https://github.com/emory-libraries/dlp-lux/pull/426
