### ISSUE TITLE
Generic thumbnail for Reading Room Only

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#394]
## Story
As an end user, I want to view a thumbnail image that helps describe the access level for restricted items in my search results, so I can determine whether or not I can view the show page by logging in or going to a reading room.

## Acceptance
Display a temporary thumbnail stating Reading Room Only. Show to all users outside the Reading Room allowable IP addresses.

Refinement of work moved to #395.

**Comment by nikdragovic** [comment]
@maxkadel Do you know if the temporary thumbnail for this issue has been created yet?

**Comment by mark-dce** [comment]
@nikdragovic - yes it's already here:
https://github.com/emory-libraries/dlp-lux/blob/master/app/assets/images/reading-room-only.png

**Comment by maxkadel** [comment]
From outside the reading room
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5a383a88-32c1-4985-a80f-206aa5fce234)

(don't currently have access to "inside the reading room")
