### ISSUE TITLE
Substitute refined thumbnails for restricted items

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#395]
## Story
As an end user, I want to view a thumbnail image that helps describe the access level for restricted items in my search results, so I can determine whether or not I can view the show page by logging in or going to a reading room.

Create two thumbnails - one stating Log In Required, one stating Reading Room Only. Use each thumbnail for the respective access group implied.

## Thumbnails
![readingroom.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/1fbf7e01-540f-42e2-8aab-cffa604689c4)

![loginrequired.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b51bd039-4968-4061-b873-582951a90373)

**Comment by mark-dce** [comment]
I created placholder images in PR #412 
I saved the original artwork as a Photoshop doc on Google Drive: https://drive.google.com/file/d/1rqowdcOSSaZTGFtexZa092ODUscBWfU3/view?usp=sharing

![image](https://user-images.githubusercontent.com/3064318/76803111-194e9080-67a7-11ea-97f7-989b3c341d85.png)  
![image](https://user-images.githubusercontent.com/3064318/76803180-32574180-67a7-11ea-9138-55d85ebf6dcb.png)

**Comment by bwatson78** [comment]
PR made: 
https://github.com/emory-libraries/dlp-lux/pull/457

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-30 at 12.52.51 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6bc59028-84d2-488b-82ff-3e802b019a5e)
