### ISSUE TITLE
Behavior of search result navigator on show pages

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#396]
While testing the application, there was some unexpected behavior with regard to show pages for collections and works. The part of the page that helps navigate thorough search results: 

![Screen Shot 2020-03-05 at 11.10.47 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/71184bc4-75a2-4444-baa4-11a4683ed1a9)

shows up in unexpected contexts. For example, in test, searching for "african" turns up 106 results, the second of which is the Langmuir Collection.

Clicking on the [Langmuir Collection object](https://digital-test.library.emory.edu/catalog/699n2z34v3-cor) leads to the show page for the collection. "2 of 106" displays below "Start Over" and "Back to Search," as would be expected.

However, following the object link (https://digital-test.library.emory.edu/catalog/699n2z34v3-cor) from a new window also shows "2 of 106," which shouldn't be linked to any search since the object was reached via direct link. Any other direct object link will also display this. However, if an incognito window is used to reach this URL, it does not display "2 of 106."

I just want to clarify, if possible, the behavior of Blacklight searches in browser sessions. Searches appear to be  carried throughout the session until a new search is initiated.

**Comment by bwatson78** [comment]
Yes, out-of-the-box, Blacklight uses a pagination widget that retains all search history info during the session.
