### ISSUE TITLE
Research HTTP Basic Auth in front of DLP applications

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-lux#398]
There will be a short window after the F5 VIP is opened to the public where will we not want the application fully available to the general public. One possible solution is to put HTTP Basic Auth in front of the entire website.

- [ ] Research different methods for Basic Auth in front of DLP's websites.

**Comment by bess** [comment]
Here is the PR from when we set this up on the ETD application: 

https://github.com/curationexperts/laevigata/commit/a1fbcc244d636fef7c0a811dce5d1b6253b15e8c#diff-c479d64f9a244ea0d8f75ee8d59951f7

**Comment by tmiles2** [comment]
We will use that solution that the ETD app is using
