### ISSUE TITLE
Link child works to parent works

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#399]
## Acceptance
- [ ] For child objects of nested works, "This item is part of" displays a link to its parent object below the link to its collection.

## Wireframe
![Lux Beta Wireframes - Working Document - View Child Object.jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/802b9d7f-8774-4192-b34a-7888fe7e7270)

## Example
This relationship is currently visible on the work page in [Curate](https://curate-arch.library.emory.edu/concern/curate_generic_works/0859cnp5kv-cor?locale=en).

**Comment by bwatson78** [comment]
Created PR for this work: https://github.com/emory-libraries/dlp-lux/pull/453

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-27 at 8.57.53 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7ceb433c-4700-40e0-909b-d33b3c19ebbd)

**Comment by bwatson78** [comment]
New PR for revisions: https://github.com/emory-libraries/dlp-lux/pull/454

**Comment by nikdragovic** [comment]
Closing based on this object in test, arch and prod need to be reindexed: https://digital-test.library.emory.edu/catalog/303qv9s4n4-cor
