### ISSUE TITLE
Document access controls

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#401]
## Acceptance
- [x] All necessary system components and behaviors (IIIF, UV, etc.) are documented for the display of each access group.
- [x] Known constraints and risks are documented.
- [ ] Emory and DCE check documentation for completeness and accuracy.

[Initial document/outline started here](https://docs.google.com/document/d/1e9XKxjw7klpncvVVYrA9RQzfDVrNmBAaIrb462WXb3Y/edit?usp=sharing)

Additional source material: Original Emory Langmuir guidelines, Github ticket notes
[DCE’s Access Controls table
](https://docs.google.com/spreadsheets/d/1JGND3IjTK0kvqkKKX0Wi0dHxtcYRZD1QQM-BqJjfrBg/edit#gid=1226450121)[Emory Ticket Notes
](https://docs.google.com/document/d/1Z68oz1PFWHBOPNRNJpyYKUi5MK8R87DYtP2oJzJYJTg/edit?usp=sharing)

**Comment by nikdragovic** [comment]
@eporter23 Very generic requirements, please let me know if you want more specificity.

**Comment by bess** [comment]
Document started here: https://docs.google.com/document/d/112JvZfHYIijmX7V_FPeIJudao1n5K2XfMnoJbsr2Q6Q/edit?ts=5e73db6a

**Comment by nikdragovic** [comment]
@eporter23 I have added you to this ticket so that we can review / accept.

**Comment by eporter23** [comment]
@bess @maxkadel @fnibbit your doc is very helpful. can you all please review the document I drafted [linked in the ticket description above](https://docs.google.com/document/d/1e9XKxjw7klpncvVVYrA9RQzfDVrNmBAaIrb462WXb3Y/edit?usp=sharing) and add any comments? Thanks @maxkadel for your notes.
