### ISSUE TITLE
Default thumbnails displaying in search/browse results 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#404]
I frequently see placeholder/default thumbnail icons in Curate test and production, whether on or off campus, authenticated or not, in a variety of different browsers. This seems to be primarily occurring on Langmuir items. The items should have thumbnails generated in their equivalent Curate environment.

To reproduce in test or prod:

1. Start a new search/session
2. Select either the Medical Artifacts or Asian Artifacts collection from the Collection facet: thumbnails are displayed.
3. Clear the Collection facet/limit and then select Langmuir: placeholder/default thumbnail icons appear for all items

**Lux - Production**
![Screen Shot 2020-03-11 at 11.47.29 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/83c83107-54d9-4e74-a2ff-20c08d4d0e05)

**Curate - Production**
![Screen Shot 2020-03-11 at 11.47.51 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/759c2eb8-8b04-4631-8a98-fad9f72582a6)

**Comment by bwatson78** [comment]
![Screen Shot 2020-03-26 at 8.52.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0e1d7420-6dd8-4676-aad2-59bcca6b7d31)

**Comment by eporter23** [comment]
@nikdragovic I'm not seeing this in digital-test anymore, so it may be safe to close. We did a fileset cleanup and a reindex of curate-test. I suspect when we reindex production it will also help.

**Comment by nikdragovic** [comment]
@eporter sounds good.
