### ISSUE TITLE
Compile list of Emory pattern library components that should move into Bootstrap framework

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#406]
There are many styling/theming pieces that Lux uses that we would prefer followed Emory's Pattern Library so they look like the library website. However, in the interest of time, we should start by identifying the highest priority components.

## Acceptance
- [ ] Generate a list of ~10 components Lux will use most often, or are otherwise highly impactful for Lux's design.
- [ ] Link those components to similar Pattern Library items (Link to multiple items if this is ambiguous)

**Comment by tmiles2** [comment]
Bootstrap Mapping: https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit#gid=0

**Comment by tmiles2** [comment]
Developers will style page by page based on the bootstrap mapping document. Comments will be provide  as needed.
