### ISSUE TITLE
Add environment variables for cookie encryption

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#417]
Lux needs to be able to encrypt a string, pass it to curate, and have curate de-crypt the string in order to enforce access restrictions. This is going to require that Lux and Curate both have access to the same encryption salt values.

Please set two environment variables: `IIIF_COOKIE_SALT_1` and `IIIF_COOKIE_SALT_2` in the `.env.production` file of all Lux instances and all Curate instances. Lux and Curate pairs in the same environment (e.g., -arch, -test, -prod) need the SAME VALUES otherwise the decryption won't work.

The salt values can be a randomly generated string. Something like `SecureRandom.hex` or anything that generates a long random string is fine.

**Comment by SolomonHD** [comment]
The variables have been added to the environments manually and also added to the ansible scripts via ansible vault.

Please test and let me know if everything is working as expected.
