### ISSUE TITLE
Make Curate and Lux Public 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#420]
High Level Process

1. Create a diagram or picture 
1. Lux should be behind basic HTTP Auth
1. Curate should require login before showing search results
1. Lux is available from the public internet

**Comment by mark-dce** [comment]
https://www.lucidchart.com/documents/view/a352cc7c-2573-4c90-93cc-ee27eeee7cd4/0_0

<img width="931" alt="image" src="https://user-images.githubusercontent.com/3064318/77120864-d9d2af00-6a07-11ea-83c9-008621d205f2.png">

**Comment by mark-dce** [comment]
Flow for image requests
1. User searches and finds a work in Lux
1. User clicks on the item link and Lux loads the single item view in the users page
1. Lux instructs the users browser to run Universal Viewer and tells universal viewer (the user's browser) which manifest to use
1. Universal Viewer running in the user's browser requests the manifest from curate (i.e. the client browser, not Lux is sending requests to curate)
1. Curate responds to the client browser with the manifest
1. UV parses the manifest and requests the first image and thumbnails for other pages from Curate (the iiif proxy endpoint)
1. Curate responds with the requested images to the client browser
1. Universal viewer renders the images for the user
