### ISSUE TITLE
Require Login for all Curate access (except ./iiif endpoint)

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-lux#428]
**STORY**
In order to prevent public internet access to curate, we need to require any user to login before searching or doing other work.

**DETAILS**
We need to do this before making the network changes to make Curate accessible to the public internet.  We think we can do this with a simple change to the routes or controllers, if not, we should do this in two steps using basic HTTP auth first and then adding devise/can-can restrictions later.

**ACCEPTANCE**
- [x] Users have to log in for any search or management access to curate
- [x] Anyone can make requests to the ./iiif endpoint without authentication - e.g. Lux users should be able to request public-access manifests without logging in to either system - https://curate.library.emory.edu/iiif//269m37pvtw-cor/manifest

**Comment by nikdragovic** [comment]
Tested by a user without a Curate login. As desired, Shib login does not provide access to Curate.

![image (2).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/8b02d740-0769-4e5e-9221-369b39a7bed9)
![image (1).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/95862914-2cff-426a-af1c-42307dc54a8c)
