### ISSUE TITLE
Allow Lux and Curate to be accessed from the public internet

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-lux#429]
**STORY**
In order to allow scholars from across the world (and the local coffeehouse) to access Emory's digital holdings, we need to make Lux discoverable and accessible on the public internet.  As a side effect, we also need to expose Curate so folks can interact with images via curate's IIIF proxying endpoint.

**DETAILS**
For parity, we want to do this for all environments: arch, test, and prod.  We have other tickets in place to ensure that arch and test are not accessible by the general public - see #427 & #428

Please link any related network services / security tickets to this in the comments.

**ACCEPTANCE**
1) I can reach the following applications from the public internet (i.e. without needing to be on campus or VPN)
- [x] digital.libary.emory.edu
- [x] digital-arch.libary.emory.edu
- [x] digital-test.libary.emory.edu
- [x] curate.library.emory.edu
- [x] curate-arch.library.emory.edu
- [x] curate-test.library.emory.edu

2) Cantaloupe iiif endpoints (http / https) cannot be reached by anyone except the relevant curate instance
- [x] iiif-cor-arch
- [x] iiif-cor-test
- [x] iiif-cor-prod

**Comment by SolomonHD** [comment]
@rotated8 @eporter23 Have the issues with restricting iiif and curate been resolved? I can't really open it up to the public until iiif is restricted on all environments, http basic auth or no.

**Comment by mark-dce** [comment]
@SolomonHD take a look at this ticket in ZenHub:
https://app.zenhub.com/workspaces/dlp-lux-5c75900b135e053ed882c4d0/issues/emory-libraries/dlp-lux/429

It's flagged as being blocked by #427 & #428 - those two tickets need to be completed and deployed first.

**Comment by SolomonHD** [comment]
The Cantaloupe servers are only accessible via their respective curate.

**Comment by SolomonHD** [comment]
After moving all iiif to the internal-only ALB, I've submitted a ticket to make the internet facing ALB open to the full internet. RFTASK108961

**Comment by SolomonHD** [comment]
The security person handling the ticket, Elliot, has a concern about the http basic auth that sits in front of lux. He thinks that means the website is unfinished and he wants to wait until that's removed before making the VIP public. I will discuss this tomorrow at standup.

**Comment by SolomonHD** [comment]
Collin, Mark B and I had a meeting with Elliot last Friday afternoon:

- Elliot doesn't want to have anything using http basic auth public, he proposed IP Whitelisting as an alternative
- We decided on using IP Whitelisting instead of http basic auth
- The whitelising will be on the apache level so that the luxes' have the same general network configuration

**Comment by SolomonHD** [comment]
The curate and lux environments are public available.

**Comment by tmiles2** [comment]
![image.png](https://images.zenhubusercontent.com/5c07f3880498270a145dcf84/861d56b2-c969-44af-800f-4aa189785630)
