### ISSUE TITLE
(SPIKE) What version of Blacklight should we use? 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#43]
- [x] Make an ADR style document outlining the trade offs related to adapting blacklight 6 vs blacklight 7 for DLP Lux
- [x] Read other ADR examples

**Comment by bess** [comment]
We will use Blacklight 7 because Blacklight 6 has a bug preventing it running in production.

Decision documented in an ADR here: https://github.com/emory-libraries/dlp-lux/blob/master/architecture-decisions/0002-Blacklight-Version.md
