### ISSUE TITLE
Update About Digital Collections page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#432]
## Acceptance Criteria
- [ ] Uses body text and heading styles from pattern library / [library website](https://libraries.emory.edu/materials/books.html).
- [x] Colors and styles similar to that found at https://libraries.emory.edu/contact/office-department-contacts.html
- [ ] Reset the page title element to full-width, similar to https://libraries.emory.edu/contact/office-department-contacts.html

## Wireframe
- [ ]  [Content and style](https://docs.google.com/document/d/1ZQE6brthA0nq-Ya0ogL054TEMjhEJnuCBrpopFntNK8/edit#heading=h.v4d5equdx2ca)
- [ ] [Static Page Template](https://docs.google.com/document/d/1xRp_yZi-44z4K8pUMbZahXVQBlBo43wT47lAGU5eoeE/edit)

**Comment by lovinscari** [comment]
@nikdragovic and @eporter23 - Rosalyn asked that we reach out to the Core Team to ensure they have approved the content on this page. Additionally, she would like us to reach out to Jody Bailey specifically to ensure she is aware and in agreement with the approach for copyright and reuse. I will add this to our agenda for Lux - Curate meeting tomorrow (4/10).

**Comment by bwatson78** [comment]
@lovinscari Should I move forward with this ticket? I'm not sure what was said during that Curate meeting.

**Comment by nikdragovic** [comment]
@bwatson78 Thanks for moving forward with this. FYI - I made some small edits to the last section - Questions, Help, and Feedback.
