### ISSUE TITLE
Set environment variables to password protect lux in production

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#437]
In order to make the production instance of lux (digital.library.emory.edu) available on the public internet without having it crawled, please set the following environment variables: 

- [x] HTTP_PASSWORD_PROTECT="true"
- [x] HTTP_USERNAME="lux"
- [x] HTTP_PASSWORD="don'tcrawlme"

**Comment by SolomonHD** [comment]
This has been enabled across all environments, please check the slack channel for the password
