### ISSUE TITLE
Issues loading images for Emory Low Download works in curate

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-lux#450]
Notes:

* Behavior I am seeing, for this work (https://curate-test.library.emory.edu/concern/curate_generic_works/177fqz612s-cor), when I try to open this in incognito, the images aren’t loading. If I open this same work in lux, the images load fine, and then when I refresh the curate page, the images start working (probably due to caching from the successful lux page load).

**Comment by maxkadel** [comment]
https://github.com/emory-libraries/dlp-curate/pull/1114

**Comment by maxkadel** [comment]
Note: The current version of this edit makes images available to anyone with a Curate login. Emily is working on refined requirements and will work on a ticket to further clarify image delivery access restrictions within Curate.
