### ISSUE TITLE
Style dropdowns

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#455]
Style the header and footer dropdowns.

[Figma](https://www.figma.com/file/B7WWVWaPZOsvffwAbDXMf1cb/Emory-System?node-id=0%3A148) design for targeted field search dropdown:
![image (3).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/06fe2211-688a-488a-93f3-f0c1d43f95ce)

[Figma](https://www.figma.com/file/B7WWVWaPZOsvffwAbDXMf1cb/Emory-System?node-id=0%3A336) design for Select a Library dropdown:
![Screen Shot 2020-03-30 at 10.16.59 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/331a6a9c-4fc2-4d14-9478-a9dd0d958a44)

[Related pattern library style for navigation dropdowns
](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/40-compounds-navigation-subnav-menu-main/40-compounds-navigation-subnav-menu-main.html)

**Comment by wulman16** [comment]
@nikdragovic I propose we tag this as post-beta because it was not originally a requirement for the header or footer.

**Comment by wulman16** [comment]
If we implement the Figma design with all 12 options currently in the footer dropdown, it would be over 700px tall, which is almost twice the height of the footer at desktop width. We could make a more compact version of that dropdown, but it would look significantly different from the Figma design. I can try to make a rendering of what such a dropdown would look like in our current footer.

**Comment by wulman16** [comment]
**Default:**
![Screen Shot 2020-05-13 at 2.37.11 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/becf7852-8386-4070-95b2-3c3761fdf249)

**Active:**
![Screen Shot 2020-05-13 at 2.37.20 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/7d3ed5dc-15aa-477e-9227-71c21597bcfe)

**Comment by wulman16** [comment]
**Default dropdown:**
![Screen Shot 2020-05-14 at 10.57.15 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/741132bb-baf8-4a57-9e0a-8cacb0c4332e)
**Active dropdown:**
![Screen Shot 2020-05-14 at 10.57.25 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/463d0b9c-9757-4a48-af21-a0e37992c7b5)

**Comment by nikdragovic** [comment]
@wulman16 The header dropdown looks awesome. I'm going to close this ticket for now and create a separate one when we determine what course to take with the footer.
