### ISSUE TITLE
Update the homepage hero section

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#456]
## Enhancements
- [x] Insert final approved [cropped images ](https://emory.app.box.com/folder/106881613222)
- [x] Link the provided images to the production ID (in the filename)
- [x] Add a semi-transparent overlay or outline the text for better readability
- [x] Slow cycle timing (10 seconds?)
- [x] Style "View Featured Item" as [badge](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=atoms-button-form) for better readability

**Comment by wulman16** [comment]
@nikdragovic What kind of badge should the "View Featured Item" be? Do you have a specific pattern in mind?

**Comment by nikdragovic** [comment]
@wulman16 We can reuse the button style that is coming from the searchbox in the header:
http://template.library.emory.edu/styleguide/patternlibrary/current/?p=atoms-button-form

**Comment by wulman16** [comment]
@nikdragovic There are 7 images in the Box folder and 2 images in a post-beta folder. Which images are we using?

**Comment by eporter23** [comment]
@wulman16 please use the 7 top level ones and not the ones in post-beta. The post beta ones are for collections not yet ready to feature.

**Comment by wulman16** [comment]
![Screen Shot 2020-04-16 at 1.48.08 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/ecca6f03-76f4-4b60-b1f9-c34395acb799)
