### ISSUE TITLE
Review pages for 500 class errors.

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#458]
After Honeybadger instance for Lux is reconfigured, monitor exception reports to determine if any common or likely errors should have a customized page.

Examples:

- Attempting to reach the bookmarks page when not logged in (digital.library.emory.edu/bookmarks) leads to a generic error page:

![Screen Shot 2020-02-06 at 5.33.09 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/bdd8a5a9-7efc-4281-a00e-248c4f1d0132)
- Another rails page, but this one goes to the unstyled custom page - https://digital.library.emory.edu/rails/info/properties

**Comment by rotated8** [comment]
@SolomonHD The `HONEYBADGER_API_KEY` is missing from the digital envs.
