### ISSUE TITLE
Performance test: iiif

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#462]
Use jmeter (or equivalent) to load test image delivery in production. We would like to establish a baseline performance for the following types of queries:

- [x] iiif response for a full image
- [x] iiif response for various image regions
- [x] iiif response for rotated images
- [x] manifest delivery especially for multi-page objects

TEST PLAN
- [ ] Write test suite and confirm syntax without load (i.e. just run each request 1 time - mimics one of us loading the images from our browser)
- [ ] Estimate anticipated production load: number of unique users x number of requests per minute/hour
- [ ] Secure a 2 hour test window by announcing in Slack and confirming Max & Mark P's availability - give at least a half day notice (i.e. confirm at standup for the following business day)
- [ ] Run the test suite with load (simulate multiple users running multiple request cycles) with the current JVM Settings at the following load levels (terminate testing if we see dramatically adverse responses at any load level) (watch htop during testing to determine memory use) (Run each test for 2-3 minutes)
  - [ ] 10% of anticipated load 
  - [ ] 25% of anticipated load
  - [ ] 50% of anticipated load 
  - [ ] 75% of anticipated load
  - [ ] 100% of anticipated load
  - [ ] 125% of anticipated load
- [ ] Increase the JVM heap size (to something around 75% of available memory) and rerun the loads
  - [ ] 50% of anticipated load 
  - [ ] 75% of anticipated load
  - [ ] 100% of anticipated load
  - [ ] 125% of anticipated load
- [ ] Time permitting, run a soak test at the maximum sustainable load (i.e. the load where response times are not compromised) and ensure response times don't creep upward

Also investigate:
When UV is loading a 500 page book, does it get all 500 page thumbnail images on the initial load?

**Comment by maxkadel** [comment]
Reporting in Emory Box - https://app.box.com/folder/110689866375
