### ISSUE TITLE
One type of date not indexing correctly 

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#464]
If you go to https://digital.library.emory.edu/?utf8=%E2%9C%93&search_field=common_fields&q= and go to the date facet, and limit to the earliest set of dates (e.g. 192 to 200) and click "apply", you will see a set of results from the 20th century with 2 possibly decades (e.g. 1930s or 1940s). These are being indexed in the fields for the date slider as 3-digit dates, rather than 4-digit dates. 

See, for example: http://solr-cor.library.emory.edu/solr/curate_collection/select?q=id%3A0106wwpznt-cor

```json
"date_created_tesim":["193X/194X"],
"year_created_isim":[193, 194],
"human_readable_date_created_tesim":["within the 1930s or 1940s"],
"year_for_lux_isim":[193, 194]
```

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/3b28ed64-f54f-4bb6-ba67-25094bfe47f8)

**Comment by tmiles2** [comment]
If it remains only a few (under 15) objects we will do a manual re-index of effect works

**Comment by maxkadel** [comment]
Previously, dates recorded as "192X/193X" were parsed as "192" for Lux, leading to the date slider showing the wrong dates for these types of items

After:
![image](https://user-images.githubusercontent.com/45948126/79506810-9e2a0580-8004-11ea-907e-08499c503d1b.png)

**Comment by maxkadel** [comment]
All objects on production have been updated, and the timeline no longer shows any object prior to 1600 (which is there correctly)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9db8c09b-b21a-4417-9e7d-14ee63721207)

**Comment by nikdragovic** [comment]
Thanks @maxkadel! Tangent to the ticket in question, but I am curious why browsing using the date facet (using the steps you described in the ticket description) doesn't work from the homepage but appears to work from the search page. I opened bug ticket #511 so I could close this one.
