### ISSUE TITLE
Add disclaimer to Access and Copyright section

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#468]
On the show work page, add the following statement at the bottom of the Access and Copyright section:

_Emory Libraries provides copyright information as a courtesy and makes no representation about copyright or other legal status of materials in its digital collections._

## Acceptance Criteria
- [ ] Statement appears on all works for which the Access and Copyright section appears.

## Wireframe
![Lux Beta Wireframes - Working Document - Access and Copyright (1).png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/a492bf7c-b67a-45ae-a95d-e23c7586e2c7)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-16 at 10.53.58 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/5bee7925-3533-46b7-9f69-20805b943597)

**Comment by bwatson78** [comment]
PR created for ticket:
https://github.com/emory-libraries/dlp-lux/pull/505
