### ISSUE TITLE
Smoke test for lux

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#472]
Create an automated test for:

- [x] Are the things we expect to be public public?
- [x] Are the thins we expect to be private private?
- [x] Does image delivery work as expected?
- [x] Does image download work as expected?
- [x] Do image thumbnails work as expected?
- [x] Are the search results roughly what we expect to see?

**Comment by nikdragovic** [comment]
@fnibbit Thanks for this! Will we have any report summary or benchmark results for the Box folder? I believe you mentioned this was also a jmeter test, so would there be a .jmx file associated with it?

**Comment by fnibbit** [comment]
Instructions on running the smoke test: 
https://github.com/emory-libraries/dlp-lux#run-jmeter-smoke-test
Test file:
https://github.com/emory-libraries/dlp-lux/blob/master/jmeter/smoke-test.jmx
