### ISSUE TITLE
Thumbnails for non-standard visibility in Lux

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#473]
* Currently a non-logged-in user cannot see Public Low Res thumbnails in Lux, requires work in Curate.
* Need to verify thumbnail behavior for other types of visibility (Emory Low, Emory High, for logged in Lux users)

**Comment by nikdragovic** [comment]
@maxkadel I am testing Emory Low and High objects while logged into Lux, and seeing the blue/white page icon. We do want to render the actual thumbnail. 

Not sure if this was what you wanted to verify (in the ticker description), but wanted to provide the info in case it helps.

**Comment by maxkadel** [comment]
In Incognito window, without Curate login 
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/02b57971-0ad2-4b77-91d0-1e8b69c2c65f)
