### ISSUE TITLE
For logging in - do University Healthcare ID's work the same as University ID's?

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#482]
With regard to different functions such access restriction?

**Comment by nikdragovic** [comment]
@SolomonHD Do you know if the Shibboleth login includes all university IDs and excludes Healthcare IDs?

**Comment by tmiles2** [comment]
@nikdragovic @eporter23 @lovinscari  Solomon and I met with Gerry Hall to discuss the Healthcare users login. During the meeting meeting it was determined:

1. Healthcare IDs are considered netIDs
2. If a users enters in a password and netID that match the application will complete authentication for the user. 
3. As long as the user is authenticated by Shibboleth their access should follow the parameters set within application.
