### ISSUE TITLE
Implement IP allowlist for arch and test environments

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#483]
@mightycollins @SolomonHD Please let me know if I need to add any more details to this ticket.

We need all possible Emory public and private IPs to be allowed, including VPN, if I understand correctly.

HTTP Auth for now, transition to IP Allowlist within the next 4 weeks.

**Comment by mark-dce** [comment]
When Solomon and I were talking with Elliot, we discussed having the whitelist includ all private network addresses (i.e. addresses that can be used within Emory but can't be accessed on the public internet) and Emory's public class C address ranges:

**PRIVATE ADDRESS RANGESS** (see https://www.arin.net/reference/research/statistics/address_filters/)
10.0.0.0/8 IP addresses: 10.0.0.0 – 10.255.255.255
172.16.0.0/12 IP addresses: 172.16.0.0 – 172.31.255.255
192.168.0.0/16 IP addresses: 192.168.0.0 – 192.168.255.255

**EMORY CLASS C ADDRESS RANGE**
170.140.0.0/16 - https://ipinfo.io/AS3512

**Comment by nikdragovic** [comment]
As discussed on 5/20/20, we are not required to do this, so we'll deprioritize it and address later if needed.
