### ISSUE TITLE
Issues viewing images in Lux UV when not logged into Curate

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#487]
When simulating a Public user (incognito mode, not logged into Lux or Curate), some work images do not load. For these images, attempting to download results in failure.

![Screen Shot 2020-04-10 at 9.01.32 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/55ebb762-c47a-4782-9f90-880e24954af1)

![Screen Shot 2020-04-10 at 9.02.01 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e4370395-f58d-45b9-ac2b-8216e5a005ee)

After logging into Curate and hitting refresh, the images load in the viewer and download as expected.
![Screen Shot 2020-04-10 at 9.07.15 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/9ffbc9cc-df0e-4548-a118-9d909e8b699c)

**Comment by maxkadel** [comment]
Investigation:
- work id: 808v9s4n2w-cor
  - visibility: open
- file_set_ids_ssim: 
  - 269m37pvtx-cor
  - 658pc86718-cor
  - 054kkwh76w-cor
  - 556931zczg-cor
  - 56341ns1xv-cor
- https://digital.library.emory.edu/catalog/808v9s4n2w-cor
- https://curate.library.emory.edu/concern/curate_generic_works/808v9s4n2w-cor
- http://solr-cor.library.emory.edu/solr/curate_collection/select?q=id%3A808v9s4n2w-cor
- https://curate.library.emory.edu/iiif//808v9s4n2w-cor/manifest
- https://curate.library.emory.edu/iiif/2/d423cd47b22379c66fdef3fad37908889051e453/info.json
- image 1 (loads) - https://curate.library.emory.edu/iiif/2/d423cd47b22379c66fdef3fad37908889051e453/full/600,/0/default.jpg
- image 2 (doesn't load) - https://curate.library.emory.edu/iiif/2/7e806d016e054810b99efabc4e23a14ceff92dc7/full/600,/0/default.jpg
- image 3 (loads) - https://curate.library.emory.edu/iiif/2/ae6e90fad7be0792ab01a0a7ec57ed43226cc563/full/600,/0/default.jpg
- image 4 (doesn't load) - https://curate.library.emory.edu/iiif/2/7b96f4f52d81e46f26084d39fdcbfce1c9b6cfe2/full/600,/0/default.jpg
- image 5 (loads) https://curate.library.emory.edu/iiif/2/e989a4aa6d7a975f222d8b18dea29c4c346ec7ad/full/600,/0/default.jpg

**Comment by nikdragovic** [comment]
@SolomonHD Here's the ticket from today.
