### ISSUE TITLE
Environment variable on Curate needs to be set

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#488]
"localhost:3000" is showing up as the domain for persistent URLs in the production system. 

LUX_BASE_URL needs to be set on Curate, and then I believe production will need to be re-indexed in order for this to display correctly in Lux.

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/940214ac-0980-4646-93d6-fc41dc492306)

https://digital.library.emory.edu/catalog/9354f4qrn8-cor

**Comment by nikdragovic** [comment]
@mark-dce and @bess will be adding this item to a pre-launch "check" list.
