### ISSUE TITLE
Adjust hyrax schema for compatibility with Blacklight 7 application

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-lux#49]
Currently digital-arch.library.emory.edu is throwing solr errors due to incompatibilities between blacklight 7 solr schema and curate_collection. 

- [x] Adjust hyrax schema for curate-arch
- [x] Test if digital-arch is working properly with curate-arch's schema

**Comment by bess** [comment]
![lux_search_results.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/5d2728c2-ba9a-4619-8e55-1e8da0c594c3)

**Comment by bess** [comment]
![digital_arch_search_results.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/1cc4e45c-7157-487b-adec-c0b896cfd9e4)
