### ISSUE TITLE
SPIKE: Implement citation gem 

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#490]
Acceptance Criteria 
- [x] Research and attempt to install citation gem in given timebox
- [x] Optional: Add italicized disclaimer at the top of the citation window: _"Provided as a suggestion only. Please verify these automated citations against the guidelines of your preferred style.”_
- [x] Optional: Shorten default language to "APA, 6th edition" "MLA" and "Chicago"

**REFERENCES**
There is an open source initiative to make machine generated citations easier and more consistent.  The initiative is named "Citation Style Languages" (CSL) - you can find out more at https://citationstyles.org

There are a number of ruby gems implementing CSL
* https://rubygems.org/gems/citeproc-ruby
* https://rubygems.org/gems/csl-styles
(also [others](https://rubygems.org/search?utf8=%E2%9C%93&query=citation+style+language), but we've used the two above)

Here's a PR in another project implementing CSL in a Hyrax app  
https://github.com/curationexperts/mahonia/commit/6697e143b9f23ee7bafd505bcd172c5d0e098e9f  
This is the main PR, so It may be worth checking out commits after that for any refactoring or polishing

[Lux Citation Mapping](https://docs.google.com/spreadsheets/d/14ijl7_ND5mCuYE1MxeAzJtS0UMnCR24snne_FpZ_Xc8/edit?usp=sharing)
[Original Requirements from Metadata Working Group](https://wiki.service.emory.edu/pages/viewpage.action?pageId=119147632#Metadata/DataEntryFunctionalRequirements-CitationBuilders)

**Comment by bwatson78** [comment]
PR made for this issue: https://github.com/emory-libraries/dlp-lux/pull/514

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-20 at 3.44.39 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c5f169ff-dd19-4981-8142-c43e22b51423)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-20 at 3.44.23 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/90664881-fac1-4f54-8051-edae88b7cf76)

**Comment by bwatson78** [comment]
@nikdragovic Addresses the change of the headers you requested.

![Screen Shot 2020-04-21 at 10.19.55 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2d628517-8002-494d-b13c-1c968f87a492)

**Comment by bwatson78** [comment]
Have changed the estimation to 5 and will swap tools to the official `citeproc` gem mentioned in the description as requested by @maxkadel.

**Comment by lovinscari** [comment]
@bwatson78 and @maxkadel  I understand from @nikdragovic there has been some back and forth with how to proceed on this issue? Since we are unable to get this completed as part of beta launch by tomorrow (Tuesday), I will need to ask that we remove the Cite from the Tools menu. We can discuss during our follow up meeting today (4/27) but it is imperative the "Cite" link be removed from Tools menu. This was communicated during the beginning of the sprint but somehow was lost in translation.

**Comment by bwatson78** [comment]
@lovinscari and @maxkadel, I will take on the removal of the site link, and will have a PR ready today.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-27 at 3.56.20 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a220c975-6123-40bb-afca-57dfd28994ff)

@nikdragovic Do you approve of this styling?

**Comment by bwatson78** [comment]
PR ready for review: https://github.com/emory-libraries/dlp-lux/pull/552
