### ISSUE TITLE
Remove email, help, feedback links from Bookmarks page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#492]
Depending on the outcome of the citation spike, we may need to remove that link as well.

**Comment by wulman16** [comment]
![Screen Shot 2020-04-22 at 10.05.02 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/91cd102a-41af-47ea-92c1-65a96e0d209b)
@nikdragovic The work on #500 had the side effect of changing the links at the top of the Bookmarks page as well. Are Cite, Help, and Feedback the desired links for this page?
