### ISSUE TITLE
"Log In Required" placeholder thumbnails not displaying

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#513]
As of Monday 4/20, no "Log In Required" placeholder thumbnails are displaying when not logged in to Lux. "Reading Room Only" thumbs are displaying properly.

- Exact time: Monday 4/20 at 6:59AM, Sunday 4/19 sometime in the evening, post-deploy
- Environment: Prod and test
- On VPN or off VPN? Off VPN
- Had an active Curate login? No
- Had an active Lux login? No
- Incognito window, or one that had been open for awhile? Incognito

https://digital.library.emory.edu/?f%5Bvisibility_group_ssi%5D%5B%5D=Log+In+Required&q=&search_field=common_fields

![Screen Shot 2020-04-20 at 6.59.04 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/867c785c-5add-4d8a-9e1d-857de0ef1d00)

**Comment by maxkadel** [comment]
As of 8:33 am on 4/20/2020 thumbnails were working again, have not yet been able to reproduce.

**Comment by nikdragovic** [comment]
This issue has not recurred in several days and has not been reproduced.
