### ISSUE TITLE
Update Contact page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#516]
Acceptance Criteria
- [ ] Text updated according to Google document; changes highlighted.

## Wireframe
- [ ]  [Content and style](https://docs.google.com/document/d/1LvGlw1qC9me9ZMp_RZtuBa1_BL7Y4Pp2wGdOgO-caoA/edit#heading=h.jqbgjn2v8urs)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-22 at 8.47.20 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/bb16fcad-2d8f-4a25-93d0-e242f84c959b)

PR made: https://github.com/emory-libraries/dlp-lux/pull/520
