### ISSUE TITLE
Project Retrospective Prep

### ISSUE THREAD

**Issue by RachelDCE** [emory-libraries/dlp-lux#526]
Please, everyone involved with our Lux retros, take some time to think back over the arc of this project. Think about where we were when we embarked on this journey back in Fall ‘19, where we were in the middle of the project around the beginning of the new year, and where we are now at beta launch. 

_The goal of our project retro: To highlight and learn from successes and likewise to learn from any shortcomings. What have we learned as a team and as individuals that will inform how we run the next phase of this project and future projects?_

Here are just some prompting questions to help you think about it. Remember that specificity will help when we get to the discussion portion of the retro.

- What were some of your personal favorite, proudest moments or achievements - “big” or “small”?

- What are you proud of your team for accomplishing?

- What parts of the process were beneficial -or- barriers to forward progress? 

- To do it all again, what might we do differently - technical or procedural? 

Thank you for taking the time and effort to prep for a successful retro.

**Comment by tmiles2** [comment]
Retro notes: https://docs.google.com/document/d/1c0M0pCj3pQnvE2Wzz_N1B0u5OhQCz95Q5bFXJThv14E/edit

Retro board: 
https://docs.google.com/document/d/1INkfku8CQpni51ALEWdJjMEZuVwFbwjRaAL9jiSj4Bg/edit
