### ISSUE TITLE
Support additional EDTF date translations

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#531]
[Detailed summary of currently supported and unsupported date formats
](https://docs.google.com/spreadsheets/d/1tm7RDYWVcAWEZuA-lB3cbxxGI4qjn8uCn71X2EJPB50/edit?usp=sharing)
[Test object in digital-arch
](https://digital-arch.library.emory.edu/catalog/119f4qrfn0-cor)
## Acceptance Criteria
- [ ] Check list for any unsupported date formats
- [ ] Enable user-friendly display for any date formats currently unsupported

**Comment by fnibbit** [comment]
I have an update merged to use the human_readable_data_collection_dates_tesim field instead of the data_collection_dates_tesim field in solr; curate added this field along with several other human_readable date fields in December to support Lux viewing, but lux hadn't picked up the data_collection_dates one.

Once that update is installed on arch, that test object should be displaying more as expected.

**Comment by fnibbit** [comment]
Current state: Lux displays dates from the human_readable_date_created_tesim, human_readable_date_issued_tesim, human_readable_data_collection_dates_tesim, conference_dates_tesim, copyright_date_tesim fields.  human_readable_copyright_date_tesim and human_readable_conference_dates are populated in solr but not currently displayed.

In the human_readable_ date fields, out of the date format list in that spreadsheet, we have: 
(seem broken)
original date: 1976~ human_readable: 1976~ desired(?): 1976 approx. 
original date: 18XX human_readable: 180s0s desired: 1800s
original date: XXXX-12 human-readable: XXXX-12 desired: October

(legible but not as documented)
original date: 200X/201X human_readable "Within the 2000s or 2010s" desired: 2000s - 2010s
original date: 2010-04-22/2010-04-23 human_readable "April 22, 2010 to April 23, 2010" desired:  "April 22, 2010 - April 23, 2010"
original date: 1998-01/2001-05 human_readable: "January 1998 to May 2001" desired:  "January 1998 - May 2001"
original date: XXXX-12-25 human_readable: "December 25, year unknown" desired: "December 25"
original date: 1998/2013 human_readable: "1998 to 2013" desired: "1998 - 2013"

**Comment by fnibbit** [comment]
Merged, not yet installed: change to use human readable forms of copyright and conference date.

In the Curate code, app/services/date_service.rb defines how those human_readable dates are generated.

**Comment by nikdragovic** [comment]
Based on yesterday's discussion, we will need to reindex affected objects to see these changes.

**Comment by eporter23** [comment]
@nikdragovic @tmiles2 I've written a followup ticket dlp-curate 1186.

**Comment by nikdragovic** [comment]
Closing since there's a new ticket to complete this.
