### ISSUE TITLE
Spike: Documented troubleshooting tips based on experience with Blacklight and Solr

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#536]
Over the course of the project, there have been a few errors (such as "Sorry, I didn't understand your search) that we had to rely on informed guesses to diagnose before doing deeper investigation. It would be helpful to understand what additional errors the application might generate alongside a possible causes.

As a DCE / Emory team:
- [x] Go over the running in production practices document that DCE wrote
- [ ] Make sure everyone can check honeybadger and understands how to read the reports
- [ ] Talk about how we detect errors and agree as a team on how to respond

**Comment by nikdragovic** [comment]
Link to Lux production checklist: https://emory.box.com/s/lgtg34qki5xwsdk6nrd0ms5m3b8hdyqp

@bwatson78 @wulman16 Can you please review this document when you are able?

**Comment by wulman16** [comment]
@nikdragovic I just went ahead and read through it. Are we meeting at some point to discuss some of the details? (e.g., who is responsible for regular review of monitors, alerting & other issue reports)

**Comment by nikdragovic** [comment]
@wulman16 Yes, that would be good. I'll make sure we get something set up in the next week or two.

**Comment by bwatson78** [comment]
@nikdragovic I just reviewed the document and cannot think of anything to add or discuss.

**Comment by nikdragovic** [comment]
Closing this ticket, as the remaining criteria for this ticket will be in scope for operations planning.
