### ISSUE TITLE
Use MySQL in local development

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#54]
If our expectation is to use MySQL in production, we should also use MySQL in development. Currently, the application is configured to use MySQL in production but sqlite for test and development. This could lead to database schema problems that we don't find until we're trying to deploy to production.

**ACCEPTANCE CRITERIA**
- [x] Local development runs against a MySQL database
- [ ] Local test suite runs against a MySQL database
- [ ] the README includes instructions for how to set this up

**Comment by SolomonHD** [comment]
socket field should be something like:

socket: <%= ENV['MYSQL_SOCKET'] || ' /tmp/mysql. sock' %>
