### ISSUE TITLE
Add PURL field to Find this Item section on show pages

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#540]
## Acceptance Criteria 
- [ ] Add a linked field to the top of the "Find this Item" grouping that replicates the link from the Universal Viewer PURL field.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-29 at 10.03.36 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2923af52-ea13-4dc1-a839-b3bceb2dceb2)

PR made: https://github.com/emory-libraries/dlp-lux/pull/560

**Comment by nikdragovic** [comment]
Note that this is hard to test by clicking the link, since test and objects don't have the same works, and don't have the same IDs even if they are the same object.
