### ISSUE TITLE
Use local copy of icons, rather than fetching from remote site, for performance

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#544]
![image](https://user-images.githubusercontent.com/45948126/80373847-afc0a800-8863-11ea-94fd-adb121683924.png)

and 
![image](https://user-images.githubusercontent.com/45948126/80374055-104fe500-8864-11ea-94a6-1c0f2ba3ba16.png)

**Comment by nikdragovic** [comment]
@maxkadel @wulman16 I am no longer able to see the arrows in the header search dropdown or the footer, in any of the three environments.![Screen Shot 2020-04-27 at 4.25.51 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/aa3494c4-7ff2-4026-8c75-f8eed3681621)
![Screen Shot 2020-04-27 at 4.25.56 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f116fd68-c3fe-4101-87e6-fa3064f214fa)
