### ISSUE TITLE
Remove "Sample Data" rake task

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#545]
This task was used to create a Solr index for use in development environments at the very beginning of the project. The fixture Solr index is far out of date, and is no longer useful for development, and can even be misleading. 

The task should either be removed or a new snapshot should be created for the purpose.
## Acceptance Criteria
 - [x] Remove rake task & fixtures used only for "Sample Data"
 - [x] Remove any references in Read Me or other documentation

**Comment by nikdragovic** [comment]
@maxkadel Thank you for writing this up. I'm in favor of removing the rake task and related references.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/641
