### ISSUE TITLE
Update Lux 404 page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#550]
We will be removing the access restrictions content from the current 404 page, and creating a new flow for access restrictions in response to user and stakeholder feedback.

## Acceptance Criteria
- [ ] Text updated according to Google document.

## Wireframe
- [ ]  [Content and style](https://docs.google.com/document/d/1O2ILCZrgbGuqmW0Vv_6WTw547k1AOPKKJkbPpXxB49w/edit?usp=sharing)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/637

![Screen Shot 2020-07-09 at 9.57.48 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/69ba1fba-acab-456b-925f-91d111917ce7)

**Comment by nikdragovic** [comment]
@bwatson78 This looks great, thanks. However, since this page is currently presented when a non-logged in clicks on a Log In Required item, we may need to wait until #624 is complete to send this to prod.
