### ISSUE TITLE
Stack traces in Curate still visible

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#551]
Unauthenticated users can see stack traces on Curate via the iiif controller, which can be a security issue, as well as being unpolished.

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/82b1ee0a-142e-4aad-8424-0ba6acbf24e8)

In addition, when Fedora can't find an object, it creates an error:

https://curate-arch.library.emory.edu/iiif/2/1e9ad3613b229dd3d4c786c5a22ed69a6efac786/info.json

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9b4115a4-6285-457a-a3ad-c1a56eae3182)

**Comment by rotated8** [comment]
Merged, pending deploy

**Comment by maxkadel** [comment]
No longer getting a stack trace, getting routed to the expected URL, then getting appropriate 404 status and error message
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/a276818c-015f-4fd0-9ca6-b7d4c593d7de)

Errors are being logged to Honeybadger and grouped appropriately (if these show up again, or in production, you'll want to chase down the missing files)
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6e7c642d-81d7-4d4a-b366-a4738e9e3ae6)

https://app.honeybadger.io/projects/66999/faults/63289982
