### ISSUE TITLE
Clean up temp files and saved searches

### ISSUE THREAD

**Issue by bess** [emory-libraries/dlp-lux#555]
Over time, the search history in Blacklight's database accumulates and gets unwieldy. Better to clean it out with an automatically run rake task, as described here: 

https://curationexperts.github.io/playbook/every_project/cleanup_temp_files.html

ACCEPTANCE CRITERIA
- [x] There is an automatically run task that will clean up temp files
- [x] There is an automatically run task that will clean out the search history from the database

Note this might require some intervention from @SolomonHD to ensure the `deploy` user's crontab file has its path set correctly. See https://github.com/curationexperts/ansible-samvera/blob/master/roles/capistrano_setup/tasks/main.yml#L54

**Comment by nikdragovic** [comment]
@SolomonHD Do you know if this work is complete?

**Comment by tmiles2** [comment]
Remaining work: Run a conjob

**Comment by SolomonHD** [comment]
The crontab had the needed info on all environments already.
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/c48c7fd0-4ab4-47af-a1ac-853a7980569b)

And they appear to be running fine:
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/a3fea86b-ac45-45f6-8485-6860320114c6)
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/4e57f30e-dd59-405d-ab89-3486598eecab)
