### ISSUE TITLE
Breadcrumb display breaks for long object titles

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#556]
We should determine whether we can rectify this, or possibly constrain the hover text to a more manageable character maximum.

[Example object](https://digital.library.emory.edu/catalog/8708w9gj2k-cor)

[Additional example - no change in text when hovering](https://digital.library.emory.edu/catalog/634sj3txf8-cor)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-30 at 8.14.01 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/54b11d51-a8cb-4d44-b59e-07a620cd4fa5)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-30 at 8.16.51 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c08a2114-9a91-4a53-aaa4-39b235911bb4)

**Comment by nikdragovic** [comment]
Tested with: https://digital-test.library.emory.edu/catalog/938jdfn30v-cor
