### ISSUE TITLE
Display breadcrumbs on Advanced Search, Bookmarks, and History pages

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#557]
## Acceptance Criteria
- [ ] Breadcrumbs similar to those on static pages are applied to these pages.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/565

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-30 at 3.06.49 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9ae22246-2629-4e24-9214-f4a708ee58a5)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-30 at 3.06.42 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/947ff17c-19db-4c78-82fa-c7e9096c4780)

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-30 at 3.06.34 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9d5f0c0d-db3b-4d49-8001-8b60cf0f8f0d)
