### ISSUE TITLE
Make sure UCLA doesn't appear in google results for digital

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#559]
Not sure how UCLA got in there, but probably not ideal.

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/952821c5-57be-4274-8b28-030f184e91b3)

**Comment by mark-dce** [comment]
It's somewhat hard to replicate those results, but I can find them using the following search:  
https://www.google.com/search?q=library+emory+digital+contact&oq=library+emory+digital+contact&aqs=chrome..69i57j33.621j0j7&sourceid=chrome&ie=UTF-8

It appears to be specific to something related to the contact page (or that was on the contact page at some point).  I can't find anything in the page source that should cause that.  It might  be worth having someone search Emory's Google Search Console for UCLA to  see if anything shows up.

Although - I do notice that yellowbacks are referenced on UCLA's site here (search for Emory on the page), so it may be google trying to do something fancy: https://www.library.ucla.edu/special-collections/discover-collections/online-collections & https://www.library.ucla.edu/blog/special/2015/10/29/crowdsourcing-the-graphic-covers-of-victorian-crowdpleasers-event-was-a-real-crowd-pleaser

**Comment by maxkadel** [comment]
Sorry, I believe it was a search for `"Emory Digital Collections"` (quotes included). Emily used the google search console to request a reindex of that page and requested a cache clear.

Looks like it's been resolved.

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/f2987f79-4e28-47e6-8b27-9fb6d5c44372)
