### ISSUE TITLE
Update text on the About Digital Collections page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#566]
Update in accordance with three highlighted sections on [wireframe](https://docs.google.com/document/d/1ZQE6brthA0nq-Ya0ogL054TEMjhEJnuCBrpopFntNK8/edit?usp=sharing).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/590

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-11 at 8.38.38 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/94a13404-413e-4bf6-a336-036ccbf6b837)
