### ISSUE TITLE
Use a replication-delayed index of the curate-arch solr cloud

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#57]

**Comment by tmiles2** [comment]
The replication will run once day 
The name needs to make sense and configured on the Hyrax side (.env.production file) lives in shared directory

**Comment by mprefer** [comment]
Created and installed bash script '/usr/local/bin/solr_api_back_restore.sh'
Created script '/usr/local/bin/sbr.sh' to actually run the backup/restore script with all it's parameters set. It's just easier to add to crontab.

Crontab has been update to execute the backup/restore each day at 10:00pm EST (3:00am UTC).
Crontab entry: 0 3 * * * /usr/local/bin/sbr.sh > /dev/null 2>&1

Executed manually to create the configs in Zookeeper and add the new collection (lux_collection) and to load the current curate_collection index data (current at the time executed).
Verified that the document counts in both collections were equal.

Just need to modify the SOLR_URL variable in /opt/dlp-lux/shared/.env.production and restart Apache.
