### ISSUE TITLE
Adjust footer height

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#570]
## Acceptance Criteria 
- [ ] Reduce global footer height to match Libraries website (approx 457 px)

**Comment by bwatson78** [comment]
@nikdragovic Is this pertaining only to computer screen width and not mobile? The footer balloons when width goes below 720px. Do any footer elements need to be hidden or resized once we squeeze smaller than 720?

**Comment by nikdragovic** [comment]
@bwatson78 Thanks! I think we can keep this behavior. Lux should follow the pattern prescribed by the Libraries website.

**Comment by bwatson78** [comment]
Thank you, Nik.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/593

![Screen Shot 2020-05-12 at 9.07.30 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/472b0554-6eb9-40fc-9dc8-0523c9b943db)
