### ISSUE TITLE
Homepage - adjust mobile layout

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#571]
## Acceptance Criteria 
- [ ] Layout is as pictured, with utility menu items appearing beneath shield and header

**Current:**
![Screen Shot 2020-05-05 at 12.34.16 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/30790e37-c98a-48cc-9f5d-77e48bcde940)

**Desired:**
![New Homepage Breakpoint.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/22772e35-459b-4476-be98-217fb7df4095)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/592

![Screen Shot 2020-05-12 at 9.14.27 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0cd368c9-fddd-408a-a369-20a16dcdd346)
