### ISSUE TITLE
Homepage - change text color of "Browse all items"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#572]
## Acceptance Criteria 
- [ ] Desired color is #082B73

**Comment by bwatson78** [comment]
@nikdragovic Would you like the same color on search result page header "Limit your search"? They are the same element--they just toggle headers depending on whether it's being served on the homepage or search results.

**Comment by nikdragovic** [comment]
@bwatson78 Yes, thanks! I included that in #575.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/594

![Screen Shot 2020-05-12 at 11.33.16 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c8d149a2-41f2-43b8-bc53-6d4dfdd339be)
