### ISSUE TITLE
Search Results Page - Alignment of result titles

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#573]
## Acceptance Criteria 
- [ ] Search result titles are aligned, with no indentation.

**Current:**
![Screen Shot 2020-05-05 at 2.55.30 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/1a4811b9-8cec-4832-81b1-ccc89a7d5ac0)

**Desired:**
![Screen Shot 2020-05-05 at 2.55.30 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/684289e4-d06e-42c8-bac7-01838e518d17)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/595

![Screen Shot 2020-05-13 at 9.47.30 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/fecdc03a-2b89-4298-984c-3e676cc54d53)

**Comment by bwatson78** [comment]
Bug found after deploying to test/arch: ![Screen Shot 2020-05-14 at 1.55.38 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c82e2a36-f9ab-4137-829e-c5db6ff542b1)

**Comment by nikdragovic** [comment]
We are going to revert this back to default display, since the result in the ticket description could not be achieved due to the element structure. Examples below.
![Screen Shot 2020-05-15 at 7.37.40 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f29d6826-c697-4432-bb20-c6abe9c91692)![Screen Shot 2020-05-15 at 7.38.44 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/256fbbf5-8acc-4555-825d-d125aa0dba2a)
