### ISSUE TITLE
Search Results Page - Change highlight color on active facet 

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#574]
## Acceptance Criteria 
- [ ] Replace green colors (#28A745) with Emory Blue (#082B73)
- [ ] Text overlaying Emory Blue should be white (#FFFFFF) for accessibility

**Current:**
![Screen Shot 2020-05-05 at 3.02.18 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/3874b082-98b5-47f2-b3f6-5963bd85e9d2)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-13 at 8.56.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/cb44178b-5da9-4fff-81c3-5d8adbfdfde5)

PR made: https://github.com/emory-libraries/dlp-lux/pull/596
