### ISSUE TITLE
Search Results Page - Change text color of "Limit your search"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#575]
## Acceptance Criteria 
- [ ] Desired color is #082B73

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/594

![Screen Shot 2020-05-12 at 11.33.16 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3d5ac518-86fc-4092-a3e2-b6bf692f1219)
