### ISSUE TITLE
Search Results Page - Align "Limit your search" to search result pagination and sort options

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#577]
## Acceptance Criteria 
- [ ] Alignment is as shown in mockup

**Current:**
![Screen Shot 2020-05-05 at 3.18.20 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/17bf8243-1300-4794-857f-317ce5c6ff12)
**Desired:**
![Revised search results.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/0ace78c0-ae47-431d-b38e-1cce83781392)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/597

![Screen Shot 2020-05-13 at 9.39.19 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3aa58304-d85e-4032-9a4c-30b28dd99770)
