### ISSUE TITLE
Search Results Page- Align search result pagination and sort options at mobile size

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#578]
## Acceptance Criteria 
- [ ] Alignment is as shown in mockup
- [ ] Move hamburger menu to right of Limit your search

**Current:**
![Screen Shot 2020-05-05 at 3.28.18 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/eed747b3-fc61-4146-8b1e-650c5f1da5b0)
**Desired:**
![Screen Shot 2020-05-05 at 3.28.18 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/df7d0e95-e872-4bba-8fca-a7c03fc91c70)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/598

![Screen Shot 2020-05-13 at 1.18.20 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ded13b06-0305-435f-a8de-3032eac587c2)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-13 at 1.17.59 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/cb1a1336-6bad-40b4-a5a9-4f2d3e03b936)

**Comment by nikdragovic** [comment]
Looks slightly odd here before the button size collapses, but I doubt this is a standard screen size, so I'm not concerned.

![Screen Shot 2020-05-14 at 2.56.55 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4f35e6d2-23d8-4345-977c-b2bf2097225b)
