### ISSUE TITLE
Collection Page - add padding below hero

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#579]
## Acceptance Criteria
- [ ] Add equivalent padding/margin below the collection image, consistent with how the View work page displays (approx 33 px).

**Current:**
![Screen Shot 2020-04-30 at 4.14.01 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e2f64204-d313-45f0-9f38-eff765fcc153)

**Desired (approx 33 px):**
![Screen Shot 2020-03-30 at 2.40.45 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/9c16623c-8b13-439d-bed1-a7f0eed40f44)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/605

![Screen Shot 2020-05-19 at 8.40.35 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/16cccf81-e65c-41bb-89f3-21ec3d116194)

**Comment by nikdragovic** [comment]
@bwatson78 I have tested this and accept for prod deploy.
