### ISSUE TITLE
All team members verify they can deploy the code 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#58]
Specifically for Emory servers 

- [x] Mark B.
- [x] Bess
- [x] Solomon
- [x] Jamie
- [x] Max
- [x] Will
- [x] Mark P.

**Comment by rotated8** [comment]
To deploy, first run `tki` and receive your 12-hour AWS credentials.
Then, run the following command:
`BRANCH=<tag> bundle exec cap <env> deploy`
where <tag> is either a version, like v0.4.32, and
where <env> is one of "production", "test", or "arch".

**Comment by mark-dce** [comment]
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/068cf551-15c0-49a7-affc-53d88e5d94be)

**Comment by mprefer** [comment]
Received this error when Capistrano deploys Honeybadger:

  01 No value provided for required options '--api-key'
    ✘ 01 deploy@10.65.89.10 2.862s
