### ISSUE TITLE
Collection/Work pages - Add spacing between logo, breadcrumbs, pagination, and Start Over/Back to search buttons

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#580]
## Acceptance Criteria
- [ ] Add padding as displayed in screenshot; consult PO via screenshare if needed for consult on pixel dimensions.

**Current:**
![Screen Shot 2020-04-17 at 4.44.10 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e1c6a0b3-c866-4266-8f28-f910a85390cf)

**Desired:**
![Screen Shot 2020-04-17 at 4.43.26 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/dba551d4-c958-4d7b-be21-ae7357f68271)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/599

![Screen Shot 2020-05-14 at 8.07.40 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c6d4dba2-5fe4-4535-9f97-ee83c4c9668c)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-14 at 7.51.52 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6cb53019-e899-4cce-8576-5495474cf302)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-14 at 8.40.57 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/02fa925d-06be-4794-a53f-45464aa00b9a)

**Comment by bwatson78** [comment]
@nikdragovic Can you look at my last two screenshots and let me know if any changes need to occur?
