### ISSUE TITLE
Collection page - Change "Find this Item" heading to "Find this Collection"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#581]
## Acceptance Criteria
- [ ] Change "Find this Item" heading to "Find this Collection"

**Current:**
![Screen Shot 2020-05-05 at 3.39.30 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/bb0fded2-6a72-4794-8412-64e0cc9d4a78)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-19 at 8.43.43 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8770fec1-20bb-4bca-8b32-39d877b517e6)

PR made:https://github.com/emory-libraries/dlp-lux/pull/603

**Comment by nikdragovic** [comment]
@devanshu-m @bwatson78 I have tested this and accept for prod deploy.
