### ISSUE TITLE
Collection/Work pages - Dates should be on separate lines

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#583]
## Acceptance Criteria
- [ ] For fields with multiple date values, enter a line break after each date value.

**Current:**
![Screen Shot 2020-05-05 at 3.54.49 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/58d73774-f119-4688-9a08-0c98113337fe)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/604

![Screen Shot 2020-05-19 at 8.13.16 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/eb21fd1e-a5b2-4b99-8b43-f80cf97645ea)

**Comment by nikdragovic** [comment]
@bwatson78 I have tested this and accept for prod deploy.
