### ISSUE TITLE
Collection/Work pages - Titles should be left-aligned

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#584]
## Acceptance Criteria
- [ ] Title text is left-aligned (including overflow lines)

**Current:**
![Screen Shot 2020-05-05 at 3.51.13 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/22fde284-1b52-45cb-9d7d-66cfbaf79c14)

**Desired:**
![Screen Shot 2020-05-05 at 3.52.04 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/30d4265a-49c0-4923-9151-90727460d3ae)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-14 at 9.08.53 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d03eba90-388d-4bc4-a64e-1c49521c9acd)

PR made: https://github.com/emory-libraries/dlp-lux/pull/600
