### ISSUE TITLE
Static Pages - Explore box should top-align with first heading 2

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#585]
## Acceptance Criteria
- [ ] Explore box should top-align with first h2

**Current:**
![Screen Shot 2020-04-30 at 4.10.27 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/658d86ec-a08d-481a-8dad-c74b4f86b3ed)

**Desired:**
![Screen Shot 2020-04-30 at 4.08.24 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/17359e12-91ae-4e6d-bfa1-2ddba72233a1)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-19 at 9.09.34 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/07923dff-ce0f-4967-9f8c-5f0ea554f778)

PR made: https://github.com/emory-libraries/dlp-lux/pull/606

**Comment by nikdragovic** [comment]
@bwatson78 I have tested this and accept for prod deploy.
