### ISSUE TITLE
Static Pages - Change font size of h2 styles

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#586]
## Acceptance Criteria
- [ ] 48px should be size for h2 [(Such as on Libraries site)
](https://libraries.emory.edu/materials/books.html)
**Current:**
![Screen Shot 2020-05-05 at 3.48.33 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f47c1a71-facf-4d77-af89-ae8ca455e678)

**Desired:**
![Screen Shot 2020-05-05 at 3.48.22 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/87928766-130a-4877-8610-0c0ae4f75a41)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/607
![Screen Shot 2020-05-19 at 9.37.52 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d77ae7ff-885b-4de4-b920-a9b7a8f5e87a)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-19 at 9.37.40 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/626c15e7-b980-404d-8f09-6aae51a9bd45)

**Comment by nikdragovic** [comment]
@bwatson78 I have tested this and accept for prod deploy.
