### ISSUE TITLE
Adjust line height for h1 styles

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#587]
## Acceptance Criteria
- [ ] Reduce line height for h1s across the application to improve display of multi-line titles (from computed: 65px; to computed: 50-55px). 

**Current:**
![Screen Shot 2020-04-20 at 10.01.52 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/10e27e27-d4b4-434a-a137-4ac9b9b12c65)

**Desired:**
![Screen Shot 2020-04-20 at 10.00.48 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/2e275d1a-0fd7-432e-8150-333c89c3d03f)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-19 at 12.32.55 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6a3500e3-dc31-41c7-9698-cda60c5d076a)

PR made: https://github.com/emory-libraries/dlp-lux/pull/609

**Comment by nikdragovic** [comment]
@bwatson78 I have tested this and accept for prod deploy.
