### ISSUE TITLE
Collection/Work pages - Change mobile layout

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#588]
Adjust breakpoints so that single-column view is (top to bottom): 
This item is part of, 
About This Item, 
Tools, 
Subjects / Keywords, 
Find This Item, 
Access and Copyright. 

Collection pages do not have some of these groupings, so those groupings will be excluded.

**Comment by nikdragovic** [comment]
@bwatson78 I seem to be getting the previous order for the single-column view. Can you check these and let me know what you see?

https://digital-test.library.emory.edu/catalog/4300zpc8g1-cor

https://digital-test.library.emory.edu/catalog/706g1jwt47-cor

https://digital-test.library.emory.edu/catalog/5977sqvb35-cor

https://digital-test.library.emory.edu/catalog/3074tmpgdn-cor

https://digital-test.library.emory.edu/catalog/119f4qrfn2-cor

**Comment by bwatson78** [comment]
@nikdragovic Looking at the code now.

**Comment by bwatson78** [comment]
The changes didn't come over in the release. Talking with Collin.
