### ISSUE TITLE
Add Universal Viewer to show page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#61]
## Story
As an end user, I want to use the Universal Viewer on the work show page, so that I can interact with the content directly in the digital library interface.

## Acceptance Criteria
- [x] If test images do not load within five seconds upon first viewing, create an issue to address performance in dlp-curate.
- [x] Images are cached after first viewing for loading within two seconds upon subsequent viewings (if not, create an issue to address performance in dlp-curate).
- [x] Images are delivered via Cantaloupe server.
- [x] Viewer resembles Curate
- [x] Add IIIF_MANIFEST_URL environment var to Lux inventory

## Wireframe
[https://app.zenhub.com/files/172767026/e47c900a-582d-4ae8-ab80-67101a988003/download](https://app.zenhub.com/files/172767026/e47c900a-582d-4ae8-ab80-67101a988003/download)

**Comment by bess** [comment]
@little9 and @maxkadel Here is an emory cantaloupe URL: https://iiif-cor-arch.library.emory.edu/cantaloupe/iiif/2/8f93a0be3eee62032cfc8df81072e1bc43c85975/full/90,/0/default.jpg

Images are being fetched by SHA1, which can be found in the solr index for a given FileSet. Ask me or @SolomonHD or @rotated8 if you aren't finding the info you need to make this work.

**Comment by little9** [comment]
Here's an example using the test data: 

https://lux-qa.curationexperts.com/catalog/5977sqv9sm-cor

**Comment by SolomonHD** [comment]
I've added the proper env vars to cor-cm:

https://github.com/emory-libraries/cor-cm/commit/5d46f598413145a7fff0358ab52e2f94602185c4#diff-7f824d3e4991559b29eb5c16c62aec41

**Comment by little9** [comment]
<img width="960" alt="Screen Shot 2019-12-06 at 9 36 53 AM" src="https://user-images.githubusercontent.com/4324761/70335626-43d69800-180d-11ea-978f-6eb2ccf04858.png">

Can be seen at https://digital-arch.library.emory.edu/catalog/542n5tb2sx-cor
