### ISSUE TITLE
Implement search result preview metadata

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#62]
## Story
As an End User, I want to preview the details of a repository resource to determine its appropriateness for my research, so that I know whether or not to download/view the material in greater detail.

## Acceptance Criteria
- [x] Title, creator, date created, and item type fields are implemented (as shown in wireframe).
- [x] Fields referenced above are populated with values.
- [x] Metadata is correctly mapped and verified for test objects.

## References
[Updated Wireframe](https://app.zenhub.com/files/172767026/8d5dcc89-97a8-4c92-a1cb-99565e8e42f9/download)
[Original Wireframe](https://app.zenhub.com/files/172767026/29072ff4-fc4c-438f-9290-95d1b90ba30c/download)

**Comment by bess** [comment]
![search_results_with_thumbnails.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/0d526c39-17b3-44f0-b8db-c1fc270fea78)

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/70447662-1a1bac00-1a6d-11ea-8689-30af18630c26.png)

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/70466274-c1f6a100-1a90-11ea-80e7-aed93446fbc2.png)
