### ISSUE TITLE
Add meta description tag to Lux homepage

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#621]
We need to add a meta description to Lux in order to provide a helpful snippet of explanatory text for users who find it via search engine. It will also help with SEO in these search engines.

Acceptance Criteria
- [ ] The following text should be applied to the homepage HTML (one possible version shown; edits to structure are at developer discretion).

`<meta content="The digital front door to the unique cultural heritage and scholarship material from Emory Libraries. Discover, view, and download images, books, and more from our campus repositories." name="description"/>`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/622

![Screen Shot 2020-06-18 at 2.42.26 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/35cdc16f-ab5a-4eac-9898-e5059669dd2f)

**Comment by nikdragovic** [comment]
@bwatson78 Tested, thanks!
