### ISSUE TITLE
Adjust display of search result items

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#626]
## Acceptance Criteria
- [x] Search results resemble mockups (ranking number is above title, titles are left-aligned, and thumbnails have consistent width.

![Screen Shot 2020-06-29 at 4.00.43 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/0511f4bb-d922-4cbf-a4c0-d0fab62f4b5b)![Screen Shot 2020-06-29 at 4.01.00 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f7559ad9-8e4f-4617-82c2-2de8559817a6)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/639

**Comment by bwatson78** [comment]
Desktop view: 
![Screen Shot 2020-07-10 at 9.54.29 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/39333e34-bdd8-4464-96bc-e65831c943aa)

Mobile view (Work):
![Screen Shot 2020-07-10 at 9.55.06 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/176c59f0-959a-43e7-965e-12a82bf8f0a9)

Mobile view (Collection):
![Screen Shot 2020-07-10 at 9.55.17 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ef6aa993-7975-4440-810f-a62be7944c36)
