### ISSUE TITLE
Add text to History page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#627]
Users should be better informed that search history is not retained after the conclusion of a browser session.

## Acceptance Criteria
- [x] Existing "Your recent searches" text should read "Your recent searches (cleared after your browser session)"

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/635

![Screen Shot 2020-07-08 at 4.00.28 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7d7f621f-73b9-4452-a82b-467dc2d0fd47)
