### ISSUE TITLE
Embed additional browse links on homepage

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#629]
## Acceptance Criteria
- [x] When a user clicks "Browse All Items," they are taken to a search result list of all available items in the repository (https://digital.library.emory.edu/?utf8=%E2%9C%93&search_field=common_fields&q=)
- [x] When a user clicks "Explore Our Collections," they are taken to a search result list of all collection pages in the repository. (Query TBD)
- [x] Hover behavior should mirror titles of featured collections (color change to accessible blue).

**Comment by tmiles2** [comment]
Pending further discussion in Monday's PO meeting.
