### ISSUE TITLE
Implement thumbnail previews on search results page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#63]
## Acceptance Criteria
- [x] Default image is primary/first image for multi-part objects
- [x] If no object images are present, placeholder from Curate/Hyrax appears
- [x] Thumbnails in a series of results are of uniform width

## References
[Updated Wireframe](https://app.zenhub.com/files/172767026/e7e2fdd5-38a3-4d59-8e66-1c0caa75229f/download)
[Original Wireframe](https://app.zenhub.com/files/172767026/c7b88abf-750b-4d1e-86ff-70d5006aeeb0/download)

**Comment by maxkadel** [comment]
This is effecting the view of the metadata as well, so I'm helping with this one.

**Comment by bess** [comment]
![search_results_with_thumbnails.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/804fe3e7-b77d-4318-8752-810e4a860bb3)

**Comment by maxkadel** [comment]
Thumbnails now appearing on digital-arch. 

![image](https://user-images.githubusercontent.com/45948126/70460848-3f1c1900-1a85-11ea-891b-e391f4fad4d6.png)
