### ISSUE TITLE
Change header links in logo

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#633]
Based on user testing, linking pattern should be adjusted to conform to Libraries website / pattern library.

## Acceptance Criteria
- [x] Shield icon links to Home (digital.library.emory.edu)
- [x] "Emory University" links to emory.edu
- [x] "Emory Libraries" links to libraries.emory.edu

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/640

![Screen Shot 2020-07-10 at 11.20.16 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a91bede5-4c1a-495d-b277-19057c17b607)
