### ISSUE TITLE
Configure Universal Viewer (time boxed @3pts)

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#65]
## Story 
As a Repository Administrator, I want to display a set of configured features in the Universal Viewer, so that users are able to maximize their inspection, interaction, and navigation of objects.

## Description
Extend the functionality of the image viewer experience presently in Curate by configuring additional standard Universal Viewer options.

## References
[Wireframe](https://app.zenhub.com/files/172767026/c21772e7-a07f-41ed-bc91-83072206ec29/download)

[Curate Link] (https://curate.library.emory.edu/concern/curate_generic_works/863fxpnvz1-cor?locale=en)

![Curate Image View.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/8cdca621-0379-4c1e-9554-a918e7d777ee)

[UV Examples] (http://universalviewer.io/examples)
-Target example: Cats
![Added Features Illustration.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b20f68ce-b1cd-4c7b-b82e-28249c80c764)

## Features 
**To retain:**
Object title (top)
Navigation arrows (right and left)
Zoom, rotate, information, download, and share icons (bottom)

**To remove:**
Duplicate zoom and rotate on hover

**To add:**
Thumbnail viewer (left side)
Object navigation arrows  (top)
Navigation box with numeric entry (top)
View toggle to fill viewer with thumbnails (top right)
Fullscreen toggle (bottom right)
Reference thumbnail for zoomed object (bottom right)

## Acceptance Criteria
All primary files appear in thumbnail viewer in the correct order
Supplemental files do not appear in thumbnail viewer
Thumbnail pane is expanded by default
Download in Universal Viewer allows for the download of primary and supplemental files, but not preservation files.
Zoom, rotate, and object navigation functions on mobile

## Out of Scope
Paged PDF viewer for book objects (for future sprint)

**Comment by little9** [comment]
Based on the pairing session today: 

To retain:
Object title (top) ✔️ 
Navigation arrows (right and left) **(will be there on mobile view)**
Zoom, rotate, information, download, and share icons (bottom) **Zoom buttons are on the upper left in desktop view** ✔️ 

To remove:
Duplicate zoom and rotate on hover **Duplicate zoom is gone on desktop view, it's the hover one by default. Mobile will not be able to hover and has the buttons in the toolbar.**

To add:
Thumbnail viewer (left side) **Only displays in desktop mode**
Object navigation arrows (top) **Display in desktop mode**
Navigation box with numeric entry (top) **Only displays in desktop mode**
View toggle to fill viewer with thumbnails (top right) **Only displays in desktop mode when the resource has multiple items**
Fullscreen toggle (bottom right) ✔️
Reference thumbnail for zoomed object (bottom right)  **Only displays in fullscreen desktop mode, displays again after leaving fullscreen**

**Comment by little9** [comment]
<img width="960" alt="Screen Shot 2019-12-06 at 3 32 46 PM" src="https://user-images.githubusercontent.com/4324761/70358423-ed824d00-183e-11ea-958e-edb0cfe0ff8b.png">
<img width="960" alt="Screen Shot 2019-12-06 at 3 40 59 PM" src="https://user-images.githubusercontent.com/4324761/70358424-ee1ae380-183e-11ea-97a7-89726ebfecaf.png">
