### ISSUE TITLE
Change color of global breadcrumb element

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#652]
The current color of the breadcrumbs is not AA accessible at small text sizes. We need to change it to optimize contrast for accessibility. 

## Acceptance Criteria
- [ ] Change all breadcrumb text from #5387F7 to #336B36

## Color Guide
![Screen Shot 2020-07-22 at 9.10.15 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/e6620dd2-ab68-4ada-9cd5-8d83cd2a8c57)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/662

**Comment by bwatson78** [comment]
![Screen Shot 2020-07-22 at 2.29.37 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/af2d0fa1-c9c8-4fb3-b57b-146b5ae68c25)
