### ISSUE TITLE
Add a link title to the shield logo in the footer

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#654]
For optimal accessibility, we should title the footer link as "Emory Libraries." This is in place for the logo in the header.

## Acceptance Criteria
- [x] Link displays title

![Screen Shot 2020-07-22 at 9.26.03 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/dea39b0f-f881-47cd-9597-439b39d6a5be)
![Screen Shot 2020-07-22 at 9.25.56 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/fa4129d9-6516-4e32-bc39-f78607b66cf6)

**Comment by bwatson78** [comment]
PR to review: https://github.com/emory-libraries/dlp-lux/pull/661

**Comment by bwatson78** [comment]
![Screen Shot 2020-07-22 at 12.10.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b69d11b9-677d-4cee-86fa-faf820b599c4)
