### ISSUE TITLE
Add alt text to collection hero images

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#659]
## Acceptance Criteria 
- [ ] Add generic "collection feature image" alt text 
- [ ] OR Add title of each feature image as alt text

![Screen Shot 2020-07-22 at 9.46.56 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/4506da86-8d9a-43de-8c12-9330fa0481f8)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/670

**Comment by bwatson78** [comment]
![Screen Shot 2020-07-27 at 11.49.08 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/9c976a60-4044-4f80-9b5d-0ff9cf1b5c80)

**Comment by nikdragovic** [comment]
@bwatson78 I don't seem to be able to load collection heros in test:

https://digital-test.library.emory.edu/catalog/914nk98sfv-cor

https://digital-test.library.emory.edu/catalog/5053ffbg7n-cor

https://digital-test.library.emory.edu/catalog/914nk98sfv-cor

**Comment by bwatson78** [comment]
@nikdragovic Looking into this.

**Comment by bwatson78** [comment]
@nikdragovic First finding is that the `banner_path_ss` solr field is wrong. My code didn't touch any manipulation of solr fields, so I'm digging deeper.

**Comment by nikdragovic** [comment]
@bwatson78 Quick add - collection objects in arch have working heros, except for Langmuir.

https://digital-arch.library.emory.edu/catalog/699n2z34v3-cor

https://digital-arch.library.emory.edu/catalog/105s7h44j3-cor

**Comment by bwatson78** [comment]
@nikdragovic Lux doesn't manipulate anything related to the `banner_path_ss` field when it comes in from Curate. I'm now looking at the Curate code.

**Comment by bwatson78** [comment]
@nikdragovic I believe there may have been a transferring of objects from test to arch recently. For example, the path to the collection banner image in Arch for Langmuir is "/mnt/test_efs/uploads/dlp-curate/branding/699n2z34v3-cor/banner/40644j0ztx-cor.jpg". The code that properly formats the path is expecting to scrub "/mnt/arch_efs/uploads/dlp-curate". I think the location of the banner was imported directly from test without manipulation. I think this is a problem we've had in the past, but I'm not sure the fix. Reindexing?
