### ISSUE TITLE
User-friendly display of dates for search result preview

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#67]
## Story
As an End User, I want to view dates in a format that is intuitive, so that I don't have to interpret character sets in shorthand or associated with machine encoding.

## Acceptance Criteria
- [x] "XXXX" for Date Created in [Curate](https://curate.library.emory.edu/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=Hindu+temples+are+among+the+interesting+attractions+of+Port+of+Spain%2C+Trinidad) displays "unknown" in Date Created for Lux.
- [x] "193?" for Date Created in Curate shows as "1930s" in Date Created for Lux.
- [x] "1934?" for Date Created in Curate "1934 approx." for Date Created in Lux.

## References
https://www.loc.gov/standards/datetime/edtf.html

## Notes
Related stories will specify this behavior for dates on the show page, results filter, and advanced search

**Comment by maxkadel** [comment]
Assumption - all the dates we are presenting are 1000 CE or after.
