### ISSUE TITLE
Collection page hero images not loading in digital-test

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#672]
No collection page hero images are loading in digital-test. Examples here:

https://digital-test.library.emory.edu/catalog/914nk98sfv-cor

https://digital-test.library.emory.edu/catalog/5053ffbg7n-cor

https://digital-test.library.emory.edu/catalog/914nk98sfv-cor

Images *are* loading in arch, with the exception of Langmuir:

https://digital-arch.library.emory.edu/catalog/699n2z34v3-cor

https://digital-arch.library.emory.edu/catalog/105s7h44j3-cor

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1365

**Comment by bwatson78** [comment]
Each collection with the hero not loading will need to be reindexed.
