### ISSUE TITLE
Header display breaks when clicking Back from Advanced Search

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#673]
In arch, test, and prod, the header styling has a bug that presents when clicking Back from Advanced Search. It resembles what we resolved in #632.

![Screen Shot 2020-07-28 at 2.41.07 PM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/def84af7-1266-4a59-8e41-55a1214a18e6)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/683

**Comment by bwatson78** [comment]
No screenshots to provide.

**Comment by eporter23** [comment]
Tried to recreate the bug a few times, did not see it. Looks good in test.
