### ISSUE TITLE
Update hero images on homepage carousel

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#674]
For fall 2020:

## Acceptance Criteria
- [ ] Add new Yellowbacks hero image with a link to the Collection page: 

- https://digital.library.emory.edu/catalog/706g1jwsv6-cor
- image: https://emory.app.box.com/file/633773812176
- alt text: Chester W. Topp collection of Victorian yellowbacks and paperbacks

- [ ] Add new health sciences item to carousel selection and link to 

- https://digital.library.emory.edu/catalog/006sxksn5r-cor
- image: https://emory.app.box.com/file/725909752115
- alt text: 11 piece surgical instrument kit owned by Dr. Clarence Arthur Earle

- [ ] Remove health sciences item 160cvdncr2-cor from carousel selection (medication bottles)

Note: a separate ticket will be submitted to add Yearbooks to the carousel once those are completed.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/695

MOV video shared with @eporter23 via slack.

**Comment by eporter23** [comment]
Looks great, thanks @bwatson78 !
