### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#676]
We are adding a section to the About page with an accessibility statement.

## Acceptance Criteria
- [x] Text updated according to Google document.

## Wireframe
- [ ]  [Content and style](https://docs.google.com/document/d/1cYOKpPyRBHXpcY2YkZeGYNCmwmZDS_3vLSEUk3n27Co/edit?usp=sharing)

**Comment by eporter23** [comment]
Looks good, thanks!
