### ISSUE TITLE
Display source collection relationship in Lux - View Work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#680]
See [wireframe - sections 1, 2](https://docs.google.com/drawings/d/1wISDQmRHzYIr-PFBlK0K0wad5wdpycUYvJAraRxN01k/edit)

- [x] Updates links in breadcrumbs
- [x] Updates link and collection title in This Item Is Part Of

**Comment by eporter23** [comment]
Noting a dependency - we should not deploy this to Lux production until we have added the source collection ID to all existing works.

**Comment by lovinscari** [comment]
Move to next sprint to accommodate all testing and merging activities.

**Comment by eporter23** [comment]
Looks great! I was also able to confirm that *only* source collection links are used on the View Item page because we had one work in test with a Deposit Collection ID accidentally assigned as a Source Collection, and the link redirected to an error page. I fixed the work in test.

**Comment by eporter23** [comment]
Looks great in production!
