### ISSUE TITLE
Adjust Lux Collections facet to show Source Collection only

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#684]
See[ wireframe ](https://docs.google.com/drawings/d/1YgdgM42JQFSYC_0DbljJllgfczUTMIiM5biolUxI4p8/edit)section 1.

Update the Lux Collections facet to return works grouped by their source_collection_id only.

**NOTE:** we need to wait to deploy these changes to Lux **production** until we've added the source collection ID to all works in production. This is nearly done as of 9/17/20.

**Comment by devanshu-m** [comment]
Did not realize this is blocked. Putting it back in queued

**Comment by eporter23** [comment]
@devanshu-m the work isn't blocked. We just need to make sure we wait to deploy these changes to Lux prod until after we have updated all the source collection MD in prod, which is nearly done.

**Comment by devanshu-m** [comment]
@eporter23 sounds good. Will pick it back up after my current ticket. Thank you!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/687

![Screen Shot 2020-09-21 at 11.41.26 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f8f42e12-f1bd-47b6-b47e-eaf83e27af7c)

**Comment by lovinscari** [comment]
Devanshu will look at this after sprint review.

**Comment by eporter23** [comment]
Looks great! There is a Deposit Collection showing up temporarily but that's because of an incorrect assignment on a single work in test. Fixing that now, and the solr synch will correct it.

**Comment by eporter23** [comment]
Looks great in production!
