### ISSUE TITLE
<span> tags showing up in Facet popups

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#685]
Facets that have a "More" option show an exposed <span> tag at the top and bottom of the facet popup:

![Screen Shot 2020-09-17 at 9.28.52 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d463602d-f207-41eb-8ee6-cda11ebbba8e)

![Screen Shot 2020-09-17 at 8.41.18 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/00bd8a73-1e1f-4991-a932-8d971c6fcdc8)

**Comment by bwatson78** [comment]
![Screen Shot 2020-09-25 at 11.10.30 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/86f97e19-847e-489e-85e5-888f5dfa0ad3)

**Comment by eporter23** [comment]
Looks great - thanks!

**Comment by eporter23** [comment]
Span tags no more!
