### ISSUE TITLE
Adjust Lux Explore Our Collections behavior to list Source Collections only

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#686]
See [wireframe](https://docs.google.com/drawings/d/1YgdgM42JQFSYC_0DbljJllgfczUTMIiM5biolUxI4p8/edit) section 2.

The [Explore Our Collections link](https://digital.library.emory.edu/?f%5Bhas_model_ssim%5D%5B%5D=Collection), accessible from the homepage, should return:

- [ ] A list of Source Collections only (Deposit Collections should not display)
- [x] And/or - do not show Collections whose Visibility is Private (this would automatically exclude Deposit Collections)

Screenshot of current output (which is what we want to replicate)

![Screen Shot 2020-09-18 at 9.40.54 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e015983e-03a4-4530-a744-b0cd06898b38)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1508

![Screen Shot 2020-09-24 at 8.28.43 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/92f7c1d3-cbac-4ba7-bee9-c6b015f0224b)

**Comment by eporter23** [comment]
Changes look good in test.

**Comment by eporter23** [comment]
Looks good, thanks!
