### ISSUE TITLE
Hero carousel at home disappears when removing a Collection filter from search results

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#690]
Tested in Mac Safari 13.1.2. This has been occurring intermittently.

**To reproduce:**

Start at homepage

Select a Collection from the Collections facet

View search results

Remove Collection filter by clicking on the limiter in the top of the screen
![Screen Shot 2020-09-24 at 4.08.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0654e92a-df90-4a5f-8cb9-912580b4a16b)

Get returned to homepage with no hero carousel displayed

![Screen Shot 2020-09-24 at 4.01.48 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0c6e817a-cdb7-4083-b8e2-985b465f60ba)

**Comment by bwatson78** [comment]
@eporter23 I cannot reproduce this error. Is it possible that it was fixed inadvertently in-between the ticket creation and now?

**Comment by eporter23** [comment]
@bwatson78 it has been intermittent, so this is not a huge priority. I am not seeing today, either. I'll close this and reopen it again later if I see it regularly.
