### ISSUE TITLE
Lux: items query/count in Collection views should retrieve all works within Source Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#693]
When browsing a collection from the Explore Collections page, the count shows 12,252 (should be 12,664 as shown in the facet). We should use source_collection_id instead of member of collections.

![Screen Shot 2020-10-06 at 9.50.40 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0a7ebac5-3bc4-4d2b-a985-2e3cb20623c3)

The View Items in Digital Collection link also returns a set of 12,252 instead of 12,664: the query should use source_collection instead of member of collections.

![Screen Shot 2020-10-06 at 9.54.00 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ac7c3049-f46a-4c1a-8d1b-0fab5d482cd4)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/694

![Screen Shot 2020-10-07 at 10.48.46 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/eae69307-5492-411d-8270-90b2bd4ed7c2)

**Comment by eporter23** [comment]
@bwatson78 looks good, the count of returned works from the View Items in This Digital Collection is just a couple of works off in test but I'm sure that's an unrelated indexing issue. 

Question: there is a separate part of this ticket which is about showing the correct count (using source collection instead of member of collection) on the Explore Collections page. Should I write that up separately and re-submit? 

![Screen Shot 2020-10-09 at 2.58.00 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/340e95c5-c5f3-4487-a24e-2091d59dedfd)

**Comment by bwatson78** [comment]
@eporter23 
Apologies for that--misinterpreted the ticket. Working on that now.

**Comment by eporter23** [comment]
@bwatson78 this seems to be working. After reindexing the collections, the Langmuir count is now 12,668 which is much more accurate. It should be 12,664 but it's possible there are some duplicates somewhere. This will be easier to test in production where the data is in better shape. Thanks!

**Comment by eporter23** [comment]
@bwatson78 I think this has been deployed to both Lux and Curate, correct? I am still seeing the incorrect count for Langmuir in the Explore Our Collections list in Lux prod. I updated the Langmuir collection on 10/16 in order to reindex it, but are additional steps needed? I also looked in SOLR and this is what I see.

![Screen Shot 2020-10-22 at 10.42.50 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a527488c-f1d6-4687-8679-42a8e1fa71b2)

![Screen Shot 2020-10-22 at 10.41.02 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6f6072e6-9cff-4dc8-99fb-119860e0f645)

![Screen Shot 2020-10-22 at 10.40.55 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/785b45b3-830d-482c-a3cf-610f4fb3277f)

**Comment by bwatson78** [comment]
@eporter23 I will dig into this now, but when you get online, would you ok me to perform a direct reindex on the collection?

**Comment by bwatson78** [comment]
@eporter23 I've confirmed that the count will be updated when a new reindex is performed.
<img width="774" alt="Screen Shot 2020-10-26 at 6 16 29 AM" src="https://user-images.githubusercontent.com/18330149/97160479-cda79080-1752-11eb-8c59-c78916aba4c8.png">

**Comment by eporter23** [comment]
Thanks @bwatson78 that will be fine, please let me know how it goes. Also, for Langmuir because it is so large it will take several hours to complete.

**Comment by eporter23** [comment]
All showing up now. Thanks.
