### ISSUE TITLE
Adjust Google Analytics "collection" Event Tracking to use Source Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#696]
The Langmuir Deposit Collection title is showing up in Analytics results, which indicates our Collection event tracking is using the deposit collection relationship instead of source collection relationship.

![Screen Shot 2020-11-11 at 12.44.40 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/2c8f0daa-e93b-4753-93cd-7259ba8ad5d2)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/697

**Comment by eporter23** [comment]
I tested this in digital-test using real time analytics, viewing several works in the Langmuir Deposit Collection. The works now show up in the analytics event under the Source Collection's title (Robert Langmuir African American Photograph Collection). 

![Screen Shot 2020-12-09 at 1.51.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/fbc37617-83f7-455c-a755-3ba0b6c17638)

**Comment by eporter23** [comment]
Confirmed in prod as well.
