### ISSUE TITLE
View items in this digital collection link disappears on mobile/small views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#698]
Reported by Katherine Fisher, Rose Library:

> I noticed that when I view a collection landing page (like this one: https://digital.library.emory.edu/catalog/535t76hf5f-cor) in a small browser window or on mobile, causing the sections of the page to stack vertically, the one containing the "View items in this digital collection" link disappears.

To reproduce:
1 - open a Collection landing page, example: https://digital.library.emory.edu/catalog/535t76hf5f-cor
2 - reduce the browser window to less than 900 px wide
3 - link to view items disappears

**Comment by bwatson78** [comment]
@eporter23 Does the following require any further CSS adjustment?

![Screen Shot 2020-11-25 at 12.56.55 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/07afe32f-48c3-4ac2-9267-fa3d2be291ad)

**Comment by eporter23** [comment]
@bwatson78 that looks good, thank you!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/697
