### ISSUE TITLE
Update Lux "About Us" page text

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#708]
We should update the static content on the About Emory Digital Collections page to remove references to Phase 1/pilot status.

Current output:

> Collections & Content
> 
> The Emory Libraries’ holdings include hundreds of digital collections and millions of digital assets in queue to be made available through our new Emory Digital Collections site. Our first phase of ingest includes 4 collections containing over 12,000 digital objects. We will load new content on an ongoing basis, and our repository roadmap includes expanding support for additional types of material.

Desired output:

Collections & Content

The Emory Libraries’ holdings include hundreds of digital collections and millions of digital assets in queue to be made available through our Emory Digital Collections site. We load new content on an ongoing basis, and our repository roadmap includes expanding support for additional types of material.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/709

![Screen Shot 2022-02-22 at 11.47.50 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/864e93c2-96b4-423c-84c3-a2d4a8895639)

**Comment by eporter23** [comment]
Looks good!
