### ISSUE TITLE
Update links to DLP wiki when Confluence migrates

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#743]
When the LTDS confluence spaces migrate, we will need to update links on our static pages to point to the new locations.

**About page**
https://digital.library.emory.edu/about

- [x] Explore box link: update to https://emorylib.atlassian.net/wiki/spaces/DLPP/overview
- [x] Questions, Help and Feedback section link: update to https://emorylib.atlassian.net/wiki/spaces/DLPP/pages/20578892/Emory+Digital+Collections+User+Guide

**Contact page**
https://digital.library.emory.edu/contact

- [x] Send Feedback section link: update wiki link to point to https://emorylib.atlassian.net/wiki/spaces/DLPP/pages/20578892/Emory+Digital+Collections+User+Guide

**Comment by eporter23** [comment]
Thanks for catching that! Here is the new wiki link: https://emorylib.atlassian.net/wiki/spaces/DLPP/pages/20579085/Digital+Preservation+Policies

**Comment by bwatson78** [comment]
Just wanted to cover all bases. It looks like we have more links in the repo with that domain. We have this in the Reading Room Not Found static page:
`Some items may no longer be available from the providing library. Refer to the contact information for each digital collection or consult our <a href='/contact' class='static-blurb-link'>Contact</a> page</li><li>Additional information is available within our user guide at <a href='https://wiki.service.emory.edu/display/DLPP/Emory+Digital+Collections+User+Guide' class='static-blurb-link'>our wiki site</a>.`
I'll replace that.

I'm guessing that the following link in this span should be https://emorylib.atlassian.net/wiki/spaces/DLPP/overview ?
`A key offering of the <a href='https://wiki.service.emory.edu/display/DLPP/Digital+Library+Program+Project+Home' class='static-blurb-link'>Digital Library Program (DLP)</a>, a multi-year Emory Libraries strategic initiative to promote best practices and provide long term access to Emory's unique digital assets and collections, the Emory Digital Collections site is the digital front door to our newly re-architected digital repository.`

And I'll need your help with this one:
`The Cor digital preservation repository infrastructure developed by the Emory Libraries is built using the Samvera digital repository framework, collaboratively developed and maintained by dozens of organizations in the library and museum sectors. The Emory Digital Collections public interface is built upon Blacklight, and our management and preservation functionality is built upon Hyrax, Fedora, Solr, and other components within an AWS framework. Learn more about our technical implementation plans at <a href='https://wiki.service.emory.edu/pages/viewpage.action?pageId=140543688' class='static-blurb-link'>our wiki site</a>`

**Comment by eporter23** [comment]
@bwatson78 the technical implementation plans link should be updated to: https://emorylib.atlassian.net/wiki/spaces/DLPP/pages/20579112/Technical+Design+Phase+2018

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/756

**Comment by eporter23** [comment]
Looks good, thanks @bwatson78 ! Hopefully we can schedule a prod deploy soon.
