### ISSUE TITLE
2023 Upgrades for Lux (Blacklight, Rails, Ruby)

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#757]
Aiming for 
- [ ] Blacklight 7.33.1
- [ ] Rails 7.x
- [ ] Ruby 3.1.2

Necessary for future upgrades, keeps us up-to-date with the catalog, and starts us on view components.

**Comment by bwatson78** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGh0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fbfb55762ffbade0b1a189d54da853d6d84688b/Gunship%20-%20Zoom%20Background.jpg" alt="Gunship - Zoom Background.jpg" />

**Comment by bwatson78** [comment]
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHB0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7ef3e2a3ec01c7308a8c8d753b261c333f2ec10/IMG_0010.PNG" alt="IMG_0010.PNG" />
