### ISSUE TITLE
Search results page issues after Blacklight update

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#760]
This ticket relates to testing work done in #757.
When doing searches in digital-test, I am seeing a few issues with the search results page.

1. Search results: sorting drop-down does not render
2. Search results: records count drop-down does not render
3. Search results metadata: the field value is displaying vertically below the label instead of horizontally next to it

To replicate, do an empty browse search or any search that will generate more than 10 results.

**Expected behavior**
<img width="1671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3769f2602de57ec8b6b534ca1a232405d468a5ca/Screenshot%202024-02-09%20at%209.52.22%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 9.52.22 AM.png" />

<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--778cc4b0d7b61ef9b3c912b9f9fc3ea3a65372bd/Screenshot%202024-02-09%20at%209.52.15%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 9.52.15 AM.png" />

**Actual behavior**

<img width="922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aa6c82e072583cbcad92aa3be87e318104e8d33/Digital%20Test%20Results%20page%202024-02-09.png" alt="Digital Test Results page 2024-02-09.png" />

**Comment by bwatson78** [comment]
Pushed up commit `1e26d56db599c1c6d001439f654bcbecb20e5f56` that should address this.

**Comment by eporter23** [comment]
Looks good @bwatson78 !
