### ISSUE TITLE
Facet "more" modal content expands beyond container

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#762]
This ticket relates to testing work done in #757.

In digital-test, when exploring a facet with many values, the "more" modal window layout shows issues (tested in Mac Safari and Mac Chrome browsers).

To replicate, open a facet with many values such as Creator.
Click on the "more" link to open the full list.
Note that some of the navigation and sort elements are expanding beyond the modal size and partially disappear, particularly the upper row elements.

Expected behavior:

<img width="818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f24367dc5b2d30360c875ef2e2ad689bd977b679/Screenshot%202024-02-09%20at%2010.18.13%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 10.18.13 AM.png" />

Actual behavior:
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1ZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66d1fc8961af6ea509c606d58f1086b2d051820c/Screenshot%202024-02-09%20at%2010.19.24%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 10.19.24 AM.png" />

**Comment by bwatson78** [comment]
Commit `b8a54a7e1c33aa53b3fae8b3c36758f8477f1e89` addresses the styling above.
