### ISSUE TITLE
Ensure Curate indexes metadata display fields for Lux

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#88]
This ticket may be updated with additional information, but I wanted to provide the source documentation as soon as possible.

Ordering and grouping is still pending.

Link: https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit?usp=sharing

Column J describes whether a field is indexed.

**ACCEPTANCE** 
- [x] Review the attached field list and confirm that all have a human readable value indexed, 
if not
- [x] Create a curate ticket to index the human readable value for each missing field

**Comment by wulman16** [comment]
Below is the indexed metadata for a work in Curate with all possible metadata fields filled out:

![Screen Shot 2019-12-09 at 11.23.32 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/56a4bcbd-55c8-4669-a3fe-9182df740daa)![Screen Shot 2019-12-09 at 11.23.50 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/d2ded8b6-ffcf-4695-a241-ef4a8ecfba84)

The fields that need to be added to or removed from the index (or converted to human-readable format) are captured in this Curate ticket: https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/837

**Comment by nikdragovic** [comment]
@wulman16 Thanks for this! I was passing this by Emily and realized we decided not to index Persistent URL, D21. I forgot to make that change in the spreadsheet but will do that now. She is making the appropriate comment on the Curate ticket you created.

**Comment by eporter23** [comment]
@nikdragovic @wulman16 we will want to search by repository ID, though, even if it isn't stored in its URL form in metadata. We confirmed this is in SOLR from the Curate side, is there anything we need to do for Lux?

**Comment by wulman16** [comment]
@eporter23 @nikdragovic It looks like searching by repository ID works in Curate but not in Lux yet.

**Comment by nikdragovic** [comment]
Thanks, @wulman16!
