### ISSUE TITLE
Ensure Curate indexes the fields required for faceting

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-lux#89]
Review the following list for fields marked as "Y" in the "Facet - Lux" column (L)
Link: https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit?usp=sharing

**ACCEPTANCE** 
- [x] Review the attached field list and confirm that all fields marked for faceting are indexed appropriately
if not
- [ ] Create a curate ticket to index the facetable value for each missing field

**Comment by maxkadel** [comment]
Ensure that the facet is stored in Solr as "_ssim" (based on examples in catalog controller), in addition to any other stored version in Solr.

**Comment by tmiles2** [comment]
@maxkadel Do you have an estimate for this ticket?

**Comment by maxkadel** [comment]
Curate code has just been deployed, waiting for Curate to be re-indexed. I am about to kick off a re-index on curate-arch.
