### ISSUE TITLE
Install Shibboleth SP on digital/digital-test servers

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-lux#9]
- [x] Run Shibboleth ansible role against servers
- [x] Get metadata to Gerry
- [x] Confirm servers can reach Shibboleth QA/Prod servers and get a callback

**Comment by tmiles2** [comment]
@SolomonHD the request form has been submitted. INC03120551

**Comment by eporter23** [comment]
@SolomonHD @tmiles2 are we still blocked on this ticket?
